### ISSUE TITLE
Using the video last generated by mediapipe holistic, how to extract the video with only lines instead of the original person?

### ISSUE THREAD

**Issue by zjkafasf** [google/mediapipe#3996] opened 2023-01-14 05:35 UTC
<em>Please make sure that this is a [Tasks](https://developers.google.com/mediapipe/solutions) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in MediaPipe):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4):
- MediaPipe Tasks SDK version:
- Task name (e.g. Object detection, Gesture recognition etc.):
- Programming Language and version ( e.g. C++, Python, Java):

**Describe the expected behavior:**

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab, GitHub repo link or anything that we can use to reproduce the problem:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment] 2023-01-16 09:21
Hi @zjkafasf,
Would you let us know the platform you are referring such as Python, Javascript or other solution available and elaborate the query in the more details?

**Comment by kuaashish** [comment] 2023-01-17 16:50
Closing this issue as Duplicate of #3997. Please follow the another issue raised.

**Closed by kuaashish** 2023-01-17 16:50 UTC
Labels: type:support, platform:python, solution:holistic
