### ISSUE TITLE
Issue in build command

### ISSUE THREAD

**Issue by Takendra** [google/mediapipe#2751] opened 2021-11-08 04:47 UTC
On execution this command on ubuntu terminal 

bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu

below is the error 

/home/takendra/mediapipe/third_party/BUILD:186:6: //third_party:opencv_binary depends on @linux_opencv//:opencv in repository @linux_opencv which failed to fetch. no such package '@linux_opencv//': /home/takendra/mediapipe/third_party/opencv_linux.BUILD is not a regular file

**Comment by sgowroji** [comment] 2021-11-08 06:53
Hi @Takendra, There is already an issue with similar error and Duplicate of (https://github.com/google/mediapipe/issues/2723).

**Comment by kuaashish** [comment] 2022-11-29 10:12
Closing this issue as Duplicate of #2723

**Closed by kuaashish** 2022-11-29 10:12 UTC
Labels: status:duplicate, type:build/install, platform:android, solution:hands
