### ISSUE TITLE
Why isn't Colab, which was working just two days ago, not working? Install mediapipe-model-maker

### ISSUE THREAD

**Issue by sd23w** [google/mediapipe#4790] opened 2023-09-13 04:22 UTC
hi

https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/customization/object_detector.ipynb

I was working by following the "Object detection model customization guide" in the link above.
I confirmed that it runs all the way to the end of the source code, and I also confirmed that I downloaded a separate file and learned it.
There was no problem until two days ago, and today I turned on Colab again and made it work, but an error occurred from the first installation part.

```shell


!pip install mediapipe-model-maker
 
Error message:

Collecting pyyaml<5.4.0,>=5.1 (from tf-models-official>=2.13.1->mediapipe-model-maker)
   Using cached PyYAML-5.3.1.tar.gz (269 kB)
   error: subprocess-exited-with-error
  
   × python setup.py egg_info did not run successfully.
   │ exit code: 1
   ╰─> See above for output.
  
   note: This error originates from a subprocess, and is likely not a problem with pip.
   Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.


```

I tried several updates, but it still didn't work.

We came close to finishing, but it became very difficult.

What happened? Has something changed?

**Comment by kuaashish** [comment] 2023-09-13 04:41
@sd23w,

We are already aware of this issue, And team is actively working on it. However, We see it is duplicate of #4784 And Closing it. We recommend you to follow up with issue #4784 for further updates.

**Closed by kuaashish** 2023-09-13 04:41 UTC
Labels: type:modelmaker

**Comment by kuaashish** [comment] 2023-09-15 11:50
@sd23w,

The matter has been successfully addressed, and for enhanced clarity, you may consult this comment [here](https://github.com/google/mediapipe/issues/4784#issuecomment-1719838585). Thank you
