### ISSUE TITLE
If tensorflow is imported first, media pipe solution hangs indefinitely 

### ISSUE THREAD

**Issue by NikhilBadami** [google/mediapipe#1461] opened 2021-01-04 05:39 UTC
I was recently using the pose estimation solution in mediapipe in Python and came across an interesting bug. I found that if I imported tensorflow before importing mediapipe, it would cause the mediapipe library to hang indefinitely, but importing tensorflow second fixed this issue. The code I used to test this is below:

```
# import tensorflow --> Uncommenting this line will cause this file to hang
import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose
if __name__ == "__main__":
    # For static images:
    pose = mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.5)
    path = "some/image/path"
    image = cv2.imread(path)
    image_hight, image_width, _ = image.shape
    # Convert the BGR image to RGB before processing.
    results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB)) --> This is the line the script hangs on

    # Draw pose landmarks on the image.
    annotated_image = image.copy()
    mp_drawing.draw_landmarks(
      annotated_image, results.pose_landmarks, mp_pose.POSE_CONNECTIONS)
    cv2.imshow('', annotated_image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
    pose.close()
```

I am working on a Mac on Catalina

**Comment by jiuqiant** [comment] 2021-01-05 20:06
It hangs at https://github.com/google/mediapipe/blob/master/mediapipe/python/solution_base.py#L301 where it's waiting for the results coming back from the c++ graph execution logic.

MediaPipe has the c++ tflite inference engine in its binary. So, my initial guess is this weird behavior is caused by the confication between MediaPipe's builtin tflite inference engine and TensorFlow's tflite inference engine. For example, who gets imported first can be registered and the latter one will be totally ignored.

**Comment by danhd123** [comment] 2021-01-12 00:23
Same thing happens with ObjC/Swift on iOS. Mediapipe should probably include a warning in the documentation that you can't import Tensorflow separately and expect it to work.

**Comment by 4sfaloth** [comment] 2021-04-14 14:09
any news on this? I may be experiencing the same issue, though it is not fixed by importing tensorflow first

**Comment by sgowroji** [comment] 2021-08-10 07:26
Hi @NikhilBadami, Could you please respond if you still seeing the above observation with the [latest](https://google.github.io/mediapipe/solutions/pose.html#python-solution-api) release.

**Comment by sgowroji** [comment] 2021-10-06 04:40
We are reopening this issue as this still exist even with the latest release.

**Comment by flacle** [comment] 2022-05-29 11:06
> It hangs at https://github.com/google/mediapipe/blob/master/mediapipe/python/solution_base.py#L301 where it's waiting for the results coming back from the c++ graph execution logic.
> 
> MediaPipe has the c++ tflite inference engine in its binary. So, my initial guess is that the weird behavior is caused by the conflicts between MediaPipe's builtin tflite inference engine and TensorFlow's tflite inference engine. It's possible that who gets imported first will be registered and the latter one will be totally ignored.

In case you are working with classes, for this special case it might help to scope `tensorflow` on a class level by using `import_module` from `importlib`. Something like this in your `__init__()`:
```
self.__tf = importlib.import_module('tensorflow')
```

**Comment by sureshdagooglecom** [comment] 2022-09-23 05:29
Hi @NikhilBadami ,
Are you still looking for the resolution on this issue.

**Closed** 2022-10-07 05:47 UTC
Labels: type:support, stat:awaiting response, platform:python, solution:pose, stalled
