### ISSUE TITLE
Python API support for multi hand tracking

### ISSUE THREAD

**Issue by SuhelNaryal** [google/mediapipe#1165] opened 2020-09-30 09:36 UTC
Hi,
When can we expect python API support for multi hand tracking? I need the python API for my application.

**Comment by jiuqiant** [comment] 2020-09-30 16:44
A duplicate of thttps://github.com//issues/1095.

**Comment by jiuqiant** [comment] 2020-09-30 16:45
A duplicate of https://github.com//issues/1095. In short, we are going to release more solution APIs in Q4. Will keep you updated.

**Closed by jiuqiant** 2020-09-30 16:45 UTC
Labels: python

**Comment by ksanjeevan** [comment] 2020-10-17 04:44
Hi @jiuqiant, I need to use this for an app and was considering implementing it myself with the `tflite` models that are available. Do you perhaps have approximate time in Q4 when you plan on releasing this? Just so I know if I should just wait. Thanks!

**Comment by mgyong** [comment] 2020-11-05 06:11
MediaPipe v0.8 - Python solutions APIs for Face Mesh, Hands and Upper body pose released! https://github.com/google/mediapipe/releases/tag/0.8.0 Try the colab https://google.github.io/mediapipe/#mediapipe-in-python
