### ISSUE TITLE
Hand Landmark Detection Quality in Python Is Not as Good as the Web Version

### ISSUE THREAD

**Issue by yiusay** [google/mediapipe#4934] opened 2023-11-05 12:34 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Windows 11

### MediaPipe Tasks SDK version

0.10.7

### Task name (e.g. Image classification, Gesture recognition etc.)

Hand landmarks detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

Hand landmark detection often fails in Python but it does not on the Web

### Describe the expected behaviour

Hand landmark detection in Python should be as stable as the web version.

Here's a video demonstrating Hand landmark detection in Python and on the web for similar movements.
https://drive.google.com/file/d/1TyifyUkeWEpGtQPZ5RRl1v-5_DvPy2LF/view?usp=sharing

While the detection is stable in the provided web sample (https://codepen.io/mediapipe-preview/pen/gOKBGPN), it frequently fails in the Python version.

Since the model is the same, the results should be equivalent. I suspect there may be an issue in my Python code. Can you help me identify the problem?

### Standalone code/steps you may have used to try to get what you need

```shell
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision

from mediapipe import solutions
from mediapipe.framework.formats import landmark_pb2

import numpy as np
import cv2
import time
import sys
import logging

logging.basicConfig(level=logging.ERROR)

def draw_hand_landmarks_on_image(rgb_image, detection_result):
  hand_landmarks_list = detection_result.hand_landmarks  
  annotated_image = np.copy(rgb_image)

  if hand_landmarks_list is not None:
    # Loop through the detected hands to visualize.
    for idx in range(len(hand_landmarks_list)):
        hand_landmarks = hand_landmarks_list[idx]

        # Draw the hand landmarks.
        hand_landmarks_proto = landmark_pb2.NormalizedLandmarkList()
        hand_landmarks_proto.landmark.extend([
        landmark_pb2.NormalizedLandmark(x=landmark.x, y=landmark.y, z=landmark.z) for landmark in hand_landmarks
        ])
        solutions.drawing_utils.draw_landmarks(
        annotated_image,
        hand_landmarks_proto,
        solutions.hands.HAND_CONNECTIONS,
        solutions.drawing_styles.get_default_hand_landmarks_style(),
        solutions.drawing_styles.get_default_hand_connections_style())
    
  return annotated_image

last_timestamp = 0
rendered_image = None

BaseOptions = mp.tasks.BaseOptions
HandLandmarker = mp.tasks.vision.HandLandmarker
HandLandmarkerOptions = mp.tasks.vision.HandLandmarkerOptions
HandLandmarkerResult = mp.tasks.vision.HandLandmarkerResult
VisionRunningMode = mp.tasks.vision.RunningMode

# Create a face landmarker instance with the live stream mode:
def callback(result: HandLandmarkerResult, output_image: mp.Image, timestamp_ms: int):
    global rendered_image
    try:
        rendered_image = draw_hand_landmarks_on_image(output_image.numpy_view(), result)
    except Exception as e:
        logging.error(f"Error in callback function: {e}")

options = HandLandmarkerOptions(
    base_options=BaseOptions(model_asset_path='hand_landmarker.task'),
    running_mode= VisionRunningMode.LIVE_STREAM,
    num_hands = 2,
    result_callback=callback
)

with HandLandmarker.create_from_options(options) as landmarker:

    cap = cv2.VideoCapture(2, cv2.CAP_DSHOW)
    while cap.isOpened():
        start_time = time.time()

        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            continue

        image = cv2.flip(image, 1)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image)

        timestamp = time.time()
        if timestamp <= last_timestamp:
           continue

        landmarker.detect_async(mp_image, mp.Timestamp.from_seconds(timestamp).value)
        last_timestamp = timestamp

        if rendered_image is not None:
            cv2.imshow('hand landmarks', rendered_image)

        key = cv2.waitKey(1)
        if key == 27:
            sys.exit(1)
```

### Other info / Complete Logs

```shell
```

**Comment by yiusay** [comment] 2023-11-06 07:59
Maybe I have found out the issue. 

It seems we need to convert an input image from BGR to RGB before feeding the image into the model since OpenCV is using BGR color format while mediapipe expects RGB.
cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

**Comment by kuaashish** [comment] 2023-11-06 09:34
Hi @yiusay,

The expected behaviour is as anticipated, with both platforms supporting different graph structures. Python utilises the CPU graph, while JavaScript employs the GPU graph, leading to slightly better performance. We want to inform you that Python GPU wheels will soon be released via pip, providing an opportunity to assess performance later. 

However, we currently cannot commit to a specific timeline for the release. It's worth noting that the scenario you explained in the previous comment may contribute to a slight increase in performance compared to JavaScript.

Thank you

**Comment by yiusay** [comment] 2023-11-06 10:18
Thank you for your prompt response. I'm delighted to hear that GPU support for Windows Python will be available soon. Your hard work is much appreciated!

**Comment by kuaashish** [comment] 2023-11-06 10:50
Hi @yiusay,

Could you please inform us if the issue is no longer present on your end? If so, may we proceed to close the issue and update the status to resolved?  Thank you

**Closed** 2023-11-06 11:09 UTC
Labels: type:support, stat:awaiting response, os:windows, platform:python, platform:javascript, task:hand landmarker
