### ISSUE TITLE
How to reduce cpu and memory utilization

### ISSUE THREAD

**Issue by xiaolinpeter** [google/mediapipe#4096] opened 2023-02-14 10:20 UTC
I  use mediapipe  hands in windows ，  the cpu  utilization is 18% and the memory utilization is 240mb， I want to  reduce cpu and memory utilization, I hope someone give me sugggestion , thanks

**Comment by ayushgdev** [comment] 2023-02-14 11:19
Hello @xiaolinpeter 
Please provide details on the issue regarding the language you are working with to address your issue better. We encourage you to use [this template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Asupport&template=Solution%28Legacy_issue_template%29.yaml) which captures all necessary details required to serve your query better.
Also, do you see any memory issue with the examples provided in the [documentation](https://google.github.io/mediapipe/solutions/hands.html)?

**Comment by ayushgdev** [comment] 2023-02-21 04:54
Closing this issue as duplicate of #4109 .

**Closed by ayushgdev** 2023-02-21 04:54 UTC
Labels: solution:hands, stat:awaiting response, type:performance
