### ISSUE TITLE
Mediapipe face mesh - One single unmovable index at the center of each Eyes appear

### ISSUE THREAD

**Issue by aishwarya123mathpati** [google/mediapipe#4705] opened 2023-08-17 09:09 UTC
- One single unmovable index at the center of each Eyes appear. 
- When all other landmarks are moving as per there face movement, that single landmark is not moving.
- Need to know the reason for that steadiness of landmark.

**Comment by kuaashish** [comment] 2023-08-17 11:26
@aishwarya123mathpati,

Closing this as duplicate of #4688. Please follow up with another issue raised. Thank you

**Closed by kuaashish** 2023-08-17 11:26 UTC
