### ISSUE TITLE
Cannot run @mediapipe/holistic in the web worker

### ISSUE THREAD

**Issue by byy01** [google/mediapipe#3406] opened 2022-06-08 02:40 UTC
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): yes
- OS Platform and Distribution : Window 10
- [MediaPipe version] @mediapipe/holistic0.5.1635989137
- Bazel version: n/a
- Solution (e.g. FaceMesh, Pose, Holistic): Holistic
- Programming Language and version ( e.g. C++, Python, Java): javascript

**Describe the expected behavior:**
I would like to run @mediapipe/holistic in a to avoid performance issues with other code on the main thread.

**Standalone code you may have used to try to get what you need :**
Worker

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

web_worker.js code :
![image](https://user-images.githubusercontent.com/58766685/172519300-09c0cd9a-c543-4918-b4f4-f79869b67b48.png)

error message :
![image](https://user-images.githubusercontent.com/58766685/172519435-75bc2cab-7738-4105-9907-f0729b631c6b.png)

If I don't use the web worker, it works well without errors.

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

**Comment by mattrossman** [comment] 2022-06-08 16:49
Duplicate of #2506, also related #2574

Big +1 to this though.

**Comment by byy01** [comment] 2022-06-09 08:07
> Duplicate of

if I don't run it in a web worker, it runs well without errors, but the web page stops for a while.

so I should run it in a web worker.

If I initialize holistic when running in a web worker, an error occurs when I load wasm, how I you fix it?

I think I set the locateFile path well.

**Comment by sureshdagooglecom** [comment] 2022-06-09 08:29
Hi @byy01 ,
Did you resolve the issue as per https://github.com/google/mediapipe/issues/3406#issuecomment-1150807432  or still are you facing any challenges.

**Comment by sureshdagooglecom** [comment] 2022-06-20 10:15
Hi @byy01 ,
Could you please share code changes to investigate on this issue.

**Closed** 2022-07-04 11:11 UTC
Labels: type:support, stat:awaiting response, platform:javascript, solution:holistic, stalled
