### ISSUE TITLE
Missing Model Card for Object Detection

### ISSUE THREAD

**Issue by glnmzx888** [google/mediapipe#1998] opened 2021-05-07 13:39 UTC
In MediaPipe, there are many pre-trained models, like Object Detection. Is this object detection model the same as the example model cards specified in (https://modelcards.withgoogle.com/model-reports)? If not, could you please provide its corresponding model card information similar to all the other public ML models as in https://google.github.io/mediapipe/solutions/models.html?

**Comment by sgowroji** [comment] 2021-05-26 06:20
Duplicate https://github.com/google/mediapipe/issues/1999

**Comment by chuoling** [comment] 2021-07-12 04:37
@sgowroji This issue is more about [Object Detection](https://google.github.io/mediapipe/solutions/object_detection.html), not [Objectron](https://google.github.io/mediapipe/solutions/objectron.html), and therefore not a duplicate of #1999.

**Comment by chuoling** [comment] 2021-07-12 04:39
@glnmzx888 Please find information about this object detection model in https://github.com/google/mediapipe/blob/master/mediapipe/models/object_detection_saved_model/README.md.

**Comment by glnmzx888** [comment] 2021-07-23 02:49
Thank you (@chuoling)  very much for your reply!

The readme file has provided the information on the training dataset and the detailed model algorithm. However, certain information that we are looking for, in particular things like intended use cases or limitations, potential pitfalls, and performance characteristics, is missing. Such information/attributes are part of the model card information as described in the published paper “Model Cards for Model Reporting”.

Can you please provide such information, as they can help us study/evaluate the proper deployment context or pitfalls to avoid when using such models in practice?

Thanks again and we are happy to provide more details/rationales if needed.

**Comment by ahmadyan** [comment] 2021-09-13 19:04
@glnmzx888 The model for object detection is from Tensorflow Object Detection API, so you can ping them about the model card and more information.

 https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

To answer your original question, it is not. The TF object detection API has a library of different models, the one linked above that Google Cloud uses is based on ResNet101 backend whereas the model in Mediapipe is based on MobileNet-SSD backend, which is optimized for on-device performance.

**Closed** 2021-10-01 06:18 UTC
Labels: stat:awaiting response, solution:object detection, type:docs-feature, stalled
