### ISSUE TITLE
Tutorial Hello World App closes constantly on device

### ISSUE THREAD

**Issue by endersaka** [google/mediapipe#948] opened 2020-07-26 04:04 UTC
Hi,

I am following https://google.github.io/mediapipe/getting_started/hello_world_android.html#initial-minimal-application-setup

The app interrupts just after I launch it. I tried to launch it either manually and with the `adb shell`.

This is the only output I get, from shell.

```bash
a40:/ $  am start-activity -D -N com.myagency.mediapipe.helloworld/.MainActivity
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.myagency.mediapipe.helloworld/.MainActivity }
cmd: Failure calling service activity: Broken pipe (32)
```

This is the build command and log:

```bash
$ bazel --output_user_root=/Users/username/tmp/_bazel_username build -c opt --config=android_arm64 saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld
WARNING: Output base '/Users/username/tmp/_bazel_username/fcb58a7ae07d9f9bce35a80cbb3eb208' is on a non-local drive. This may lead to surprising failures and undetermined behavior.
WARNING: The major revision of the Android NDK referenced by android_ndk_repository rule 'androidndk' is 21. The major revisions supported by Bazel are [10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]. Bazel will attempt to treat the NDK as if it was r20. This may cause compilation and linkage problems. Please download a supported NDK version.
WARNING: API level 29 specified by android_ndk_repository 'androidndk' is not available. Using latest known API level 28
INFO: Analyzed target //saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld (44 packages loaded, 7041 targets configured).
INFO: Found 1 target...
INFO: From Processing Android resources for //saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld:
Warning: /Users/username/tmp/_bazel_username/fcb58a7ae07d9f9bce35a80cbb3eb208/sandbox/darwin-sandbox/289/execroot/mediapipe/bazel-out/arm64-v8a-opt/bin/saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld/_merged/helloworld/AndroidManifest.xml:25:9-34:20 Warning:
	Element activity#com.myagency.mediapipe.helloworld.MainActivity at AndroidManifest.xml:25:9-34:20 duplicated with element declared at AndroidManifest.xml:15:9-24:20
Target //saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld:helloworld up-to-date:
  bazel-bin/saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld/helloworld_deploy.jar
  bazel-bin/saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld/helloworld_unsigned.apk
  bazel-bin/saiam/mediapipe/getting_started/hello_world_android/src/java/com/myagency/mediapipe/helloworld/helloworld.apk
INFO: Elapsed time: 382.196s, Critical Path: 368.57s
INFO: 301 processes: 237 darwin-sandbox, 64 worker.
INFO: Build completed successfully, 341 total actions
```

Java Version

today
```bash
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.8+10, mixed mode)
```

yesterday
```bash
$ java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) 64-Bit Server VM (build 25.73-b02, mixed mode)
```

Installed SDKs and Tools (i noticed that some tools do not run over Java 11, though I tried compilation yesterday with Java 8 and I got the same identical results)

```bash
$ sdkmanager --list
Warning: File /Users/username/.android/repositories.cfg could not be loaded.    
Installed packages:=====================] 100% Computing updates...             
  Path                                                                              | Version      | Description                                     | Location                                                                          
  -------                                                                           | -------      | -------                                         | -------                                                                           
  build-tools;28.0.3                                                                | 28.0.3       | Android SDK Build-Tools 28.0.3                  | build-tools/28.0.3/                                                               
  build-tools;29.0.3                                                                | 29.0.3       | Android SDK Build-Tools 29.0.3                  | build-tools/29.0.3/                                                               
  build-tools;30.0.0-rc4                                                            | 30.0.0 rc4   | Android SDK Build-Tools 30-rc4                  | build-tools/30.0.0-rc4/                                                           
  build-tools;30.0.1                                                                | 30.0.1       | Android SDK Build-Tools 30.0.1                  | build-tools/30.0.1/                                                               
  cmdline-tools;latest                                                              | 2.1          | Android SDK Command-line Tools (latest)         | cmdline-tools/latest/                                                             
  emulator                                                                          | 30.0.12      | Android Emulator                                | emulator/                                                                         
  extras;android;m2repository                                                       | 47.0.0       | Android Support Repository                      | extras/android/m2repository/                                                      
  extras;google;m2repository                                                        | 58           | Google Repository                               | extras/google/m2repository/                                                       
  extras;intel;Hardware_Accelerated_Execution_Manager                               | 7.5.1        | Intel x86 Emulator Accelerator (HAXM installer) | extras/intel/Hardware_Accelerated_Execution_Manager/                              
  extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2 | 1            | Solver for ConstraintLayout 1.0.2               | extras/m2repository/com/android/support/constraint/constraint-layout-solver/1.0.2/
  extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2        | 1            | ConstraintLayout for Android 1.0.2              | extras/m2repository/com/android/support/constraint/constraint-layout/1.0.2/       
  ndk;20.1.5948944                                                                  | 20.1.5948944 | NDK (Side by side) 20.1.5948944                 | ndk/20.1.5948944/                                                                 
  ndk;21.1.6352462                                                                  | 21.1.6352462 | NDK (Side by side) 21.1.6352462                 | ndk/21.1.6352462/                                                                 
  ndk;21.3.6528147                                                                  | 21.3.6528147 | NDK (Side by side) 21.3.6528147                 | ndk/21.3.6528147/                                                                 
  patcher;v4                                                                        | 1            | SDK Patch Applier v4                            | patcher/v4/                                                                       
  platform-tools                                                                    | 30.0.3       | Android SDK Platform-Tools                      | platform-tools/                                                                   
  platforms;android-28                                                              | 6            | Android SDK Platform 28                         | platforms/android-28/                                                             
  platforms;android-29                                                              | 4            | Android SDK Platform 29                         | platforms/android-29/                                                             
  sources;android-28                                                                | 1            | Sources for Android 28                          | sources/android-28/                                                               
  sources;android-29                                                                | 1            | Sources for Android 29                          | sources/android-29/                                                               
  system-images;android-29;google_apis_playstore;x86                                | 8            | Google Play Intel x86 Atom System Image         | system-images/android-29/google_apis_playstore/x86/                               
  tools                                                                             | 26.1.1       | Android SDK Tools                               | tools/                                                                            
```

I  have Italian localization, the text in the screenshot means: "The Hello World app keeps stopping".

![Screenshot_20200726-035907_One UI Home](https://user-images.githubusercontent.com/6204818/88470880-4e5fb200-cf02-11ea-8ed7-b5a215c7e969.jpg)

**Comment by endersaka** [comment] 2020-07-26 04:42
Eureka! 😃 

I didn't know how to do but I have found how to get the log (`adb logcat | grep -e " E "`).

This, at least, is a step forward.

```
07-26 06:35:19.276 17359 17359 E AndroidRuntime: FATAL EXCEPTION: main
07-26 06:35:19.276 17359 17359 E AndroidRuntime: Process: com.myagengy.mediapipe.helloworld, PID: 17359
07-26 06:35:19.276 17359 17359 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.myagengy.mediapipe.helloworld/com.myagengy.mediapipe.helloworld.MainActivity}: android.view.InflateException: Binary XML file line #2 in com.myagengy.mediapipe.helloworld:layout/activity_main: Binary XML file line #2 in com.myagengy.mediapipe.helloworld:layout/activity_main: Error inflating class android.support.constraint.ConstraintLayout
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3556)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7948)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2 in com.myagengy.mediapipe.helloworld:layout/activity_main: Binary XML file line #2 in com.myagengy.mediapipe.helloworld:layout/activity_main: Error inflating class android.support.constraint.ConstraintLayout
07-26 06:35:19.276 17359 17359 E AndroidRuntime: Caused by: android.view.InflateException: Binary XML file line #2 in com.myagengy.mediapipe.helloworld:layout/activity_main: Error inflating class android.support.constraint.ConstraintLayout
07-26 06:35:19.276 17359 17359 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.support.constraint.ConstraintLayout
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.createView(LayoutInflater.java:815)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1006)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:961)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:659)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:534)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:481)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:545)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at com.myagengy.mediapipe.helloworld.MainActivity.onCreate(MainActivity.java:12)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7955)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7944)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:237)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7948)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
07-26 06:35:19.276 17359 17359 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: android.support.constraint.ConstraintLayout
07-26 06:35:19.276 17359 17359 E AndroidRuntime: 	... 26 more
```

**Comment by endersaka** [comment] 2020-07-26 06:05
Ok,

I resolved.
Your documentation is obsolete? Totally wrong? I don't know. Though the code of the `res/layout/activity_main.xml` file from the tutorial...

```
<?xml version="1.0" encoding="utf-8"?>
<android.support.constraint.ConstraintLayout
```

should be

```
<?xml version="1.0" encoding="utf-8"?>
<androidx.constraintlayout.widget.ConstraintLayout
 ```

**Comment by eknight7** [comment] 2020-07-26 20:58
Thanks for the feedback, we will update our docs. Per your latest comment, the issue is resolved so we are closing this. Feel free to reopen or post new questions.

**Closed by eknight7** 2020-07-26 20:58 UTC
