### ISSUE TITLE
abi:cxx11 undefined reference to `std::allocator...

### ISSUE THREAD

**Issue by honglh** [google/mediapipe#1585] opened 2021-02-04 19:31 UTC
I am cross-compiling mediapipe for my aarch64 target. With changes to the crosstool mainly to setup the right path for my toolchain, I **almost** can build successfully (e.g. target mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu)

The compile went through with no issues. The last linking failed
```
bazel-out/aarch64-opt/bin/mediapipe/framework/deps/libregistration.a(registration.o): In function `mediapipe::NamespaceWhitelist::TopNamespaces[abi:cxx11]()':
registration.cc:(.text._ZN9mediapipe18NamespaceWhitelist13TopNamespacesB5cxx11Ev+0x48): undefined reference to `std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::allocator()'
```

I can see that that **absl** is built with c++17,  along with packages from mediapipe, and I am using libstdc++.so from the standard released `aarch64-linux-gnu` `libstdc++.so.6.0.25`  For example this is the message when building `absl/container/raw_hash_seet`

```
  /usr/bin/aarch64-linux-gnu-gcc -fPIC -U_FORTIFY_SOURCE -fstack-protector
   -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer 
  '-march=armv8-a' -g0 -O3 -DNDEBUG '-D_FORTIFY_SOURCE=2' -ffunction-sections 
  -fdata-sections -funsafe-math-optimizations -ftree-vectorize 


  '-std=c++11'  <============

  -MD -MF bazel-out/aarch64-opt/bin/external/com_google_absl/absl/container/_objs/raw_hash_set/raw_hash_set.d
  '-frandom-seed=bazel-out/aarch64-opt/bin/external/com_google_absl/absl/container/_objs/raw_hash_set/raw_hash_set.o' 
  -iquote external/com_google_absl -iquote bazel-out/aarch64-opt/bin/external/com_google_absl -w 

  '-std=c++17'  <============

  -Wall -Wextra -Wcast-qual -Wconversion-null 
  -Wmissing-declarations -Woverlength-strings -Wpointer-arith 
  -Wundef -Wunused-local-typedefs -Wunused-result -Wvarargs 
  -Wvla -Wwrite-strings -Wno-missing-field-initializers -Wno-sign-compare 
  -DNOMINMAX -no-canonical-prefixes -fno-canonical-system-headers 
  -Wno-builtin-macro-redefined '-D__DATE__="redacted"' 
  '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' 
  -c external/com_google_absl/absl/container/internal/raw_hash_set.cc 
  -o bazel-out/aarch64-opt/bin/external/com_google_absl/absl/container/_objs/raw_hash_set/raw_hash_set.o
```

If I simply comment out the a few lines that references `NamespaceWhitelist::TopNamespaces` then the build completes successfully.

Any thoughts what might be the reason of this error? It seems that `std::__cxx11::basic_string` is in the libstdc++.so.6.0.25

**Comment by honglh** [comment] 2021-02-04 19:36
However, if I simply build for aarch64 target for RPI, then it works. The only difference is that when building my target, I setup the include path to the ones from my toolchain. As mentioned, all compile worked out, and the only issue is at linking NamespaceWhitelist::TopNamespaces() which uses `absl::flat_hash_set<std::string>` and that caused the `abi:cxx11` issue 
(all other places of `absl::flat_hash_set` uses `<int>` type though, so only `absl::flat_hash_set<string>` is failing

**Comment by honglh** [comment] 2021-02-08 16:24
Forcing a declaration in `registration.cc` also can workaround the issue
```
+  std::allocator<std::string> __dummy_string_workaround_github_issue_1585__;
```

full diff:
```
diff --git a/mediapipe/framework/deps/registration.cc b/mediapipe/framework/deps/registration.cc
index c6a3ffa..1ec3d38 100644
--- a/mediapipe/framework/deps/registration.cc
+++ b/mediapipe/framework/deps/registration.cc
@@ -37,6 +37,7 @@ inline size_t array_size(T (&arr)[SIZE]) {

 /*static*/
 const absl::flat_hash_set<std::string>& NamespaceWhitelist::TopNamespaces() {
+  std::allocator<std::string> __dummy_string_workaround_github_issue_1585__;
   static absl::flat_hash_set<std::string>* result =
       new absl::flat_hash_set<std::string>(
           kTopNamespaces, kTopNamespaces + array_size(kTopNamespaces));
```

**Comment by jiuqiant** [comment] 2021-04-16 19:36
Glad to hear that the problem is solved. Closing this issue now.

**Closed by jiuqiant** 2021-04-16 19:36 UTC
Labels: type:build/install
