### ISSUE TITLE
Support for full body pose tracking

### ISSUE THREAD

**Issue by BetaPundit** [google/mediapipe#1086] opened 2020-09-05 08:20 UTC
Currently, the examples contain code for upper body pose tracking. When shall we get the support for full-body pose tracking?
Or is there a way to update the code for upper body tracking to include the lower body as well?

**Comment by mgyong** [comment] 2020-09-05 17:16
Duplicate of #1066 #1022

**Closed by mgyong** 2020-09-05 17:16 UTC
Labels: feature request
