### ISSUE TITLE
problem with switching between a large number of effects (faceeffect)

### ISSUE THREAD

**Issue by milad-4274** [google/mediapipe#1841] opened 2021-04-04 10:00 UTC
Hi, I'm modifying faceeffect example. I want to switch between a lot effects (about 25 effects). but when I add more than 10-15 effect renderer calculator, the app does not open and my phone freeze (I think it's memory problem). It's ok when I use less than 10 calculator. Is there any solution to change the effect without consecutive render calculators? for example by passing the texture path as an input_stream? if not what is the solution. 
Tank you.
the sample graph I used: 
```
# MediaPipe graph that applies a face effect to the input video stream.

# GPU buffer. (GpuBuffer)
input_stream: "input_video"

input_stream: "effect_type1"
input_stream: "effect_type2"

input_stream: "effect_type3"


# Indicates whether to use the face detection as the input source. (bool)
#
# If `true`, the face detection pipeline will be used to produce landmarks.
# If `false`, the face landmark pipeline will be used to produce landmarks.
# input_side_packet: "use_face_detection_input_source"

# Output image with rendered results. (GpuBuffer)
output_stream: "output_video"

# A list of geometry data for a single detected face.
#
# NOTE: there will not be an output packet in this stream for this particular
# timestamp if none of faces detected.
#
# (std::vector<face_geometry::FaceGeometry>)
output_stream: "multi_face_geometry"

# Throttles the images flowing downstream for flow control. It passes through
# the very first incoming image unaltered, and waits for downstream nodes
# (calculators and subgraphs) in the graph to finish their tasks before it
# passes through another image. All images that come in while waiting are
# dropped, limiting the number of in-flight images in most part of the graph to
# 1. This prevents the downstream nodes from queuing up incoming images and data
# excessively, which leads to increased latency and memory usage, unwanted in
# real-time mobile applications. It also eliminates unnecessarily computation,
# e.g., the output produced by a node may get dropped downstream if the
# subsequent nodes are still busy processing previous inputs.
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}

# Generates an environment that describes the current virtual scene.
node {
  calculator: "FaceGeometryEnvGeneratorCalculator"
  output_side_packet: "ENVIRONMENT:environment"
  node_options: {
    [type.googleapis.com/mediapipe.FaceGeometryEnvGeneratorCalculatorOptions] {
      environment: {
        origin_point_location: TOP_LEFT_CORNER
        perspective_camera: {
          vertical_fov_degrees: 63.0  # 63 degrees
          near: 1.0  # 1cm
          far: 10000.0  # 100m
        }
      }
    }
  }
}


node {
  calculator: "SingleFaceGeometryFromLandmarksGpu"
  input_stream: "IMAGE:throttled_input_video"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
}

# Renders the selected effect based on `selected_effect_id`.
node {
  calculator: "SwitchContainer"
  input_stream: "SELECT:effect_type1"
  input_stream: "IMAGE_GPU:throttled_input_video"
  input_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "IMAGE_GPU:effect1_res"
  node_options: {
    [type.googleapis.com/mediapipe.SwitchContainerOptions] {
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect11.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect12.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect13.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect14.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect15.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect16.pngblob"
          }
        }
      }
      


    }
  }
}


node {
  calculator: "SwitchContainer"
  input_stream: "SELECT:effect_type3"
  input_stream: "IMAGE_GPU:effect1_res"
  input_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "IMAGE_GPU:effect2_res"
  node_options: {
    [type.googleapis.com/mediapipe.SwitchContainerOptions] {
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect21.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect22.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect23.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect24.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect25.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect26.pngblob"
          }
        }
      }


    }
  }
}



node {
  calculator: "SwitchContainer"
  input_stream: "SELECT:effect_type2"
  input_stream: "IMAGE_GPU:effect2_res"
  input_stream: "MULTI_FACE_GEOMETRY:multi_face_geometry"
  input_side_packet: "ENVIRONMENT:environment"
  output_stream: "IMAGE_GPU:output_video"
  node_options: {
    [type.googleapis.com/mediapipe.SwitchContainerOptions] {
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect31.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect32.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect33.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect34.pngblob"
          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect35.pngblob"

          }
        }
      }
      contained_node: {
        calculator: "FaceGeometryEffectRendererCalculator"
        node_options: {
          [type.googleapis.com/mediapipe.FaceGeometryEffectRendererCalculatorOptions] {
            effect_texture_path: "mediapipe/graphs/face_effect/data/effect36.pngblob"

          }
        }
      }


    }
  }
}


```

**Comment by milad-4274** [comment] 2021-04-12 10:31
any advice? 
I also check it without using "SwitchContainer" and the problem still exist.

**Comment by yazdanghaderi** [comment] 2021-04-13 06:36
I have similar problem when using 20 render calculator on weak hardware device(e.g Huawei honor 8C) crashed.

**Comment by jaywalk1414** [comment] 2021-04-17 05:16
Same issue. Is this really a bug ?

**Comment by brucechou1983** [comment] 2021-06-15 16:20
You might want to use only one calculator and send the effect textures via an input stream.

**Comment by milad-4274** [comment] 2021-06-16 04:40
> You might want to use only one calculator and send the effect textures via an input stream.

yes, It's what I want. but I think It's impossible with current calculator structure. should I write my own renderer calculator?

**Comment by brucechou1983** [comment] 2021-06-16 08:08
Yes, you need to modify the calculator. I've done something similar before.

1. Add a new input stream with packet specifying the texture resource path. Also add a private variable to store the current texture (could be empty by design). Remove texture setting from input side packet.
2. Use SyncSetInputStreamHandler for your new calculator in pbtxt, separate original input streams and the new one into two sets.
3. at Process() function of your calculator, if original set of packets is received, just render with current texture as usual. If texture path packet is received, select/load the target texture, reassign current texture and return.
4. At application level, bind the UI (say double tap event) with sending the next texture path packet. Note that the timestamp must be monotonically increasing. For example like Frame(t0) -> Texture(t1) -> Frame(t2).

Hope this helps.

**Comment by milad-4274** [comment] 2021-06-16 11:05
> Yes, you need to modify the calculator. I've done something similar before.
> 
> 1. Add a new input stream with packet specifying the texture resource path. Also add a private variable to store the current texture (could be empty by design). Remove texture setting from input side packet.
> 2. Use SyncSetInputStreamHandler for your new calculator in pbtxt, separate original input streams and the new one into two sets.
> 3. at Process() function of your calculator, if original set of packets is received, just render with current texture as usual. If texture path packet is received, select/load the target texture, reassign current texture and return.
> 4. At application level, bind the UI (say double tap event) with sending the next texture path packet. Note that the timestamp must be monotonically increasing. For example like Frame(t0) -> Texture(t1) -> Frame(t2).
> 
> Hope this helps.

Thank you for your great reply. I will do it and tell the result here.

**Closed** 2021-08-05 06:57 UTC
Labels: solution:face detection, stalled, stat:awaiting response, type:performance

**Comment by krithicappyhigh** [comment] 2022-09-11 09:28
@brucechou1983 thanks for reply. i've actually modified the existing `effect_renderer.cc` to fit my needs(although i'm not using a `SyncSetInputStreamHandler` here). but the app freezes and is being killed after i switch about 20-25 effects (this threshold actually depends on the device). i am suspecting an OOM here prolly because i'm leaking memory somewhere. i've looked into it for 2 days not but can't figure out why the app is being killed. here is my modified `effect_renderer.cc`:

```cpp
#include <memory>
#include <string>
#include <vector>

#include "absl/types/optional.h"
#include "mediapipe/framework/calculator_framework.h"
#include "mediapipe/framework/formats/image_frame.h"
#include "mediapipe/framework/formats/image_frame_opencv.h"
#include "mediapipe/framework/port/opencv_core_inc.h"       // NOTYPO
#include "mediapipe/framework/port/opencv_imgcodecs_inc.h"  // NOTYPO
#include "mediapipe/framework/port/opencv_imgproc_inc.h"    // NOTYPO
#include "mediapipe/framework/port/ret_check.h"
#include "mediapipe/framework/port/status.h"
#include "mediapipe/framework/port/status_macros.h"
#include "mediapipe/framework/port/statusor.h"
#include "mediapipe/gpu/gl_calculator_helper.h"
#include "mediapipe/gpu/gpu_buffer.h"
#include "mediapipe/modules/face_geometry/libs/effect_renderer.h"
#include "mediapipe/modules/face_geometry/libs/validation_utils.h"
#include "mediapipe/modules/face_geometry/protos/environment.pb.h"
#include "mediapipe/modules/face_geometry/protos/face_geometry.pb.h"
#include "mediapipe/modules/face_geometry/protos/mesh_3d.pb.h"
#include "mediapipe/util/resource_util.h"

namespace mediapipe {
namespace {

static constexpr char kEnvironmentTag[] = "ENVIRONMENT";
static constexpr char kImageGpuTag[] = "IMAGE_GPU";
static constexpr char kMultiFaceGeometryTag[] = "MULTI_FACE_GEOMETRY";

static constexpr char kEffectTexturePathTag[] = "TEXTURE_PATH";
static constexpr char kEffectMesh3dPathTag[] = "MESH3D_PATH";
static constexpr char kRenderFlag[] = "RENDER_FLAG";

class CustomEffectRendererCalculator : public CalculatorBase {
 public:
  static absl::Status GetContract(CalculatorContract* cc) {
    MP_RETURN_IF_ERROR(mediapipe::GlCalculatorHelper::UpdateContract(cc))
        << "Failed to update contract for the GPU helper!";

    cc->InputSidePackets()
        .Tag(kEnvironmentTag)
        .Set<face_geometry::Environment>();
    cc->Inputs().Tag(kImageGpuTag).Set<GpuBuffer>();

    cc->Inputs().Tag(kEffectTexturePathTag).Set<std::string>();
    cc->Inputs().Tag(kRenderFlag).Set<bool>();

    if (cc->Inputs().HasTag(kEffectMesh3dPathTag)) {
      cc->Inputs().Tag(kEffectMesh3dPathTag).Set<std::string>();
    }

    cc->Inputs()
        .Tag(kMultiFaceGeometryTag)
        .Set<std::vector<face_geometry::FaceGeometry>>();
    cc->Outputs().Tag(kImageGpuTag).Set<GpuBuffer>();

    return mediapipe::GlCalculatorHelper::UpdateContract(cc);
  }

  absl::Status Open(CalculatorContext* cc) override {
    cc->SetOffset(mediapipe::TimestampDiff(0));
    MP_RETURN_IF_ERROR(gpu_helper_.Open(cc))
        << "Failed to open the GPU helper!";

    return gpu_helper_.RunInGlContext([&]() -> absl::Status {
      environment_ = cc->InputSidePackets()
                         .Tag(kEnvironmentTag)
                         .Get<face_geometry::Environment>();
      MP_RETURN_IF_ERROR(face_geometry::ValidateEnvironment(environment_))
          << "Invalid environment!";
      return absl::OkStatus();
    });
  }

  absl::Status Process(CalculatorContext* cc) override {
    auto texture_path =
        cc->Inputs().Tag(kEffectTexturePathTag).Get<std::string>();
    if (texture_path != "") {
      current_texture_path = texture_path;
      current_mesh_3d_path =
          cc->Inputs().HasTag(kEffectMesh3dPathTag)
              ? cc->Inputs().Tag(kEffectMesh3dPathTag).Get<std::string>()
              : "";

      ReadFromInputStream(cc, current_texture_path, current_mesh_3d_path);
      initialized = true;

      cc->Outputs()
          .Tag(kImageGpuTag)
          .AddPacket(
              cc->Inputs().Tag(kImageGpuTag).Value().At(cc->InputTimestamp()));
      return absl::OkStatus();
    }

    if (!cc->Inputs().Tag(kImageGpuTag).IsEmpty()) {
      bool render_flag = cc->Inputs().Tag(kRenderFlag).Get<bool>();
      if (initialized && render_flag) {
        Render(cc);
        return absl::OkStatus();
      } else {
        cc->Outputs()
            .Tag(kImageGpuTag)
            .AddPacket(cc->Inputs()
                           .Tag(kImageGpuTag)
                           .Value()
                           .At(cc->InputTimestamp()));
        return absl::OkStatus();
      }
    }

    return absl::OkStatus();
  }

  ~CustomEffectRendererCalculator() {
    gpu_helper_.RunInGlContext([this]() { effect_renderer_.reset(); });
  }

 private:
  absl::Status ReadFromInputStream(CalculatorContext* cc,
                                   const std::string& texture_path,
                                   const std::string& mesh_3d_path) {
    return gpu_helper_.RunInGlContext([&]() -> absl::Status {
      absl::optional<face_geometry::Mesh3d> effect_mesh_3d;
      if (mesh_3d_path != "") {
        ASSIGN_OR_RETURN(effect_mesh_3d, ReadMesh3dFromFile(mesh_3d_path),
                         _ << "Failed to read the effect 3D mesh from file!");
      }

      ASSIGN_OR_RETURN(ImageFrame effect_texture,
                       ReadTextureFromFile(texture_path),
                       _ << "Failed to read the effect texture from file!");

      effect_renderer_.reset();
      ASSIGN_OR_RETURN(effect_renderer_,
                       CreateEffectRenderer(environment_, effect_mesh_3d,
                                            std::move(effect_texture)),
                       _ << "Failed to create the effect renderer!");

      return absl::OkStatus();
    });
  }

  absl::Status Render(CalculatorContext* cc) {
    return gpu_helper_.RunInGlContext([this, cc]() -> absl::Status {
      const auto& input_gpu_buffer =
          cc->Inputs().Tag(kImageGpuTag).Get<GpuBuffer>();

      GlTexture input_gl_texture =
          gpu_helper_.CreateSourceTexture(input_gpu_buffer);

      GlTexture output_gl_texture = gpu_helper_.CreateDestinationTexture(
          input_gl_texture.width(), input_gl_texture.height());

      std::vector<face_geometry::FaceGeometry> empty_multi_face_geometry;
      const auto& multi_face_geometry =
          cc->Inputs().Tag(kMultiFaceGeometryTag).IsEmpty()
              ? empty_multi_face_geometry
              : cc->Inputs()
                    .Tag(kMultiFaceGeometryTag)
                    .Get<std::vector<face_geometry::FaceGeometry>>();

      // Validate input multi face geometry data.
      for (const face_geometry::FaceGeometry& face_geometry :
           multi_face_geometry) {
        MP_RETURN_IF_ERROR(face_geometry::ValidateFaceGeometry(face_geometry))
            << "Invalid face geometry!";
      }

      MP_RETURN_IF_ERROR(effect_renderer_->RenderEffect(
          multi_face_geometry, input_gl_texture.width(),
          input_gl_texture.height(), input_gl_texture.target(),
          input_gl_texture.name(), output_gl_texture.target(),
          output_gl_texture.name()))
          << "Failed to render the effect!";

      std::unique_ptr<GpuBuffer> output_gpu_buffer =
          output_gl_texture.GetFrame<GpuBuffer>();

      cc->Outputs()
          .Tag(kImageGpuTag)
          .AddPacket(mediapipe::Adopt<GpuBuffer>(output_gpu_buffer.release())
                         .At(cc->InputTimestamp()));

      output_gl_texture.Release();
      input_gl_texture.Release();

      return absl::OkStatus();
    });
  }

  static absl::StatusOr<ImageFrame> ReadTextureFromFile(
      const std::string& texture_path) {
    ASSIGN_OR_RETURN(std::string texture_blob,
                     ReadContentBlobFromFile(texture_path),
                     _ << "Failed to read texture blob from file!");

    // Use OpenCV image decoding functionality to finish reading the texture.
    std::vector<char> texture_blob_vector(texture_blob.begin(),
                                          texture_blob.end());
    cv::Mat decoded_mat =
        cv::imdecode(texture_blob_vector, cv::IMREAD_UNCHANGED);

    RET_CHECK(decoded_mat.type() == CV_8UC3 || decoded_mat.type() == CV_8UC4)
        << "Texture must have `char` as the underlying type and "
           "must have either 3 or 4 channels!";

    ImageFormat::Format image_format = ImageFormat::UNKNOWN;
    cv::Mat output_mat;
    switch (decoded_mat.channels()) {
      case 3:
        image_format = ImageFormat::SRGB;
        cv::cvtColor(decoded_mat, output_mat, cv::COLOR_BGR2RGB);
        break;

      case 4:
        image_format = ImageFormat::SRGBA;
        cv::cvtColor(decoded_mat, output_mat, cv::COLOR_BGRA2RGBA);
        break;

      default:
        RET_CHECK_FAIL()
            << "Unexpected number of channels; expected 3 or 4, got "
            << decoded_mat.channels() << "!";
    }

    ImageFrame output_image_frame(image_format, output_mat.size().width,
                                  output_mat.size().height,
                                  ImageFrame::kGlDefaultAlignmentBoundary);

    output_mat.copyTo(formats::MatView(&output_image_frame));

    return output_image_frame;
  }

  static absl::StatusOr<face_geometry::Mesh3d> ReadMesh3dFromFile(
      const std::string& mesh_3d_path) {
    ASSIGN_OR_RETURN(std::string mesh_3d_blob,
                     ReadContentBlobFromFile(mesh_3d_path),
                     _ << "Failed to read mesh 3D blob from file!");

    face_geometry::Mesh3d mesh_3d;
    RET_CHECK(mesh_3d.ParseFromString(mesh_3d_blob))
        << "Failed to parse a mesh 3D proto from a binary blob!";

    return mesh_3d;
  }

  static absl::StatusOr<std::string> ReadContentBlobFromFile(
      const std::string& unresolved_path) {
    ASSIGN_OR_RETURN(std::string resolved_path,
                     mediapipe::PathToResourceAsFile(unresolved_path),
                     _ << "Failed to resolve path! Path = " << unresolved_path);

    std::string content_blob;
    MP_RETURN_IF_ERROR(
        mediapipe::GetResourceContents(resolved_path, &content_blob))
        << "Failed to read content blob! Resolved path = " << resolved_path;
    LOG(INFO) << "JEDI::MEDIAPIPE:: read file with path " << resolved_path
              << " successfully";

    return content_blob;
  }

  mediapipe::GlCalculatorHelper gpu_helper_;
  face_geometry::Environment environment_;
  std::unique_ptr<face_geometry::EffectRenderer> effect_renderer_;
  std::string current_texture_path = "";
  std::string current_mesh_3d_path = "";
  bool initialized = false;
};

}  // namespace

using CustomFaceGeometryEffectRendererCalculator =
    CustomEffectRendererCalculator;

REGISTER_CALCULATOR(CustomFaceGeometryEffectRendererCalculator);

}  // namespace mediapipe
```

**Comment by andrechen** [comment] 2022-09-12 08:43
well, maybe things are not that complicated. Like video games do, do just load/unload model/texture with respect to user input.  Much simpler than using a ugly **SwitchContainer** calculator.

A windows port of **face_effect** is [here](https://github.com/andrechen/mediapipe/tree/master/visualstudio/face_effect) to demonstrate it. Built by visual studio 2019/2022 makes it easier to debug and see what's really going on.
