### ISSUE TITLE
To build, for example, the C++ example app of the legacy MediaPipe Hand Detection solution with CPU. failed

### ISSUE THREAD

**Issue by shizhixiao** [google/mediapipe#4258] opened 2023-04-07 07:05 UTC
ERROR: /home/gc/mediapipe/mediapipe/framework/formats/BUILD:172:11: Compiling mediapipe/framework/formats/image_frame_opencv.cc failed: (Exit 1): gcc failed: error executing command (from target //mediapipe/framework/formats:image_frame_opencv) /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 57 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
In file included from ./mediapipe/framework/formats/image_frame_opencv.h:20,
                 from mediapipe/framework/formats/image_frame_opencv.cc:15:
./mediapipe/framework/port/opencv_core_inc.h:18:10: fatal error: opencv2/core/version.hpp: No such file or directory
   18 | #include <opencv2/core/version.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Target //mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 158.641s, Critical Path: 147.05s
INFO: 287 processes: 133 internal, 154 linux-sandbox.
FAILED: Build did NOT complete successfully

The error is as above, my gcc and g++ versions are both 11

Does anyone know what to do?

**Comment by shizhixiao** [comment] 2023-04-10 06:10
what should I do? Lower gcc version to 8.0?

**Comment by kuaashish** [comment] 2023-04-10 08:58
Hello @shizhixiao,
For macOS M1, You need to change the path to opencv since homebrew installs opencv on M1 at different locations. Two changes need to be done in [WORKSPACE.bazel](https://github.com/google/mediapipe/blob/master/WORKSPACE#L324) file. 

- In **macos_opencv** repository, Change path to point to your homebrew directory(if it includes opencv@3 inside homebew/opt directory).  Do not add **/opt/opencv@3** since it is included to be prefixed in //third_party:opencv_macos.BUILD already. 
- Also change the **ffmpeg** [path](https://github.com/google/mediapipe/blob/master/WORKSPACE#L333) to point to **/opt/homebrew/opt/ffmpeg**.
<img width="623" alt="Screenshot 2023-04-10 at 2 26 35 PM" src="https://user-images.githubusercontent.com/98159216/230869136-2b6ea8b8-151c-4130-b946-979d2edf53f4.png">

Please let us know if resolves the issue. Thank you

**Comment by shizhixiao** [comment] 2023-04-10 09:04
> Hello @shizhixiao, For macOS M1, You need to change the path to opencv since homebrew installs opencv on M1 at different locations. Two changes need to be done in [WORKSPACE.bazel](https://github.com/google/mediapipe/blob/master/WORKSPACE#L324) file.
> 
> * In **macos_opencv** repository, Change path to point to your homebrew directory(if it includes opencv@3 inside homebew/opt directory).  Do not add **/opt/opencv@3** since it is included to be prefixed in //third_party:opencv_macos.BUILD already.
> * Also change the **ffmpeg** [path](https://github.com/google/mediapipe/blob/master/WORKSPACE#L333) to point to **/opt/homebrew/opt/ffmpeg**.
> 
> <img alt="Screenshot 2023-04-10 at 2 26 35 PM" width="623" src="https://user-images.githubusercontent.com/98159216/230869136-2b6ea8b8-151c-4130-b946-979d2edf53f4.png">
> 
> Please let us know if resolves the issue. Thank you

I am using a Linux system under Ubuntu, what modifications do I need to make? Also the opencv version is 4.6.0, does this have any effect?

**Comment by kuaashish** [comment] 2023-04-10 09:18
@shizhixiao,
Please add following code snippet to the [linkopts](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD#L30) in opencv_linux.BUILD as mentioned below:

```
linkopts = [
        "-l/usr/local/lib",
        "-l:libopencv_core.so",
        "-l:libopencv_calib3d.so",
```
If above is still an issue then we suggest to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build.install_issue_template.yaml) to receive the complete steps followed, information to reproduce the issue from our end. Thank you

**Comment by shizhixiao** [comment] 2023-04-10 09:49
> 



> @shizhixiao, Please add following code snippet to the [linkopts](https://github.com/google/mediapipe/blob/master/third_party/opencv_linux.BUILD#L30) in opencv_linux.BUILD as mentioned below:
> 
> ```
> linkopts = [
>         "-l/usr/local/lib",
>         "-l:libopencv_core.so",
>         "-l:libopencv_calib3d.so",
> ```
> 
> If above is still an issue then we suggest to fill the [template](https://github.com/google/mediapipe/issues/new?assignees=&labels=type%3Abuild%2Finstall&template=build.install_issue_template.yaml) to receive the complete steps followed, information to reproduce the issue from our end. Thank you

https://github.com/google/mediapipe/issues/4267   filled the template here

**Comment by kuaashish** [comment] 2023-04-10 09:50
Closing this issue as Duplicate of #4267, Please follow up the another issue raised. Thank you

**Closed by kuaashish** 2023-04-10 09:50 UTC
Labels: type:build/install, MediaPipe, framework
