### ISSUE TITLE
Howto build a dynamic library of mediapipe for Linux x86_x64

### ISSUE THREAD

**Issue by THKDev** [google/mediapipe#2344] opened 2021-07-27 16:29 UTC
i'm aware of the issues #236, #144 and #294 . I tried to build a dynamic library but end up with a SIGSEGV.

I modified the mediapipe/mediapipe/examples/desktop/selfie_segmentation/BUILD . Added following 
```
cc_binary(
    name = "libmediapipe_selfie_segmentation_gpu.so",
    linkshared = 1,
    linkstatic = 1,
    data = [
        "//mediapipe/graphs/selfie_segmentation:selfie_segmentation_gpu.binarypb",
        "//mediapipe/modules/selfie_segmentation:selfie_segmentation.tflite",
    ],
    deps = [
        "//mediapipe/graphs/selfie_segmentation:selfie_segmentation_gpu_deps"
    ],
    srcs = [ "lib.cc" ]
)

cc_library(
    name = "libmediapipe_selfie_segmentation_gpu",
    srcs = [":libmediapipe_selfie_segmentation_gpu.so"],
    alwayslink = 1,
)
```
Then build the library by calling
```shell
bazel build --verbose_failures --strip=never --compilation_mode=dbg --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 mediapipe/examples/desktop/selfie_segmentation:libmediapipe_selfie_segmentation_gpu
```
Then linking a small program (empty main function only) against this dynamic library. Running this program results in a SIGSEGV.
```
libmediapipe_selfie_segmentation_gpu.so!google::protobuf::internal::AddDescriptors(const google::protobuf::internal::DescriptorTable * table) (/proc/self/cwd/external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2415)
ld-linux-x86-64.so.2!call_init(struct link_map * l, int argc, char ** argv, char ** env) (/usr/src/debug/glibc-2.32-8.fc33.x86_64/elf/dl-init.c:74)
ld-linux-x86-64.so.2!call_init(char ** env, char ** argv, int argc, struct link_map * l) (/usr/src/debug/glibc-2.32-8.fc33.x86_64/elf/dl-init.c:37)
ld-linux-x86-64.so.2!_dl_init(struct link_map * main_map, int argc, char ** argv, char ** env) (/usr/src/debug/glibc-2.32-8.fc33.x86_64/elf/dl-init.c:121)
ld-linux-x86-64.so.2!_dl_start_user (Unknown Source:0)
[Unknown/Just-In-Time compiled code] (Unknown Source:0)
```
generated_message_reflection.cc
```
void AddDescriptors(const DescriptorTable* table) {
  // AddDescriptors is not thread safe. Callers need to ensure calls are
  // properly serialized. This function is only called pre-main by global
  // descriptors and we can assume single threaded access or it's called
  // by AssignDescriptorImpl which uses a mutex to sequence calls.
  if (*table->is_initialized) return;
  *table->is_initialized = true;
  AddDescriptorsImpl(table);
}
```
Line 2415 is -> if (*table->is_initialized) return;

Seems that table is null. 

What has to be done to avoid the SIGSEGV and get a working library?

**Comment by sgowroji** [comment] 2021-08-18 07:57
@THKDev Duplicate of this https://github.com/google/mediapipe/issues/1162#issuecomment-897196714

**Comment by asprecic** [comment] 2022-05-05 15:54
Try my approach:
https://github.com/asprecic/mediapipe-qt-integration-example

**Closed** 2022-05-17 09:45 UTC
Labels: type:build/install, platform:desktop, stat:awaiting response, framework, stalled, solution:selfie segmentation
