### ISSUE TITLE
Error on example script provided in MediaPipe Hands - Uncaught (in promise) RuntimeError: Aborted(native code called abort())

### ISSUE THREAD

**Issue by sonmh79** [google/mediapipe#4062] opened 2023-02-05 07:21 UTC
Hello, I'm using Apple M1 and I found an error(`Uncaught (in promise) RuntimeError: Aborted(native code called abort())`) while testing example script written on Javascript in [docs](https://google.github.io/mediapipe/solutions/hands.html). 

**System information** (Please provide as much relevant information as possible)

- Have I written custom code (as opposed to using a stock example script provided in MediaPipe): X
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Apple M1(Ventura 13.2)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: X
- Browser and version (e.g. Google Chrome, Safari) if the issue happens on browser: Google Chrome (109.0.5414.119, arm64)
- Programming Language and version ( e.g. C++, Python, Java): Javascript
- [MediaPipe version](https://github.com/google/mediapipe/releases/tag/v0.9.1): Latest Version (released on Fabruary 1st, 2023)
- Bazel version (if compiling from source): X
- Solution ( e.g. FaceMesh, Pose, Holistic ): Hands
- Android Studio, NDK, SDK versions (if issue is related to building in Android environment): X
- Xcode & Tulsi version (if issue is related to building for iOS): X

**Describe the current behavior:**

`Uncaught (in promise) RuntimeError: Aborted(native code called abort())` on example script provided in MediaPipe.
Only input video is shown and not the result video for hand detection.
<img width="891" alt="스크린샷 2023-02-04 오후 10 45 28" src="https://user-images.githubusercontent.com/78152114/216806143-e4d2c437-5812-4c99-a846-99ceda623e93.png">

**Describe the expected behavior:**

Result video which is detecting my hands.

**Standalone code to reproduce the issue:**
-

**Other info / Complete Logs :**

It works good on Window.

**Comment by ayushgdev** [comment] 2023-02-06 11:15
Hello @sonmh79 
Thanks for filing your observation. However, we are not able to reproduce this issue at our end. Attached is a screenshot of the console from Chrome Dev tools. There are few warnings but no errors for `abort()` call. 

<img width="1728" alt="Screenshot 2023-02-06 at 4 40 19 PM" src="https://user-images.githubusercontent.com/118424249/216957222-08720a31-e3be-4dd0-be56-c75ff9c16c7f.png">
The system used to reproduce this issue is Macbook M1 Pro with Mac OS Ventura 13.2. The chrome version details are visible in screenshot below
<img width="719" alt="Screenshot 2023-02-06 at 4 39 42 PM" src="https://user-images.githubusercontent.com/118424249/216957446-ec8376a6-6e1d-4bf3-ab02-247d5d324133.png">

The code is identical to the example code given in the documentation. The `<script type="module">` tag was included at the end of the body (before `</body>`). Please let us know if we missed something in reproduction of the issue.

**Comment by Youngmook-Lim** [comment] 2023-02-06 16:51
Hi @ayushgdev,

We are pleased to inform you that we were able to fix this issue by including the version number in the return value for "locateFile" property, which is used to create a new Hands object. The code is as follows : 

const hands = new Hands({
        locateFile: (file) => {
          return `https://cdn.jsdelivr.net/npm/@mediapipe/hands@0.4/${file}`;
        },
});

We are not sure why this has solved the issue for us. Please let us know if you do. 

Thank you.

**Comment by sonmh79** [comment] 2023-02-06 16:58
Wow, It works well for me !! 

Thanks :) 

@Youngmook-Lim

**Comment by ayushgdev** [comment] 2023-02-07 08:25
@sonmh79 Glad to know the issue is resolved for you. However, it is peculiar the sample code isn't working for you, though without version specified explicitly simply means to pull the latest packages. This is something worth looking into at our end.

**Comment by ayushgdev** [comment] 2023-03-10 04:34
Closing this issue after internal discussion.

**Closed by ayushgdev** 2023-03-10 04:34 UTC
Labels: solution:hands, platform:javascript, type:bug
