### ISSUE TITLE
JS Pose not working on WebKit browsers after updating to 15.4

### ISSUE THREAD

**Issue by tarobodygram** [google/mediapipe#3262] opened 2022-04-14 07:20 UTC
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): iOS 15.4.1
- [MediaPipe version](https://github.com/google/mediapipe/releases): @0.5.1635988162
- Bazel version: -
- Solution (e.g. FaceMesh, Pose, Holistic): Pose
- Programming Language and version ( e.g. C++, Python, Java): JavaScript

Pose detection stops working after updating ios version to 15.4. I'm not sure what ios version I was using prior but I have verified that it works as usual on 14.7.1.

In the logs, it says it failed to load pose_detection.tflite but I don't see any xhr request for the model.

Any ideas where I should look at? Thanks

**Describe the expected behavior:**

`await pose.initialize()` should load `pose_detection.tflite` properly on WebKit browsers (ios15.4).

**Standalone code you may have used to try to get what you need :**

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook:

**Other info / Complete Logs :**
Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached:

<img width="1706" alt="Screen Shot 2022-04-13 at 11 58 08" src="https://user-images.githubusercontent.com/86764467/163333192-947ddf05-659e-46ca-bd15-189c6d415d57.png">

**Comment by jpamarohorta** [comment] 2022-04-21 16:14
Hello, I'm having the same issue. Any news or solutions? Thank you!

**Comment by hiukim** [comment] 2022-07-28 23:10
I also encountered this issue in iOS 15.4.  But interestingly, 15.5 seems fine....

**Comment by ayushgdev** [comment] 2022-12-14 09:27
Marking as a duplicate of #3874  and closing this issue. Please track for the resolution on #3874 .

**Closed** 2022-12-14 09:29 UTC
Labels: status:duplicate, type:support, platform:javascript, solution:pose
