### ISSUE TITLE
C++ compilation of rule '//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1)

### ISSUE THREAD

**Issue by nyanmn** [google/mediapipe#1673] opened 2021-02-28 06:16 UTC
I have this error building desktop version `pose tracking` for both cpu and gpu. 

The full errors build are

```
INFO: Found 1 target...
ERROR: /home/itc/mediapipe/mediapipe/calculators/tensor/BUILD:594:11: C++ compilation of rule '//mediapipe/calculators/tensor:image_to_tensor_converter_opencv' failed (Exit 1) gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 61 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~
Target //mediapipe/examples/desktop/pose_tracking:pose_tracking_cpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 513.380s, Critical Path: 506.91s
INFO: 606 processes: 606 linux-sandbox.
FAILED: Build did NOT complete successfully

```

I am building on Xavier (Jetson) with gcc/g++ version 

`g++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0`

How can I fix error?

**Comment by flyinskyin2013** [comment] 2021-03-08 09:01
Did you solve it?

**Comment by flyinskyin2013** [comment] 2021-03-09 05:59
> Did you solve it?

It's will be ok by using 'return absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>(std::move(tensor));' in place of 'return tensor;'

**Comment by sergweb** [comment] 2021-03-13 04:20
I modified 2 files **image_to_tensor_converter_opencv.cc** and **image_to_tensor_converter_gl_buffer.cc** in directory **mediapipe/calculator/tensor** by replacing code
`return tensor;`
by the following:
`return absl::StatusOr<mediapipe::Tensor> ( mediapipe::Tensor(std::move(tensor)) );`

**Comment by ramilmsh** [comment] 2021-03-29 07:20
@sergweb thank you for the solution, it worked for me. Could you make a PR for this?

**Comment by sgowroji** [comment] 2021-04-15 08:01
Hi @nyanmn, Is your issue resolved with above comments?. @sergweb we are glad to see your changes on the above issue. Thanks!

**Comment by sgowroji** [comment] 2021-04-21 07:25
Hi @nyanmn, Could you please respond to the above comment. Thanks!

**Comment by sgowroji** [comment] 2021-04-26 06:05
We are closing this ticket as of now, Due to lack of activity!

**Closed by sgowroji** 2021-04-26 06:05 UTC
Labels: platform:cpu, platform:gpu, solution:pose, stat:awaiting response, type:build/install

**Comment by AndreV84** [comment] 2021-04-28 15:59
I can observe the same issue trying to build on Jetson nano

**Comment by AndreV84** [comment] 2021-04-28 16:00
@sgowroji 
```
mediapipe/mediapipe/calculators/tensor/BUILD:594:11: Compiling mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 62 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc: In member function 'virtual absl::lts_2020_09_23::StatusOr<mediapipe::Tensor> mediapipe::{anonymous}::OpenCvProcessor::Convert(const mediapipe::Image&, const mediapipe::RotatedRect&, const mediapipe::Size&, float, float)':
mediapipe/calculators/tensor/image_to_tensor_converter_opencv.cc:106:12: error: could not convert 'tensor' from 'mediapipe::Tensor' to 'absl::lts_2020_09_23::StatusOr<mediapipe::Tensor>'
     return tensor;
            ^~~~~~

```

**Comment by sgowroji** [comment] 2021-04-29 06:58
Hi @AndreV84,  Thanks for letting us know. Could you share above mentioned configurations are same as yours. If both same then please provide the complete details like steps to reproduce to get the error. if not then raise another new issue with your details. Thanks

**Comment by AndreV84** [comment] 2021-04-29 08:17
1. the same configuration; the issue occurred exactly in the same way on the same setup, gcc 7.4; I saw more thread with that particular error message https://github.com/google/mediapipe/issues/1733 . E.g. it would occur on executing `bazel build -c opt --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 \ mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu` . 
2. Also changing in two files return tensor phrase passed to further steps
3. However, I yet can not confirm that it got resolved as I did not find a way how to run mediapipe solutions headless   - without display connected. Is it possible? at least for webcam examples? probably I will be able "run from file input- save to file outputs sample - for it I will creare an issue, while the former bug confirmation is well defind in the current thread - it occurs building mentioned examples https://github.com/google/mediapipe/issues/1950

**Comment by khanhnd0408** [comment] 2021-09-12 14:56
> examples

Hi, I'm trying to compile face mesh with GPU support. For "return tensor;", I'm replacing the code as you say, and this is perfect working but after that, the compiler through this error:

`Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> > mediapipe::CreateImageToGlBufferTensorConverter(mediapipe::CalculatorContext*, bool, mediapipe::BorderMode)':
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc:341:10: error: could not convert 'result' from 'std::unique_ptr<mediapipe::{anonymous}::GlProcessor, std::default_delete<mediapipe::{anonymous}::GlProcessor> >' to 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> >'
   return result;
          ^~~~~~
Target //mediapipe/examples/desktop/face_mesh:face_mesh_gpu failed to build
`

Could you help me out?

**Comment by khanhnd0408** [comment] 2021-09-12 14:57
@sergweb 
Hi, I'm trying to compile face mesh with GPU support. For "return tensor;", I'm replacing the code as you say, and this is perfect working but after that, the compiler through this error:

`Use --sandbox_debug to see verbose messages from the sandbox
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc: In function 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> > mediapipe::CreateImageToGlBufferTensorConverter(mediapipe::CalculatorContext*, bool, mediapipe::BorderMode)':
mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc:341:10: error: could not convert 'result' from 'std::unique_ptr<mediapipe::{anonymous}::GlProcessor, std::default_delete<mediapipe::{anonymous}::GlProcessor> >' to 'absl::lts_2020_09_23::StatusOr<std::unique_ptr<mediapipe::ImageToTensorConverter> >'
   return result;
          ^~~~~~
Target //mediapipe/examples/desktop/face_mesh:face_mesh_gpu failed to build
`

Could you help me out?

**Comment by sergweb** [comment] 2021-09-12 15:18
@khanhnd0408, let me check my code and get back to you.

**Comment by sergweb** [comment] 2021-09-12 15:58
@khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?
  
return std::unique_ptr<ImageToTensorConverter>(std::move(result));

**Comment by khanhnd0408** [comment] 2021-09-12 16:28
@sergweb 
No, from the master branch, it just "return result;" directly. I have tried your suggestion and its works. Thank you so much for your reply.

**Comment by DLGL99GL** [comment] 2021-09-21 07:59
> @khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?
> 
> `return std::unique_ptr<ImageToTensorConverter>(std::move(result));`
I modified 2 files image_to_tensor_converter_opencv.cc and image_to_tensor_converter_gl_buffer.cc. Code below
return tensor;
was replaced by
return absl::StatusOr<mediapipe::Tensor> ( mediapipe::Tensor(std::move(tensor)) );

**Comment by DLGL99GL** [comment] 2021-09-21 08:00
> @khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?
> 
> `return std::unique_ptr<ImageToTensorConverter>(std::move(result));`
@khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?

return std::unique_ptr<ImageToTensorConverter>(std::move(result));
I modified 2 files image_to_tensor_converter_opencv.cc and image_to_tensor_converter_gl_buffer.cc. Code below
return tensor;
was replaced by
return absl::StatusOrmediapipe::Tensor ( mediapipe::Tensor(std::move(tensor)) );

**Comment by DLGL99GL** [comment] 2021-09-21 08:20
> @khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?
> 
> `return std::unique_ptr<ImageToTensorConverter>(std::move(result));`

@khanhnd0408 , does your code in file mediapipe/calculators/tensor/image_to_tensor_converter_gl_buffer.cc, line 341 look like the following?

return std::unique_ptr<ImageToTensorConverter>(std::move(result));
I modified 2 files image_to_tensor_converter_opencv.cc and image_to_tensor_converter_gl_buffer.cc. Code below
return tensor;
was replaced by
return absl::StatusOrmediapipe::Tensor ( mediapipe::Tensor(std::move(tensor)) );

hi，After I made the above modifications, the above problems were solved; But there is also an error at compile time：
*****************************************************************************************************************
INFO: From Compiling org_tensorflow/tensorflow/lite/delegates/gpu/gl/api2.cc:
In file included from external/opencl_headers/CL/cl.h:32:0,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/api.h:42,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/api2.h:23,
                 from external/org_tensorflow/tensorflow/lite/delegates/gpu/gl/api2.cc:16:
external/opencl_headers/CL/cl_version.h:34:104: note: #pragma message: cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)
 #pragma message("cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 220 (OpenCL 2.2)")
                                                                                                        ^
ERROR: /home/test/Desktop/mediapipe/mediapipe/calculators/tensor/BUILD:81:11: C++ compilation of rule '//mediapipe/calculators/tensor:inference_calculator_gl' failed (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 146 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer '-std=c++0x' -MD -MF ... (remaining 146 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
*****************************************************************************************************************

Win10 + VMware(Ubuntu running Mediapipe)
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
bazel：3.7.2
 glxinfo | grep -i opengl：
OpenGL vendor string: VMware, Inc.
OpenGL renderer string: SVGA3D; build: RELEASE;  LLVM;
OpenGL core profile version string: 3.3 (Core Profile) Mesa 20.0.8
OpenGL core profile shading language version string: 3.30
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 3.3 (Compatibility Profile) Mesa 20.0.8
OpenGL shading language version string: 3.30
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 2.0 Mesa 20.0.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16
OpenGL ES profile extensions:

build and run is OK in CPU，but it not worked in GPU，Here are the instructions I used：
CPU（OK）：
bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu

GLOG_logtostderr=1 bazel-bin/mediapipe/examples/desktop/hand_tracking/hand_tracking_cpu \
  --calculator_graph_config_file=mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt

GPU（error）：
bazel build --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 --copt -DMEDIAPIPE_DISABLE_GL_COMPUTE \
mediapipe/examples/desktop/hand_tracking:hand_tracking_gpu

**Comment by sergweb** [comment] 2021-09-21 19:06
Here is my working code with all modifications I made on top of original mediapipe (in case you would like to compare): [drowsiness_detector](https://github.com/sergweb/mediapipe/tree/drowsiness_detector). Check [/_build_iris_tracking_gpu.sh](https://github.com/sergweb/mediapipe/blob/drowsiness_detector/_build_iris_tracking_gpu.sh) for compilation instruction.
