### ISSUE TITLE
Object box tracking in flutter

### ISSUE THREAD

**Issue by KingOfTNT10** [google/mediapipe#3981] opened 2023-01-10 06:17 UTC
Hi, i know many people have already asked for mediapipe support for flutter, but I really need just the box tracking... is there ANY way to do that in flutter?

**Comment by ayushgdev** [comment] 2023-01-10 08:55
Hi @KingOfTNT10 
Unfortunately we don't have any way to support flutter. We have informed the team of the increasing interest in flutter package, however, we don't have it on our roadmap as of now.

**Comment by ayushgdev** [comment] 2023-01-17 10:16
Marking as duplicate of #3922 . Closing this issue.

**Closed by ayushgdev** 2023-01-17 10:16 UTC
Labels: type:feature, MediaPipe, stat:awaiting response, type:others, stalled
