### ISSUE TITLE
Black screen on Samsung Galaxy S20+

### ISSUE THREAD

**Issue by PlugFox** [google/mediapipe#984] opened 2020-08-05 13:55 UTC
Try install mediapipe objectron 3d prebuild example on Android with ARM64 (Samsung Galaxy S20+).
But in each of the examples I get a black screen.

Objectron for Shoes
Android target: ([or download prebuilt ARM64 APK](https://drive.google.com/open?id=1S0K4hbWt3o31FfQ4QU3Rz7IHrvOUMx1d))

Objectron for Chairs
Android target: ([or download prebuilt ARM64 APK](https://drive.google.com/open?id=1MM8K-13bXLCVS1EHQ-KgkVyEahEPrKej))

This is also the behavior of Object Detection (CPU and GPU)

I tried to build step by step from sources - the result is the same.

![photo_2020-08-05_16-54-51](https://user-images.githubusercontent.com/7805176/89421276-7e962480-d73c-11ea-85ee-182982ffede8.jpg)

**Comment by PlugFox** [comment] 2020-08-05 14:30
Access to the camera granted

![image](https://user-images.githubusercontent.com/7805176/89425150-4f35e680-d741-11ea-9625-a053e404e872.png)
![image](https://user-images.githubusercontent.com/7805176/89425171-552bc780-d741-11ea-92dd-c331e178a48c.png)
![image](https://user-images.githubusercontent.com/7805176/89425176-578e2180-d741-11ea-834f-df58133c8c23.png)

**Comment by eknight7** [comment] 2020-08-06 04:44
1. Does switching the camera to the front camera work?
2. Do any of the other MediaPipe examples work?

**Comment by PlugFox** [comment] 2020-08-06 08:01
@eknight7 how can I switch camera in the example?
Try face detection GPU, same thing - black screen.

Sometimes the camera still displays the first frame (from the main camera), but that's about it.

In other (not mediapipe) applications this does not happen and everything works fine

**Comment by mcclanahoochie** [comment] 2020-08-07 17:16
can you provide the logs produced via adb?

**Comment by PlugFox** [comment] 2020-08-10 13:59
> can you provide the logs produced via adb?

`adb logcat -v threadtime >logcat.txt`
[logcat.txt](https://github.com/google/mediapipe/files/5051214/logcat.txt)

**Comment by mcclanahoochie** [comment] 2020-08-14 21:40
hmm, the log doesn't seem to have anything obvious wrong

a big update on gpu memory usage was recently made in [v0.7.9](https://github.com/google/mediapipe/blob/v0.7.9/) that reduces memory pressure quite a bit, can you try re-building with the latest version of mediapipe to see if it could be memory related?

**Comment by PlugFox** [comment] 2020-08-15 14:12
> hmm, the log doesn't seem to have anything obvious wrong
> 
> a big update on gpu memory usage was recently made in [v0.7.9](https://github.com/google/mediapipe/blob/v0.7.9/) that reduces memory pressure quite a bit, can you try re-building with the latest version of mediapipe to see if it could be memory related?

Ok, thank you.
On monday i will try to do it.

**Comment by Cubbee** [comment] 2020-09-08 07:40
Can confirm on S20+

Tried to build facedetectiongpu and handtrackinggpu v0.7.8, v0.7.9, v0.7.10 with same results - face detection outputs nothing, but black screen, and hand tracking crashes.

**Comment by Cubbee** [comment] 2020-09-09 07:40
I have no idea why, but a fix that I've tried for completely unrelated problem somehow fixes this issue

I've moved `TfLiteInferenceCalculator` onto a separate GL context like this:

Modify `mediapipe/gpu/gpu_shared_data_internal.cc`

  bool compute_context = node_type == "TfLiteInferenceCalculator";

  const auto& options = node->GetCalculatorState().Options<GlContextOptions>();
  if (options.has_gl_context_name() && !options.gl_context_name().empty()) {
    context_key = absl::StrCat("user:", options.gl_context_name());
  } else if (gets_own_context) {
    context_key = absl::StrCat("auto:", node_type);
  } else if (compute_context) {
    context_key = "user:compute_ctx";
  } else if (kGlCalculatorShareContext) {
    context_key = SharedContextKey();

**Comment by gittitov** [comment] 2020-09-17 02:39
> I have no idea why, but a fix that I've tried for completely unrelated problem somehow fixes this issue (tested on facedetectiongpu v0.7.10)
> 
> I've moved `TfLiteInferenceCalculator` into a separate GL context like this:
> 
> Modify `mediapipe/gpu/gpu_shared_data_internal.cc`
> `PrepareGpuNode`
> 
> ```
>   bool compute_context = node_type == "TfLiteInferenceCalculator";
> 
>   const auto& options = node->GetCalculatorState().Options<GlContextOptions>();
>   if (options.has_gl_context_name() && !options.gl_context_name().empty()) {
>     context_key = absl::StrCat("user:", options.gl_context_name());
>   } else if (gets_own_context) {
>     context_key = absl::StrCat("auto:", node_type);
>   } else if (compute_context) {
>     context_key = "user:compute_ctx";
>   } else if (kGlCalculatorShareContext) {
>     context_key = SharedContextKey();
> ```
Thank!
I have two Android devices. On first device with Rockchip + Android 9 - all mediapipe examples work for me. On the second device "vivo iQOO Z1 5G 6 GB 128 GB MediaTek 1000 Plus, Cortex-A77, Mali-G77MC9" + Android 10 only hello_world worked. In other cases, a black screen.
I checked your code on version v0.7.10 and on the latest. It works the same for me.

Face Detection - ok
Object detect - ok
Instant Motion Tracking - ok
hair - ok

Other examples don't work correctly. I am attaching a gif.
![git](https://user-images.githubusercontent.com/44014384/93413502-15abdb80-f8a8-11ea-9993-cd7aceb03ae5.gif)

**Comment by gittitov** [comment] 2020-09-20 04:34
I have partially localized the problem.

Conclusion: we have a conflict Mali-G77 + TfLiteInferenceCalculator + pose_landmark_upper_body.tflite
and also Mali-G77 + TfLiteInferenceCalculator + hand_landmark.tflite
(palm_detection.tflite and pose_detection.tflite - no problem)
I have not tested other examples.

I reconfigured the inference on the CPU and on the vivo iQOO Z1 - everything worked. (the phone is cold and everything works very quickly)

For those who want to run the BlazePose example on vivo iQOO Z1 with partial inference on the CPU (and probably on s20 and others with Mali-G77), you need to do
1.modify mediapipe / gpu / gpu_shared_data_internal.cc as described above.

2. pose_landmark_upper_body_by_roi_gpu.pbtxt

node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "transformed_pose_region"
  output_stream: "transformed_pose_region_2"
}

node { 
  calculator: "TfLiteConverterCalculator"
  input_stream: "IMAGE:transformed_pose_region_2"
  output_stream: "TENSORS:input_tensors"
  options: {
    [mediapipe.TfLiteConverterCalculatorOptions.ext] {
      zero_center: false
    }
  }
}

node { 
 calculator: "TfLiteInferenceCalculator"
 input_stream: "TENSORS:input_tensors"
  output_stream: "TENSORS:output_tensors"
  options: {
    [mediapipe.TfLiteInferenceCalculatorOptions.ext] {
      model_path: "mediapipe/modules/pose_landmark/pose_landmark_upper_body.tflite"
    }
  }
}


3. modules/pose_landmark/BUILD
mediapipe_simple_subgraph(
    name = "pose_landmark_upper_body_by_roi_gpu",
    graph = "pose_landmark_upper_body_by_roi_gpu.pbtxt",
    register_as = "PoseLandmarkUpperBodyByRoiGpu",
    deps = [
        "//mediapipe/calculators/core:gate_calculator",
        "//mediapipe/calculators/core:split_vector_calculator",
        "//mediapipe/calculators/image:image_cropping_calculator",
        "//mediapipe/calculators/image:image_transformation_calculator",
        "//mediapipe/calculators/tflite:tflite_converter_calculator",
        "//mediapipe/calculators/tflite:tflite_inference_calculator",
        "//mediapipe/calculators/tflite:tflite_tensors_to_floats_calculator",
        "//mediapipe/calculators/tflite:tflite_tensors_to_landmarks_calculator",
        "//mediapipe/calculators/util:landmark_letterbox_removal_calculator",
        "//mediapipe/calculators/util:landmark_projection_calculator",
        "//mediapipe/calculators/util:thresholding_calculator",
        "//mediapipe/gpu:gpu_buffer_to_image_frame_calculator",
    ],
)

P.S (There is still a small chance that the error is in TfLiteConverterCalculator, for example, these models are not centered around zero)

**Comment by Cubbee** [comment] 2020-11-15 13:40
Looks like the issue is fixed in 0.8.0 with new tensor inference calculator, as mentioned in https://github.com/google/mediapipe/issues/1218

I've rewritten my graphs to use new tensor-based calculators and they work on S20 and S20+!

**Comment by gittitov** [comment] 2020-11-18 00:36
they just removed all the inference from the GPU. Now everything is running on the CPU.
New calculators do not work on x64 because they require 4 channel images.

**Comment by gittitov** [comment] 2020-11-23 10:08
I checked. Works on vivo iQOO Z1 too.

**Comment by ROBYER1** [comment] 2020-12-04 10:14
Will the examples be updated with the fix? Just tried the shoes, cup and motion tracking examples all were black screen on my Xperia XZ3

**Comment by sgowroji** [comment] 2021-08-17 07:44
Hi All, Above issue fixes in the latest release. Please feel free to reopen if you encounter the same issue in the latest release.

**Closed by sgowroji** 2021-08-17 07:44 UTC
Labels: platform:android, android::camera
