### ISSUE TITLE
Error in Chrome on iOS

### ISSUE THREAD

**Issue by adrian-at-stink** [google/mediapipe#4835] opened 2023-09-26 14:13 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

iOS 17

### Mobile device if the issue happens on mobile device

iPhone 14

### Browser and version if the issue happens on browser

Chrome 117.0.5938.108

### Programming Language and version

Typescript/ React/Next

### MediaPipe version

0.10.5

### Solution

Face Detection

### Describe the actual behavior

Error: null is not an object (evaluating 't.alpha') when running .createFromOptions 

### Describe the expected behaviour

Face detection to work as expected, Safari works ok

### Standalone code/steps you may have used to try to get what you need

```shell
const FaceDetectorDefaults = {
  basePath: "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm",
  options: {
    baseOptions: {
      modelAssetPath:
        "https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite",
      delegate: "GPU",
    },
    runningMode: "VIDEO",
  } as FaceDetectorOptions,
};

Calling the Face Detector

return await FilesetResolver.forVisionTasks(basePath).then((vision) =>
      FaceDetectorImpl.createFromOptions(vision, options)
    );
```

### Other info / Complete Logs

If I go to https://codepen.io/mediapipe-preview/pen/OJByWQr on chrome on iOS this page does not let you try the code, as the screen is blocked and the Enable Webcam feature is disabled

The main example on the mediapipe site just has a loading spinner 

https://mediapipe-studio.webapps.google.com/studio/demo/face_detector

**Comment by artemjackson** [comment] 2023-10-09 19:06
The issue is caused by the weird `OffscreenCanvas` support in Safari: the `WebGL2RenderingContext.getContextAttributes()` returns `null` if the context is obtained from the `OffscreenCanvas` and an object if the context is obtained from the `HTMLCanvasElement`:

```js
// Safari
var c = document.createElement("canvas")
var gl = c.getContext("webgl2")

var oc = new OffscreenCanvas(1, 1)
var ogl = oc.getContext("webgl2")

console.log(gl && gl.getContextAttributes()) // { alpha: true, ... }
console.log(ogl && ogl.getContextAttributes()) // null
```

Chromium-based browsers, on the other hand, have consistent behavior:

```js
// Chromium
var c = document.createElement("canvas")
var gl = c.getContext("webgl2")

var oc = new OffscreenCanvas(1, 1)
var ogl = oc.getContext("webgl2")

console.log(gl && gl.getContextAttributes()) // { alpha: true, ... }
console.log(ogl && ogl.getContextAttributes()) // { alpha: true, ... }
```

**Comment by kuaashish** [comment] 2023-10-11 10:46
@adrian-at-stink,

I could able to successfully run the web demo https://mediapipe-studio.webapps.google.com/studio/demo/face_detector in `iOS 17`,` iPhone 14 Plus`, With `Chrome Browser Version 117.0.5938.117.` Could you please try to upgrade your Chrome Browser to specified one or newer and let us know if this is still an issue from your end. Thank you

**Comment by kuaashish** [comment] 2023-10-13 04:20
@adrian-at-stink,

Could you please go through the above and let us know if this works for you. Thank you

**Comment by adrian-at-stink** [comment] 2023-10-13 08:23
@kuaashish - apologies for the delay in replying

Trying with Chrome` 117.0.5938.117` and iOS 17.0.3 - the problem has been resolved. I have a feeling that it was resolved in the Apple update release

**Comment by kuaashish** [comment] 2023-10-13 09:13
@adrian-at-stink,

Thank you for your confirmation, Could you please let us know if this no longer issue from your end, Can we go ahead and mark this issue as resolved and close it?

**Comment by adrian-at-stink** [comment] 2023-10-13 10:09
@kuaashish - no longer an issue now with mentioned apple update. please close

**Closed** 2023-10-13 10:13 UTC
Labels: platform:ios, platform:javascript, type:bug, task:face detection
