### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by H1eu69** [google/mediapipe#4080] opened 2023-02-10 06:36 UTC
### OS Platform and Distribution

Ubuntu 20.04

### Programming Language and version

Java

### Bazel version

5.2.0

### Android SDK and NDK versions (if android)
33.0.2 and 21

### Android AAR (if android)

None

### Describe the problem

```shell
An Error happens when i try to build android example app using Bazel
```

### Complete Logs

```shell
ERROR: /home/hieuprovip/.cache/bazel/_bazel_hieuprovip/47fd8d65f25211cf425e15fb1585bb19/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/BUILD:3:13: Building external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/libdexer.jar (15 source files) and running annotation processors (AutoValueProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:20: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:16: error: package com.android.dx.cf.direct does not exist
import com.android.dx.cf.direct.DirectClassFile;
                               ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:17: error: package com.android.dx.cf.direct does not exist
import com.android.dx.cf.direct.StdAttributeFactory;
                               ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:18: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:19: error: package com.android.dx.dex does not exist
import com.android.dx.dex.DexOptions;
                         ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:20: error: package com.android.dx.dex.cf does not exist
import com.android.dx.dex.cf.CfOptions;
                            ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:21: error: package com.android.dx.dex.cf does not exist
import com.android.dx.dex.cf.CfTranslator;
                            ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:22: error: package com.android.dx.dex.code does not exist
import com.android.dx.dex.code.PositionList;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:23: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.ClassDefItem;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:24: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:25: error: package com.android.dx.util does not exist
import com.android.dx.util.ByteArray;
                          ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexBuilder.java:209: error: cannot find symbol
      DxContext context,
      ^
  symbol:   class DxContext
  location: class DexBuilder
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:187: error: cannot find symbol
  private final DxContext context;
                ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:188: error: cannot find symbol
  private final DexOptions dexOptions;
                ^
  symbol:   class DexOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:189: error: cannot find symbol
  private final CfOptions cfOptions;
                ^
  symbol:   class CfOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:195: error: cannot find symbol
  public Dexing(DxContext context, DexingOptions options) {
                ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
         ^
  symbol:   class DxContext
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
                            ^
  symbol:   class DexOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:200: error: cannot find symbol
  Dexing(DxContext context, DexOptions dexOptions, CfOptions cfOptions) {
                                                   ^
  symbol:   class CfOptions
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:206: error: cannot find symbol
  public static DirectClassFile parseClassFile(byte[] classfile, String classfilePath) {
                ^
  symbol:   class DirectClassFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:214: error: cannot find symbol
  public DexFile newDexFile() {
         ^
  symbol:   class DexFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
                                   ^
  symbol:   class DexFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
                                                 ^
  symbol:   class DirectClassFile
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:218: error: cannot find symbol
  public ClassDefItem addToDexFile(DexFile dest, DirectClassFile classFile) {
         ^
  symbol:   class ClassDefItem
  location: class Dexing
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:131: error: cannot find symbol
    public CfOptions toCfOptions(DxContext context) {
                                 ^
  symbol:   class DxContext
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:131: error: cannot find symbol
    public CfOptions toCfOptions(DxContext context) {
           ^
  symbol:   class CfOptions
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/Dexing.java:145: error: cannot find symbol
    public DexOptions toDexOptions() {
           ^
  symbol:   class DexOptions
  location: class DexingOptions
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexConverter.java:16: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexConverter.java:29: error: cannot find symbol
  public DexFile toDexFile(byte[] classfile, String classfilePath) {
         ^
  symbol:   class DexFile
  location: class DexConverter
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:19: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:20: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:21: error: package com.android.dx.merge does not exist
import com.android.dx.merge.CollisionPolicy;
                           ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:22: error: package com.android.dx.merge does not exist
import com.android.dx.merge.DexMerger;
                           ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:47: error: cannot find symbol
  private final ArrayList<Dex> currentShard = new ArrayList<>();
                          ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:51: error: cannot find symbol
  private final DxContext context;
                ^
  symbol:   class DxContext
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileArchive.java:18: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:16: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:17: error: package com.android.dex does not exist
import com.android.dex.FieldId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:18: error: package com.android.dex does not exist
import com.android.dex.MethodId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:19: error: package com.android.dex does not exist
import com.android.dex.ProtoId;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:20: error: package com.android.dex does not exist
import com.android.dex.TypeList;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:61: error: cannot find symbol
      DxContext context,
      ^
  symbol:   class DxContext
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:79: error: cannot find symbol
  public DexFileAggregator add(Dex dexFile) {
                               ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:131: error: cannot find symbol
  private void writeMergedFile(Dex... dexes) {
                               ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:144: error: cannot find symbol
  private Dex merge(Dex... dexes) throws IOException {
                    ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:144: error: cannot find symbol
  private Dex merge(Dex... dexes) throws IOException {
          ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:47: error: cannot find symbol
  public boolean track(Dex dexFile) {
                       ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:58: error: cannot find symbol
  private void trackFieldsAndMethods(Dex dexFile) {
                                     ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:69: error: cannot find symbol
  private static String typeName(Dex dex, int typeIndex) {
                                 ^
  symbol:   class Dex
  location: class DexLimitTracker
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:94: error: cannot find symbol
    static MethodDescriptor fromDex(Dex dex, int methodIndex) {
                                    ^
  symbol:   class Dex
  location: class MethodDescriptor
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexLimitTracker.java:75: error: cannot find symbol
    static FieldDescriptor fromDex(Dex dex, int fieldIndex) {
                                   ^
  symbol:   class Dex
  location: class FieldDescriptor
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileArchive.java:47: error: cannot find symbol
  public DexFileArchive addFile(ZipEntry entry, Dex dex) throws IOException {
                                                ^
  symbol:   class Dex
  location: class DexFileArchive
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:188: error: cannot find symbol
  private class RunDexMerger implements Callable<Dex> {
                                                 ^
  symbol:   class Dex
  location: class DexFileAggregator
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:190: error: cannot find symbol
    private final Dex[] dexes;
                  ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:192: error: cannot find symbol
    public RunDexMerger(Dex... dexes) {
                        ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:197: error: cannot find symbol
    public Dex call() throws IOException {
           ^
  symbol:   class Dex
  location: class DexFileAggregator.RunDexMerger
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:212: error: cannot find symbol
    private final ListenableFuture<Dex> dex;
                                   ^
  symbol:   class Dex
  location: class WriteFile
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileAggregator.java:216: error: cannot find symbol
    public WriteFile(String filename, ListenableFuture<Dex> dex, DexFileArchive dest) {
                                                       ^
  symbol:   class Dex
  location: class WriteFile
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:21: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:22: error: package com.android.dex does not exist
import com.android.dex.DexFormat;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:23: error: package com.android.dx.command.dexer does not exist
import com.android.dx.command.dexer.DxContext;
                                   ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:20: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:21: error: package com.android.dex does not exist
import com.android.dex.DexFormat;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:16: error: package com.android.dex does not exist
import com.android.dex.Dex;
                      ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:17: error: package com.android.dx.dex.file does not exist
import com.android.dx.dex.file.DexFile;
                              ^
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:28: error: cannot find symbol
  public static Dex toDex(DexFile dex) throws IOException {
                          ^
  symbol:   class DexFile
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:28: error: cannot find symbol
  public static Dex toDex(DexFile dex) throws IOException {
                ^
  symbol:   class Dex
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFiles.java:35: error: cannot find symbol
  static byte[] encode(DexFile dex) throws IOException {
                       ^
  symbol:   class DexFile
  location: class DexFiles
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileMerger.java:164: error: cannot find symbol
      defaultValue = "" + DexFormat.MAX_MEMBER_IDX,
                          ^
  symbol:   variable DexFormat
  location: class Options
external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/dexer/DexFileSplitter.java:112: error: cannot find symbol
      defaultValue = "" + DexFormat.MAX_MEMBER_IDX,
                          ^
  symbol:   variable DexFormat
  location: class Options
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 45.213s, Critical Path: 3.31s
INFO: 52 processes: 48 internal, 1 linux-sandbox, 3 worker.
FAILED: Build did NOT complete successfully
```

**Comment by ayushgdev** [comment] 2023-02-10 11:29
Hello @H1eu69 Can you please provide the detail on which MediaPipe solution are you trying to build?

**Comment by H1eu69** [comment] 2023-02-10 11:40
it's Hand tracking

> Hello @H1eu69 Can you please provide the detail on which MediaPipe solution are you trying to build?

**Comment by H1eu69** [comment] 2023-02-12 09:50
Update: It happens to all example not only Hands

**Comment by ayushgdev** [comment] 2023-02-13 06:18
@H1eu69 Since the issue is resolved, can you please close the issue if no further assistance is required?

**Closed** 2023-02-27 07:47 UTC
Labels: type:build/install, platform:android, stat:awaiting response, stalled
