### ISSUE TITLE
How to build a framework for iOS?

### ISSUE THREAD

**Issue by Cc-1993** [google/mediapipe#374] opened 2020-01-04 08:51 UTC
How to build a framework package that can be used on iOS, such as .Framework /.a, Is there any documentation like [this](https://github.com/google/mediapipe/blob/master/mediapipe/docs/android_archive_library.md) for android?

**Comment by Acimaz** [comment] 2020-01-06 16:05
I'm interested in this as well

**Comment by mgyong** [comment] 2020-01-06 16:33
Duplicate of #364

**Closed** 2020-07-08 02:25 UTC
Labels: ios
