### ISSUE TITLE
Tulsi for bazel is no longer maintained ,but I want to use tulsi for mediapipe ，i must use what number version of mediapipe ?

### ISSUE THREAD

**Issue by chensisi0730** [google/mediapipe#4734] opened 2023-08-30 03:08 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

ios

### Solution

gesture recognition

### Programming Language and version

oc

**Comment by kuaashish** [comment] 2023-08-30 07:35
@chensisi0730,

This matter is being resolved as a duplicate of the referenced issue #4732. We recommend directing your attention to another concurrently raised issue, while we proceed to close the current matter. Thank you

**Closed by kuaashish** 2023-08-30 07:35 UTC
Labels: type:support, platform:ios, task:gesture recognition
