### ISSUE TITLE
hand landmark to hand poses dataset available?

### ISSUE THREAD

**Issue by sofman98** [google/mediapipe#279] opened 2019-11-29 10:39 UTC
Hello I am currently looking for a dataset that would have the hand landmarks (the predicted 21 key points) as an input (data) and the hand poses (Yeah!, Rock'n'Roll!, Spread...etc) as the target.
I believe they used a machine learning model in order to classify the hand landmarks into hand poses but I couldn't find the dataset they have used (or any other similar dataset).
Thank you for your help.

**Comment by mgyong** [comment] 2019-12-05 18:24
Duplicate of #296

**Closed by mgyong** 2019-12-05 18:24 UTC

**Comment by mlizhardy** [comment] 2021-04-29 23:56
this is not a duplicate.  @sofman98 is asking for a dataset, #296 is asking for a model
