### ISSUE TITLE
Hand Tracking Multiple Hands

### ISSUE THREAD

**Issue by pranay-agra** [google/mediapipe#151] opened 2019-10-05 21:31 UTC
Hey,

In your blog, you released a hand-tracking model. In the blog, it mentioned scalability to multiple hands. How do you enable this on the software as it is currently only tracking one hand? I am not too well versed with Mediapipe / hand-tracking, so an in-depth explained answer would be perfect!

Thanks

**Comment by mgyong** [comment] 2019-10-06 00:39
Duplicate of #32 We don't support this currently

**Comment by mgyong** [comment] 2019-10-08 20:11
@eknight7 FYI
We will update this issue in the future once we have support

**Closed by mgyong** 2019-10-08 20:11 UTC
Labels: hands

**Comment by mgyong** [comment] 2019-11-15 23:21
@pranay-agra With the new release https://github.com/google/mediapipe/releases/tag/v0.6.4, we have multi-hand tracking examples:

https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_mobile_gpu.md
https://github.com/google/mediapipe/blob/master/mediapipe/docs/multi_hand_tracking_desktop.md
