### ISSUE TITLE
Support Tensorflow OpenCL on non-Android / non-ChromeOS platforms

### ISSUE THREAD

**Issue by csn1800** [google/mediapipe#3808] opened 2022-11-01 13:03 UTC
**System information** (Please provide as much relevant information as possible)
OS : Ubuntu 20.04
Device: Khadas Vim 3 (aarch64)
GPU: ARM Mali G52

- MediaPipe Solution (you are using): Holistic landmark detection (with OpenGL backend)
- Programming language : C++
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state:**
Currently Tensorflow OpenCL backend is not support on Mediapipe, as indicated in file mediapipe/util/tflite/tflite_gpu_runner.cc -> TFLiteGPURunner::InitializeOpenCL:
```
#else
  return mediapipe::UnimplementedError(
      "Currently only Android & ChromeOS are supported");
#endif  // defined(__ANDROID__) || defined(MEDIAPIPE_CHROMIUMOS)

```

**Will this change the current api? How?**
As per my understanding, current APIs need not be changed, rather should be supported on additional platforms
 
**Who will benefit with this feature?**
Non-Android (Ubuntu and other Linux variants, Windows) users will be benefitted largely, as Tensorflow-lite OpenCL delegate bring large performance improvements (inference latency improvements) in comparison with OpenGL delegates. 

**Please specify the use cases for this feature:**
Run holistic landmark detection on non-Android platforms

**Any Other info:**
None

**Comment by kuaashish** [comment] 2022-11-07 07:27
Duplicate of #3798

**Comment by kuaashish** [comment] 2022-11-08 07:53
Hi @csn1800,
Closing this issue as Duplicate of #3798 and following up with another issue raised. Thank you!

**Closed by kuaashish** 2022-11-08 07:53 UTC
Labels: status:duplicate, type:feature, solution:holistic, framework
