### ISSUE TITLE
Facedetector model documentation

### ISSUE THREAD

**Issue by yousifa** [google/mediapipe#1] opened 2019-06-23 19:45 UTC
I'm trying to use the facedetector model (facedetector_front.tflite) directly, but there is no documentation on the output of the model. A description of the output would be greatly appreciated.

**Comment by mgyong** [comment] 2019-06-24 00:14
@fanzhanggoogle Can you include the facedetector model input and output details into https://github.com/google/mediapipe/blob/master/mediapipe/docs/face_detection_android_gpu.md
and https://github.com/google/mediapipe/blob/master/mediapipe/models/README.md

**Comment by mgyong** [comment] 2019-06-27 20:52
@yousifa We don't recommend using the facedetector_front.tflite model directly without the preprocessing and postprocessing calculators that the [MediaPipe Android Face detection on GPU example](https://mediapipe.readthedocs.io/en/latest/face_detection_android_gpu.html) demonstrates.

To understand better the details of the facedetector_front.tflite model architecture, i recommend reading the [publication](https://sites.google.com/view/perception-cv4arvr/blazeface
) that the model is based on. You can also examine the code of the [TfLiteTensorsToDetections calculator](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/tflite/tflite_tensors_to_detections_calculator.cc) to better understand how to process the outputs of the facedetector_front.tflite model

**Comment by mgyong** [comment] 2019-07-02 16:19
Closing this issue since there hasn't been any follow up from @yousifa

**Closed by mgyong** 2019-07-02 16:19 UTC

**Comment by swagger2016** [comment] 2019-07-13 14:18
> I'm trying to use the facedetector model (facedetector_front.tflite) directly, but there is no documentation on the output of the model. A description of the output would be greatly appreciated.

I font this file has been removed, can you send me a copy, my email addr is : swaggerplusplus@outlook.com

**Comment by ogl4jo3** [comment] 2019-09-11 07:38
> I'm trying to use the facedetector model (facedetector_front.tflite) directly, but there is no documentation on the output of the model. A description of the output would be greatly appreciated.


I tried to inference BlazeFace model directly, and this is [python demo code](https://gist.github.com/ogl4jo3/5ba673b61ecc82780299edbcdcca301a). It is a simple demo. There are many shortcomings to be improved. 

- The post-processing spend a lot of time, I think it was caused by python code, maybe you can use [Numba](https://numba.pydata.org/) to optimize it. 
- And I use original NMS method instead paper's method. If you want better performance. You can implement [paper's method](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/non_max_suppression_calculator.cc).

**Comment by swagger2016** [comment] 2019-09-11 10:58
I tried the tflit file too. it only output the extracted feature. thanks for your demo. i will try it soon

发自我的 iPhone

**Comment by ValYouW** [comment] 2019-11-10 10:39
@ogl4jo3 Thank you for sharing. I did a small change to the script, instead of decoding all boxes and then filter results by score, first filter results and then decode only relevant boxes, on my laptop it reduced post-processing time from ~50ms to ~10ms
Here is the [gist](https://gist.github.com/ValYouW/07cb84b1ba0a803bf2766a383d5c1732)

**Comment by SigmaLGX** [comment] 2020-02-26 02:11
> > I'm trying to use the facedetector model (facedetector_front.tflite) directly, but there is no documentation on the output of the model. A description of the output would be greatly appreciated.
> 
> I tried to inference BlazeFace model directly, and this is [python demo code](https://gist.github.com/ogl4jo3/5ba673b61ecc82780299edbcdcca301a). It is a simple demo. There are many shortcomings to be improved.
> 
> * The post-processing spend a lot of time, I think it was caused by python code, maybe you can use [Numba](https://numba.pydata.org/) to optimize it.
> * And I use original NMS method instead paper's method. If you want better performance, you can implement [paper's method](https://github.com/google/mediapipe/blob/master/mediapipe/calculators/util/non_max_suppression_calculator.cc).

Thank you for sharing.  I run the  python demo code,but  get Wrong detection box.   I don't know where is the problem.
