### ISSUE TITLE
Inference time decreasing after a certain delay using GPUBuffer packets running in GL Context

### ISSUE THREAD

**Issue by ABazL** [google/mediapipe#5111] opened 2024-01-31 16:10 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Android 13

### MediaPipe version

0.8.10

### Bazel version

5.2.0

### Solution

Pose

### Describe the actual behavior

ddddddddddddddddddddddddddddddddddddddddddddddddd

**Comment by kuaashish** [comment] 2024-02-01 06:21
Closing this as a duplicate of issue https://github.com/google/mediapipe/issues/5113. Kindly refer to the latest issue for further updates.

**Closed by kuaashish** 2024-02-01 06:21 UTC
Labels: status:duplicate, type:support
