### ISSUE TITLE
help with using mediapipe to detect keystrokes from a webcam

### ISSUE THREAD

**Issue by HeavenComet** [google/mediapipe#5019] opened 2023-12-11 01:58 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Kali linux / google colab

### Task name (e.g. Image classification, Gesture recognition etc.)

hand landmark detection

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

kinda works but data isn't clean enough for what is needed

### Describe the expected behaviour

is very clean cut and gives the exact frame the keystroke is pressed

### Standalone code/steps you may have used to try to get what you need

```shell
!pip install pytube
!pip install mediapipe opencv-python
import os
from pytube import YouTube
from IPython.display import YouTubeVideo
import mediapipe as mp
import cv2

def download_video(video_url, output_dir):
    yt = YouTube(video_url)
    video_stream = yt.streams.get_highest_resolution()
    original_filename = video_stream.title
    video_stream.download(output_path=output_dir, filename=original_filename)
    return os.path.join(output_dir, f"{original_filename}.mp4")

def determine_keystrokes(hand_landmarks, amount):
    if hand_landmarks:
      #return hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_TIP].y
        if hand_landmarks.landmark[mp_hands.HandLandmark.MIDDLE_FINGER_TIP].y > amount: #replace that with amount in a minute
            return 'W'
        #if hand_landmarks.landmark[mp_hands.HandLandmark.INDEX_FINGER_TIP].y > 0.7614:
    return 'None'


def crop_handcam(frame):
    x, y, width, height = 100, 100, 200, 200
    cropped_frame = frame[y:y + height, x:x + width]
    return cropped_frame


def map_to_tensor(video_id, frame_id, keystrokes):
    return {
        "video_id": video_id,
        "frame_id": frame_id,
        "keystrokes": keystrokes,
    }


mp_hands = mp.solutions.hands
hands = mp_hands.Hands()

training_data_videos = [
    "https://youtube.com/shorts/_QDte-cXaMs?feature=share",
    "https://www.youtube.com/shorts/xNJlBWk5iN4",
    "https://www.youtube.com/watch?v=b97wWi6tw6k",
    ""
]

data_dir = 'data'
if not os.path.exists(data_dir):
    os.makedirs(data_dir)



for video_id, video_url in enumerate(training_data_videos):
    video_path = download_video(video_url, data_dir)
    print(video_id)
    video_path = os.path.join(data_dir, "November 10, 2023")
    video_capture = cv2.VideoCapture(video_path)
    print(video_capture)
    total_frames = int(video_capture.get(cv2.CAP_PROP_FRAME_COUNT))
    print(f"the total amount of frames in this video is {total_frames}")
    if video_id == 0:
      amount = 0.79
    if video_id == 1:
      amount = 0.52
    if video_id == 2:
      amount = 0.7614
    for frame_id in range(total_frames):

      ret, frame = video_capture.read()
      if not ret:
          break
        #cropped_frame = crop_handcam(frame)

      
      rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB) #instead of frame put cropped frame once project furthers
      results = hands.process(rgb_frame)

      
      hand_landmarks = results.multi_hand_landmarks[0] if results.multi_hand_landmarks else None
      detected_keystrokes = determine_keystrokes(hand_landmarks, amount)

        
      tensor_data = map_to_tensor(video_id, frame_id, detected_keystrokes)
      if frame_id % 30 == 0:
        print(f"second {frame_id/30:.0f}" )
     
      print(tensor_data)

    video_capture.release()

hands.close()```
```

### Other info / Complete Logs

```shell
im creating an AI that plays minecraft from start to finish as fast as possible and im using training data to get the AI a little head start. i have some test data with a camera over the players hand that shows the keyboard (and mouse but thats not relevant at the moment) and im trying to figure out a way to get keystrokes out of the videos using mediapipe by looking at the y level of the middle finger. ive had some success but the keystrokes outputted are very messy and might mess up the training of the AI. as of now im only tracking the middle finger which will be attributed to the w key (in the future it will be all the fingers and the mouse). thank you for any help and i dont use github much so if i posted this in the wrong place or i shouldve given more information please tell me. thank you again
```

**Comment by kuaashish** [comment] 2023-12-11 10:03
Hi @HeavenComet,

The task named "fingertip placement" is not currently listed in our documentation. Our documentation only includes the available tasks. Kindly refer to the [documentation](https://developers.google.com/mediapipe/solutions/guide) for more information. If you are obtaining information from sources or repositories other than MediaPipe documentation, it is advisable to raise an issue on the relevant forum or repository. Taking this step will help initiate the necessary support or resolution process, and it's recommended to follow up with them for further assistance.

Thank you

**Comment by HeavenComet** [comment] 2023-12-11 11:43
sorry about that, i dont use github much. ill fix the question.

**Comment by kuaashish** [comment] 2023-12-12 09:40
Hi @HeavenComet,

The code snippets you shared include a legacy MediaPipe hand solution implementation that we no longer support or maintain. You can find details about this in our [guide](https://developers.google.com/mediapipe/solutions/guide#available_solutions). Currently, we lack the appropriate contact person to address this issue, and unfortunately, we are unable to provide support for Legacy Solutions.

We recommend replacing the code related to the legacy hand implementation with the new Hand Landmarker Task API. You can find a Python code example [here](https://developers.google.com/mediapipe/solutions/vision/hand_landmarker/python) if it is possible from your end. Additionally, if you can provide the webpage or documentation you are using for your implementation, we can guide you to the right forum or repository where you may receive better support for the issues you are facing.

Thank you

**Comment by HeavenComet** [comment] 2023-12-12 12:13
Sorry and thank you @kuaashish for your consistent and well thought out responses, I will reimplement the old legacy mediapipe with the hand landmark API, should probably work better. as for the webpage documentation that i used, im pretty sure (but not positive) that its this: https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/python. thank you again for your help and have a great day

**Comment by kuaashish** [comment] 2023-12-14 05:49
Hi @HeavenComet,

Could you please confirm if now the issue is no longer present on your end? If so, may we proceed to close this matter and update the status? Should you require further assistance, feel free to initiate a new issue with complete details.

Thank you

**Comment by HeavenComet** [comment] 2023-12-16 18:50
yeah i should be good, ill try to convert it to API code but im not that good at coding so if i cant figure it out ill ask for help. thank you again for your patience, support and understanding.

**Closed** 2023-12-16 18:54 UTC
Labels: platform:python, type:others
