### ISSUE TITLE
building apps or aar at android platform failed

### ISSUE THREAD

**Issue by BTLDXX-x** [google/mediapipe#4306] opened 2023-04-19 17:06 UTC
### OS Platform and Distribution

android

### Programming Language and version

java

### MediaPipe version

0.9.3

### Bazel version

5.2.0

### Android SDK and NDK versions (if android)

sdk: 30.0.3. ndk:21

### Android AAR (if android)

Yes

### Describe the problem

```shell
1. follow the documentation(https://developers.google.com/mediapipe/framework/getting_started/android)
2. run the command:
bazel build -c opt --config=android_arm64 mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu
3. run the command:
bazel build -c opt --strip=ALWAYS \
--host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
--fat_apk_cpu=arm64-v8a,armeabi-v7a \
--legacy_whole_archive=0 \
--features=-legacy_whole_archive \
--copt=-fvisibility=hidden \
--copt=-ffunction-sections \
--copt=-fdata-sections \
--copt=-fstack-protector \
--copt=-Oz \
--copt=-fomit-frame-pointer \
--copt=-DABSL_MIN_LOG_LEVEL=2 \
--linkopt=-Wl,--gc-sections,--strip-all \
//mediapipe/examples/android/src/java/com/google/mediapipe/apps/face_effect_aar:mediapipe_face_effect.aar



i can successfully built 2 and 3 with v0.9.2, but failed with v0.9.3.
i want to use the calculator of landmark smoothing filter and face geometry. i saw the v0.9.3 add the face geometry that couldn't be found when i built the face_effect aar before. so i try to use v0.9.3, but met problems.
```

### Complete Logs

```shell
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'flatbuffers' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_googlesource_code_re2' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'zlib' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'rules_python' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'pybind11_protobuf' because it already exists.
DEBUG: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/org_tensorflow/third_party/repo.bzl:132:14: 
Warning: skipping import of repository 'com_github_glog_glog' because it already exists.
WARNING: /Users/apple/MPProject/mediapipe/mediapipe/framework/tool/BUILD:197:24: in cc_library rule //mediapipe/framework/tool:field_data_cc_proto: target '//mediapipe/framework/tool:field_data_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
WARNING: /Users/apple/MPProject/mediapipe/mediapipe/framework/BUILD:54:24: in cc_library rule //mediapipe/framework:calculator_cc_proto: target '//mediapipe/framework:calculator_cc_proto' depends on deprecated target '@com_google_protobuf//:cc_wkt_protos': Only for backward compatibility. Do not use.
INFO: Repository android_gmaven_r8 instantiated at:
  /DEFAULT.WORKSPACE.SUFFIX:460:6: in <toplevel>
  /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/bazel_tools/tools/build_defs/repo/utils.bzl:233:18: in maybe
Repository rule http_jar defined at:
  /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/bazel_tools/tools/build_defs/repo/http.bzl:530:27: in <toplevel>
WARNING: Download from https://maven.google.com/com/android/tools/r8/3.3.28/r8-3.3.28.jar failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'android_gmaven_r8':
   Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/bazel_tools/tools/build_defs/repo/http.bzl", line 211, column 33, in _http_jar_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [https://maven.google.com/com/android/tools/r8/3.3.28/r8-3.3.28.jar] to /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/android_gmaven_r8/jar/downloaded.jar: connect timed out
ERROR: /DEFAULT.WORKSPACE.SUFFIX:460:6: fetching http_jar rule //external:android_gmaven_r8: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/bazel_tools/tools/build_defs/repo/http.bzl", line 211, column 33, in _http_jar_impl
		download_info = ctx.download(
Error in download: java.io.IOException: Error downloading [https://maven.google.com/com/android/tools/r8/3.3.28/r8-3.3.28.jar] to /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/android_gmaven_r8/jar/downloaded.jar: connect timed out
INFO: Repository android_opencv instantiated at:
  /Users/apple/MPProject/mediapipe/WORKSPACE:358:13: in <toplevel>
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/androidsdk/BUILD.bazel:13:25: @androidsdk//:d8_jar_import depends on @android_gmaven_r8//jar:jar in repository @android_gmaven_r8 which failed to fetch. no such package '@android_gmaven_r8//jar': java.io.IOException: Error downloading [https://maven.google.com/com/android/tools/r8/3.3.28/r8-3.3.28.jar] to /private/var/tmp/_bazel_apple/8bcb6d1f4c989e1d81eae00d06962091/external/android_gmaven_r8/jar/downloaded.jar: connect timed out
ERROR: Analysis of target '//mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu' failed; build aborted: 
INFO: Elapsed time: 58.498s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (26 packages loaded, 9898 targets \
configured)
    Fetching https://github.com/...3-android-sdk.zip; 3.2 MiB (3,349,938B) 53s
```

**Comment by kuaashish** [comment] 2023-06-08 08:54
@BTLDXX-x,

Closing this issue as Duplicate of #4393. Please follow up with #4393 as Issue has been already assigned to correct owner and we are waiting for the input.

**Closed by kuaashish** 2023-06-08 08:54 UTC
Labels: type:build/install, platform:android, solution:hands, android::aar
