### ISSUE TITLE
ImportError after build from souce

### ISSUE THREAD

**Issue by RitchieQi** [google/mediapipe#2461] opened 2021-08-25 16:59 UTC
- OS Platform and Distribution:Linux Ubuntu 16.04
- Compiler version: gcc/g++ 9.4.0 
- Programming Language and version: Python3.5
- [MediaPipe version](https://github.com/google/mediapipe/releases): 0.8.7
- Bazel version: 4.2.0

Installed opencv by executing setup_opencv.sh and build from source of master branch
When executing _sudo python3 setup.py install --link-opencv_, there're some syntax error:
![image](https://user-images.githubusercontent.com/54255182/130833274-ec8eab0e-cb78-4ab1-ae45-a7d0b946da5e.png)
When import mediapipe in python, there's another issue:
![image](https://user-images.githubusercontent.com/54255182/130833391-73493a8d-6289-45f1-a5c9-b9acd148694d.png)

Any solution regarding this? Thanks in advance!

**Comment by RitchieQi** [comment] 2021-08-30 11:05
Hi guys, I have tried both with and without '--link-opencv' in ver 0.8,6
this error occured in both situation.
![image](https://user-images.githubusercontent.com/54255182/131329814-772ef807-7971-4daf-935c-cb96201b2d87.png)

However I was considering to migrate to 18.04 or even 20.04.

**Comment by RitchieQi** [comment] 2021-08-30 13:18
Okay I upgrade to gcc/g++9 again, and execute setup_opencv.sh and python3 setup.py install --link-opencv. here's an error:
![image](https://user-images.githubusercontent.com/54255182/131345193-c2913ef2-39b6-44d3-b968-7b1d6c42f039.png)
looks like another gcc related problem

**Comment by jiuqiant** [comment] 2021-08-30 17:28
The "-lavresample" flag is related to the ffmpeg library. Have you installed it?

Or you can edit https://github.com/google/mediapipe/blob/master/mediapipe/python/BUILD like the following to only keep the must-have opencv components:

```
diff --git a/mediapipe/python/BUILD b/mediapipe/python/BUILD
index 42ce07f6..64f8af12 100644
--- a/mediapipe/python/BUILD
+++ b/mediapipe/python/BUILD
@@ -24,11 +24,6 @@ pybind_extension(
         "//conditions:default": [
             "-lopencv_core",
             "-lopencv_imgproc",
-            "-lopencv_highgui",
-            "-lopencv_video",
-            "-lopencv_features2d",
-            "-lopencv_calib3d",
-            "-lopencv_imgcodecs",
         ],
     }),
     deps = [
```

This will not require ffmpeg (for video processing) anymore.

**Comment by RitchieQi** [comment] 2021-08-31 10:37
I have removed and reinstalled ffmpeg, here's what I got:
![image](https://user-images.githubusercontent.com/54255182/131488146-ff23abf6-b06c-441d-8d38-fa12ec1d7587.png)

**Comment by jiuqiant** [comment] 2021-08-31 16:12
This error means the python protos were not properly generated and the setup program found nothing to delete at the cleanup step.  Please run `python3 setup.py gen_protos && python3 setup.py install --link-opencv` together.

**Comment by RitchieQi** [comment] 2021-09-01 13:46
After reinstalling by following your instruction, here's still a syntax error.
![image](https://user-images.githubusercontent.com/54255182/131682250-2be976ab-b7c3-45a3-9720-f7e7ccff5315.png)
And I have made my mind and started working on 18.04 and 20.04, mediapipe works fine on both of them. Here's no need for further support. I appreciate your time and patience.

**Comment by jiuqiant** [comment] 2021-09-01 17:23
Regrading the syntax error, this is caused by the unsupported type annotation in python 3.5: https://stackoverflow.com/questions/51789120/type-hints-syntax-error-on-python-3-5.

Close this for now since the issue is solved.

**Closed by jiuqiant** 2021-09-01 17:23 UTC
Labels: type:build/install, stat:awaiting response, platform:python
