### ISSUE TITLE
How do I use mediapipe in iOS

### ISSUE THREAD

**Issue by Cc-1993** [google/mediapipe#365] opened 2020-01-02 03:36 UTC
I tried to run mediapipe on my iPhone and had already generated the xcode project through tulsi, but it ran wrong: "/ Users/xxx/Desktop/ERROR: / Users/xxx mediapipe/mediapipe/examples/ios/handtrackinggpu/BUILD: land: ProcessEntitlementsFiles mediapipe/examples/ios/handtrackinggpu/HandTrackingGpuApp_entitlements entitlements failed (1) Exit plisttool failed: Error executing the command "and"/Users/xxx/Desktop/Mediapipe xcodeproj/for/Scripts/bazel_build py: 549: Bazel build failed with exit code 1. Both Please check the build log Report in the Navigator (⌘ 9) for more information. "and I tried many ways couldn't find a solution. My ultimate goal is to integrate the "handtrack" module into my video project. Even if I run the mediapipe demo, how can I split the module? What files does it depend on? Please help me.

**Comment by vineet15889** [comment] 2020-01-02 18:38
@Cc-1993 The basic document you can find here --> https://mediapipe.readthedocs.io/en/latest/
For hand tracking you should care about following things..

**APIs for MediaPipe**

- Calculator API in C++
- Graph Construction API in ProtoBuf
- (Coming Soon) Graph Construction API in C++
- Graph Execution API in C++
- Graph Execution API in Java (Android)
- Graph Execution API in Objective-C (iOS)

*if you just want to build for demo purpose you can replace bundleid and provisioning profile and it works. you can find  instructions here -> https://github.com/google/mediapipe/blob/master/mediapipe/docs/mediapipe_ios_setup.md

**Comment by Cc-1993** [comment] 2020-01-03 08:47
Vineet15889 thanks for your reply. I have read the documents in detail again and can run the xcode project on my iPhone. Now I want to port this function module into my project. What are the necessary operations? Can you help me? thank you

**Comment by mgyong** [comment] 2020-01-06 16:35
Duplicate of #364

**Comment by mapleyuan** [comment] 2020-01-07 02:48
@Cc-1993  have u solved it? I have a same problem.

**Comment by Cc-1993** [comment] 2020-01-07 03:11
> @ Cc-1993 你解决了吗？我有同样的问题。

Not yet！

**Closed** 2020-02-11 20:28 UTC
Labels: ios
