### ISSUE TITLE
'FieldDescriptor' object has no attribute '_default_constructor' when using create_from_optioons

### ISSUE THREAD

**Issue by weuceda14** [google/mediapipe#5254] opened 2024-03-23 00:22 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

Yes

### OS Platform and Distribution

Mac OS ventura 13.0

### Task name (e.g. Image classification, Gesture recognition etc.)

Pose Landmark Detection

### Programming Language and version (e.g. C++, Python, Java)

C++

### Describe the actual behavior

Program stops when calling create from options

### Describe the expected behaviour

simple live stream tracking

### Standalone code/steps you may have used to try to get what you need

```shell
#The following is the code im using 

import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
import cv2 as cv

BaseOptions = mp.tasks.BaseOptions
PoseLandmarker = mp.tasks.vision.PoseLandmarker
PoseLandmarkerOptions = mp.tasks.vision.PoseLandmarkerOptions
PoseLandmarkerResult = mp.tasks.vision.PoseLandmarkerResult
VisionRunningMode = mp.tasks.vision.RunningMode

model_path = 'pose_landmarker_full.task'

cap = cv.VideoCapture(0)

if not cap.isOpened():
    print("Error: Failed to open camera.")
    exit()



# Create a pose landmarker instance with the live stream mode:
def print_result(result: PoseLandmarkerResult, output_image: mp.Image, timestamp_ms: int):
    print('pose landmarker result: {}'.format(result))

options = PoseLandmarkerOptions(
    base_options=BaseOptions(model_asset_path=model_path),
    running_mode=VisionRunningMode.LIVE_STREAM,
    result_callback=print_result)

##THE ERROR IS RIGHT HERE WHY IS IT NOT WORKING?
with PoseLandmarker.create_from_options(options) as landmarker:
 
    while cap.isOpened():


        # Get the current timestamp in ticks
        ticks = cv.getTickCount()

# Get the tick frequency (ticks per second)
        tick_frequency = cv.getTickFrequency()

# Calculate the timestamp in milliseconds
        timestamp_ms = (ticks / tick_frequency) * 1000    


    # Read a frame from the camera
        ret, frame = cap.read()
    # Check if the frame was captured successfully
        if not ret:
            print("Error: Failed to capture frame.")
            break

        # Use OpenCV’s VideoCapture to start capturing from the webcam.

        # Create a loop to read the latest frame from the camera using VideoCapture#read()

        # Convert the frame received from OpenCV to a MediaPipe’s Image object.
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=frame)


        # Send live image data to perform pose landmarking.
        # The results are accessible via the `result_callback` provided in
        # the `PoseLandmarkerOptions` object.
        # The pose landmarker must be created with the live stream mode.
        landmarker.detect_async(mp_image, timestamp_ms)
    


    # Display the captured frame in a window
        cv.imshow('Frame', frame)






    # Check for the 'q' key to exit the loop
        if cv.waitKey(1) & 0xFF == ord('q'):
            break


cap.release()
cv.destroyAllWindows()


What could the potential issue be? I tried installing media pipe 10.9 and changing my python version but im not sure if I did it correctly
```

**Comment by hanphps** [comment] 2024-03-24 02:48
Saw same error further debugging from my end:

**OS Platform and Distribution**

Mac OS Sanoma 14.4

**MediaPipe Tasks SDK version**

No response

**Task name (e.g. Image classification, Gesture recognition etc.)**

Pose Landmark Detection

**Programming Language and version (e.g. C++, Python, Java)**

Python

**Describe the actual behavior**

Program stops when calling create from options

**Describe the expected behaviour**

simple image checking

**Standalone code/steps you may have used to try to get what you need**

See PDF 
[Debug.pdf](https://github.com/google/mediapipe/files/14734209/Debug.pdf)

**Comment by hanphps** [comment] 2024-03-24 03:01
As you can see the copy from task_options_proto in task_info.py is a table:
 CalcOptions
```
base_options {
  model_asset {
    file_name: "/Users/hannah/Documents/bikepose/model_full/pose_landmarker_full.task"
  }
  use_stream_mode: false
}
pose_detector_graph_options {
  min_detection_confidence: 0.5
  num_poses: 1
}
pose_landmarks_detector_graph_options {
  min_detection_confidence: 0.5
}
min_tracking_confidence: 0.5
```
Iterating over each seems fine and copies correctly?

When we try to copy from to node
```
[mediapipe.tasks.vision.pose_landmarker.proto.PoseLandmarkerGraphOptions.ext] {
  base_options {
    model_asset {
      file_name: "/Users/hannah/Documents/bikepose/model_full/pose_landmarker_full.task"
    }
    use_stream_mode: false
  }
  pose_detector_graph_options {
    min_detection_confidence: 0.5
    num_poses: 1
  }
  pose_landmarks_detector_graph_options {
    min_detection_confidence: 0.5
  }
  min_tracking_confidence: 0.5
}
```

It results in trying to create buffer as such:
`{'_options': None, '_options_class_name': 'FieldOptions', '_serialized_options': None, 'has_options': False, 'name': 'ext', 'full_name': 'mediapipe.tasks.vision.pose_landmarker.proto.PoseLandmarkerGraphOptions.ext', 'file': <google.protobuf.descriptor.FileDescriptor object at 0x132763c50>, '_camelcase_name': None, 'json_name': 'ext', 'index': 0, 'number': 516587230, 'type': 11, 'cpp_type': 10, 'label': 1, 'has_default_value': False, 'default_value': None, 'containing_type': <google.protobuf.descriptor.Descriptor object at 0x12bfc9410>, 'message_type': <google.protobuf.descriptor.Descriptor object at 0x1327780d0>, 'enum_type': None, 'is_extension': True, 'extension_scope': <google.protobuf.descriptor.Descriptor object at 0x1327780d0>, 'containing_oneof': None, '_cdescriptor': None}
`
Seems to be issue with calculator_options_pb2.CalculatorOptions @kuaashish

**Comment by hanphps** [comment] 2024-03-25 16:47
Update:
Can run in Google Colab

Maybe a Mac related issue?

My Mac is Intel based chip

**Comment by kuaashish** [comment] 2024-03-26 06:44
Hi @hanphps,

This issue for now looks like a Mac related issue and known to us. We suggest you to please follow up already raised issue #5188 for further update as we are already tracking issue and closing this issue now. 

Thank you!!

**Closed by kuaashish** 2024-03-26 06:44 UTC
Labels: status:duplicate, platform:python, type:bug, task:pose landmarker, os:macOS
