### ISSUE TITLE
How to setup SDK and NDK path when running on Linux subsytem

### ISSUE THREAD

**Issue by j-vent** [google/mediapipe#809] opened 2020-06-16 18:06 UTC
Hello, 
I am following the initial tutorial to use MediaPipe : https://google.github.io/mediapipe/getting_started/building_examples.html#option-1-build-with-bazel-in-command-line 

However I am on a windows so I have to resort to using a Linux subsystem. But when trying to run the build command I get the following error:
ERROR: /mediapipe/WORKSPACE:195:23: //external:android/crosstool depends on @androidndk//:default_crosstool in repository @androidndk which failed to fetch. no such package '@androidndk//': Either the path attribute of android_ndk_repository or the ANDROID_NDK_HOME  environment variable must be set.

I don't know what to set as my path because the Android Studio packages are installed on my local machine whereas mediapipe is on the Linux subsystem. Any help would be appreciated, thank you.

Linux v.20
Android Studio 3.5
Bazel 2.0.0

**Comment by jiuqiant** [comment] 2020-06-16 21:48
We provide a script to do this:https://github.com/google/mediapipe/blob/master/setup_android_sdk_and_ndk.sh. Run something like the following in WSL.

```
./setup_android_sdk_and_ndk.sh ~/Android/Sdk ~/Android/Ndk r18b
```

**Comment by j-vent** [comment] 2020-06-16 21:59
Hi, I did run this command before running the build but I still get that error.

**Comment by jiuqiant** [comment] 2020-06-17 06:19
The script will modify your WORKSPACE file. Can you run `git diff` to see if it happens?

**Comment by jiuqiant** [comment] 2020-06-19 17:04
Based on https://github.com/google/mediapipe/issues/810#issuecomment-646438179, I think the problem is solved by yourself. I am going to close this issue.

**Closed by jiuqiant** 2020-06-19 17:04 UTC
