### ISSUE TITLE
face mesh app output wrong mesh

### ISSUE THREAD

**Issue by wwdok** [google/mediapipe#3327] opened 2022-05-06 05:08 UTC
<em>Please make sure that this is a [solution](https://google.github.io/mediapipe/solutions/solutions.html) issue.<em>

**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Android 10
- [MediaPipe version](https://github.com/google/mediapipe/releases): latest
- Bazel version:
- Solution (e.g. FaceMesh, Pose, Holistic): FaceMesh
- Programming Language and version ( e.g. C++, Python, Java): 

**Describe the expected behavior:**

I git clone this repo, and use Android Studio to open C:\MachineLearning\mediapipe\mediapipe\examples\android\solutions, then i build the app, this is the output apk:
[facemesh-debug.zip](https://github.com/google/mediapipe/files/8637617/facemesh-debug.zip)
then i install the app on my phone (XIAOMI 8 SE), it shows the mesh result as below :
![image](https://user-images.githubusercontent.com/43233772/167070468-ce85c23d-265f-427b-a9a9-fe580cfa0704.png)

**Comment by wwdok** [comment] 2022-05-07 15:04
By the way, how to mesure the FPS of model inference in the android example app, where to place what codes ? Thanks in advance ~

**Comment by sureshdagooglecom** [comment] 2022-05-09 07:37
Hi @wwdok ,
Could you please share your code changes to investigate further on this issue.

**Comment by wwdok** [comment] 2022-05-10 16:07
@sureshdagooglecom Hi, i didn't change any code, is it convenient for you to use the latest code to build the face mesh android apk on your computer ?

**Comment by jiuqiant** [comment] 2022-05-18 15:55
Similar to https://github.com/google/mediapipe/issues/3326#issuecomment-1120087511, the issue is fixed in the latest android maven package.

**Closed by jiuqiant** 2022-05-18 15:55 UTC
Labels: type:support, platform:android, stat:awaiting response, solution:face mesh, stalled

**Comment by wwdok** [comment] 2022-05-19 08:57
@jiuqiant I rebuild the app, now it is normal. By the way, could you please tell me how to mesure the FPS of model inference in the android example app, where to place what codes ? I am not familiar with java

**Comment by sureshdagooglecom** [comment] 2022-05-19 11:53
Hi @wwdok ,
This issue is corrected in the latest version (more recent versions) of MediaPipe.  
you can check this closed issue https://github.com/google/mediapipe/issues/598 to check model FPS.
