### ISSUE TITLE
Uncaught (in promise) Error: StartGraph failed: $ExternalFile must specify at least one of 'file_content', 'file_name', 'file_pointer_meta' or 'file_descriptor_meta'.; Initialize was not ok

### ISSUE THREAD

**Issue by lc-spxl** [google/mediapipe#4736] opened 2023-08-30 16:35 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

Web / SvelteKit

### MediaPipe Tasks SDK version

npm package

### Task name (e.g. Image classification, Gesture recognition etc.)

Audio Classifier

### Programming Language and version (e.g. C++, Python, Java)

Javascript (Typescript)

### Describe the actual behavior

```shell
Running the same example as here https://codepen.io/mediapipe-preview/pen/wvxYYmy?editors=1111

We do also have video tasks running correctly (pose,face,hands)
```

### Describe the expected behaviour

```shell
It's should work
```

### Standalone code/steps you may have used to try to get what you need

```shell
import { AudioClassifier, FilesetResolver } from '@mediapipe/tasks-audio';

export const createAudioClassifier = async () => {
  const audio = await FilesetResolver.forAudioTasks(
    "https://cdn.jsdelivr.net/npm/@mediapipe/tasks-audio@0.10.0/wasm"
  );

  const audioClassifier = await AudioClassifier.createFromOptions(audio, {
    baseOptions: {
      modelAssetPath:
        "https://storage.googleapis.com/mediapipe-models/audio_classifier/yamnet/float32/1/yamnet.tflite"
    }
  });

  return audioClassifier
};
```

![image](https://github.com/google/mediapipe/assets/105427834/50a7d0ad-a545-46ee-956d-613e0662d1d1)

### Other info / Complete Logs

```shell
audio_bundle.mjs:1 Uncaught (in promise) Error: StartGraph failed: $ExternalFile must specify at least one of 'file_content', 'file_name', 'file_pointer_meta' or 'file_descriptor_meta'.; Initialize was not ok
    at m.handleErrors (audio_bundle.mjs:1:411894)
    at m.setGraph (audio_bundle.mjs:1:411578)
    at m.refreshGraph (audio_bundle.mjs:1:419240)
    at audio_bundle.mjs:1:410967
    at async createTaskRunner (audio_bundle.mjs:1:409524)
    at async createAudioClassifier (AudioClassifier.ts:8:27)
    at async detectSilence (Microphone.svelte:151:27)
```

**Comment by kuaashish** [comment] 2023-08-31 11:04
Hello @schmidt-sebastian,

Could you please look into this issue. Thank you

**Comment by schmidt-sebastian** [comment] 2023-08-31 21:17
Thank you for reporting this. We will have to do some investigation here to see what the root cause is.

**Comment by alessandroperetti** [comment] 2023-09-01 14:52
Hi, 
I don't know if it can help but disabling `tasks-vision` (delete the npm package and all the import inside the source code), `tasks-audio` start to work again. 

I am thinking, may be there is a conflict between the packages?

**Comment by schmidt-sebastian** [comment] 2023-09-12 16:17
This has been fixed internally. Release is coming shortly.

**Closed by schmidt-sebastian** 2023-09-12 16:17 UTC
Labels: type:support, platform:javascript, stat:awaiting googler, task:audio classification
