### ISSUE TITLE
Screen enlargement using hand trackingpu

### ISSUE THREAD

**Issue by MakeMeCookie** [google/mediapipe#3992] opened 2023-01-13 01:45 UTC
**System information** (Please provide as much relevant information as possible)
- Have I written custom code (as opposed to using a stock example script provided in Mediapipe): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04, Android 11, iOS 14.4): Linux Ubuntu 22.04 , Android 10
- [MediaPipe version](https://github.com/google/mediapipe/releases): mediapipe master
- Bazel version: bazel 6.0.0
- Solution (e.g. FaceMesh, Pose, Holistic): Handtrackingpu
- Programming Language and version ( e.g. C++, Python, Java): java, android

I used hand tracking pu to do hand recognition. Hand recognition is recognized up to 1.8m. But if you're off the street, the dots aren't recognized. In this case, I want to enlarge the screen. What should I do in this case?
and Can I use the rear camera and web camera to add zoom function?

If there is a problem, provide a reproducible test case that is the bare minimum necessary to generate the problem. If possible, please share a link to Colab/repo link /any notebook: https://github.com/google/mediapipe

**Comment by MakeMeCookie** [comment] 2023-01-13 02:30
I set up the rear camera, but it doesn't zoom in because it doesn't have a zooming function:(
Rear Camera Settings
<AndroidManifest.xml>
 <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
    <uses-permission android:name="android.hardware.camera.front" android:required="false"/>
...
     </activity>

        <meta-data android:name="cameraFacingFront" android:value="true"/>

<mainactivity>
import android.Manifest;
import android.content.Intent;
import android.os.Bundle;
import androidx.appcompat.app.AppCompatActivity;

**Comment by MakeMeCookie** [comment] 2023-01-13 02:40
I set up the rear camera. But the zoom still doesn't work. How do I add zoom? :(
Rear Camera Settings

**Comment by kuaashish** [comment] 2023-01-13 06:29
Hi @MakeMeCookie,
Closing this issue as Duplicate of #3969. Please follow up with another issue raised and we are following with the team to get possible resolution on the query raised.

**Closed by kuaashish** 2023-01-13 06:29 UTC
Labels: type:support, platform:android, solution:hands, android::camera
