### ISSUE TITLE
Adding ImageFrameToGpuBufferCalculator followed by GpuBufferToImageFrameCalculator do not return original image

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#704] opened 2020-05-07 12:19 UTC
The experiment is done over mobile phone as it cannot be done on desktop due to #694. Since MediaPipe does not have support for screenshot on mobile phone, I cannot post the test results here.

As MediaPipe also has a bad support for manually inserting test image into the graph over Android, I can only feed the test image by modifying the ImageFrame in the node before the ImageTransformationCalculator using the following code:

```
  bool flag = true;
  for (int i = 0; i < input_mat.rows; i++) {
    for (int j = 0; j < input_mat.cols; j++) {
      if (flag) {
        input[(i*input_mat.rows + j) * 4 + 0] = 0;
        input[(i*input_mat.rows + j) * 4 + 1] = 0;

        input[(i*input_mat.rows + j) * 4 + 2] = 0;
      } else {
        input[(i*input_mat.rows + j) * 4 + 0] = 255;
        input[(i*input_mat.rows + j) * 4 + 1] = 0;
        input[(i*input_mat.rows + j) * 4 + 2] = 0;
      }
      input[(i*input_mat.rows + j) * 4 + 3] = 255;
      flag = !flag;
    }
  } 
```

This create an image with alternating black and red lines. Then I run it through the ImageTransformationCalculator to downsample the image to 11x11 (so the the differences is more obvious). Let's call this image A.

Then I pass A through a ImageFrameToGpuBufferCalculator, followed by GpuBufferToImageFrameCalculator, to create image B. B should be exactly the same as A!

However, A is different from B.

Why? Is this a bug?

**Comment by jiuqiant** [comment] 2020-05-07 17:27
I think it's because MediaPipe has different default image frame alignment boundary for CPU and GPU: https://github.com/google/mediapipe/blob/master/mediapipe/framework/formats/image_frame.h#L75. When CPU image frame is created, it uses a 4-byte alignment boundary. However, what GpuBufferToImageFrameCalculator returns is an image frame with 16-byte alignment boundary: https://github.com/google/mediapipe/blob/master/mediapipe/gpu/gpu_buffer_to_image_frame_calculator.cc#L88. If you see the different between the data arrays, the different alignment boundaries may be the root cause.

**Comment by yxchng** [comment] 2020-05-08 00:51
@jiuqiant Is this unavoidable problem?

**Comment by sgowroji** [comment] 2021-07-29 06:03
Hi @yxchng,  Above [comment](https://github.com/google/mediapipe/issues/704#issuecomment-625392448) answered your query. We are closing this issue now. Feel free to reach if you still have any relevant query with above context.

**Closed by sgowroji** 2021-07-29 06:03 UTC
Labels: calculators, type:support
