### ISSUE TITLE
Coral Support - Bazel Setup  :ERROR: Skipping 'build': no such target '//:build'

### ISSUE THREAD

**Issue by fjzhangcr** [google/mediapipe#3713] opened 2022-09-22 08:04 UTC
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)
- OS Platform and Distribution (e.g. Linux Ubuntu 16.04, Android 11, iOS 14.4): ubuntu
- Compiler version (e.g. gcc/g++ 8 /Apple clang version 12.0.0):
- Programming Language and version ( e.g. C++ 14, Python 3.6, Java ):
- Installed using virtualenv? pip? Conda? (if python):
- [MediaPipe version](https://github.com/google/mediapipe/releases):
- Bazel version:  5.2.0
- XCode and Tulsi versions (if iOS):
- Android SDK and NDK versions (if android):
- Android [AAR](https://google.github.io/mediapipe/getting_started/android_archive_library.html) ( if android):
- OpenCV version (if running on desktop):

**Describe the problem**:
i have basel 5.2.0 version and ran mediapipe edgtpu demo
`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ ls`
indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ ls
build_android_examples.sh  build_desktop_examples.sh  CONTRIBUTING.md  docs     MANIFEST.in  README.md         setup_android_sdk_and_ndk.sh  setup.py     WORKSPACE
BUILD.bazel                build_ios_examples.sh      Dockerfile       LICENSE  mediapipe    requirements.txt  setup_opencv.sh               third_party

`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel version`
Build label: 5.2.0
Build target: bazel-out/k8-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue Jun 7 16:02:26 2022 (1654617746)
Build timestamp: 1654617746
Build timestamp as int: 1654617746

my scripts strictly follow the readme.md here:
[Coral Support - Bazel Setup](https://github.com/google/mediapipe/tree/master/mediapipe/examples/coral)
`indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel build --compilation_mode=opt --define darwinn_portable=1 --define MEDIAPIPE_DISABLE_GPU=1 --define MEDIAPIPE_EDGE_TPU=usb --linkopt=-l:libusb-1.0.so mediapipe/examples/coral:face_detection_tpu build`

I received an error of bazel build
indeed@indeed-virtual-machine:~/Desktop/mediapipe-master$ bazel build --compilation_mode=opt --define darwinn_portable=1 --define MEDIAPIPE_DISABLE_GPU=1 --define MEDIAPIPE_EDGE_TPU=usb --linkopt=-l:libusb-1.0.so mediapipe/examples/coral:face_detection_tpu build
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_absl' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_benchmark' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11_bazel' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_protobuf' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_google_googletest' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'com_github_gflags_gflags' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_apple' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_rules_swift' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'build_bazel_apple_support' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'xctestrunner' because it already exists.
DEBUG: /home/indeed/.cache/bazel/_bazel_indeed/8841f98192e74cc58dc35ba42db474f7/external/org_tensorflow/third_party/repo.bzl:124:14:
Warning: skipping import of repository 'pybind11' because it already exists.
ERROR: Skipping 'build': no such target '//:build': target 'build' not declared in package '' defined by /home/indeed/Desktop/mediapipe-master/BUILD.bazel
ERROR: no such target '//:build': target 'build' not declared in package '' defined by /home/indeed/Desktop/mediapipe-master/BUILD.bazel
INFO: Elapsed time: 0.341s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**[Provide the exact sequence of commands / steps that you executed before running into the problem](https://google.github.io/mediapipe/getting_started/getting_started.html):**

**Complete Logs:**
Include Complete Log information or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached:

**Comment by kuaashish** [comment] 2022-09-23 09:06
Duplicate of #3520

**Comment by kuaashish** [comment] 2022-09-23 09:08
Hi @fjzhangcr, We are following up with issue #3520 and closing it as a duplicate. Thank you!

**Closed by kuaashish** 2022-09-23 09:08 UTC
Labels: status:duplicate, type:build/install, platform:desktop, solution:face detection, platform:coral
