### ISSUE TITLE
build fail

### ISSUE THREAD

**Issue by qichuangguo** [google/mediapipe#3057] opened 2022-02-08 01:48 UTC
bazel build -c opt --strip=ALWAYS     --host_crosstool_top=@bazel_tools//tools/cpp:toolchain     --fat_apk_cpu=arm64-v8a,armeabi-v7a     //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mediapipe_face_detection.aar

load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
    name = "mediapipe_face_detection",
    calculators = ["//mediapipe/graphs/face_detection:mobile_calculators"],
)

build fail log:

/home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/external/maven/BUILD:7:11: Merging compiled Android resources for @maven//:androidx_activity_activity failed: (Exit 1): ResourceProcessorBusyBox failed: error executing command bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput ... (remaining 15 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Feb 08, 2022 9:45:45 AM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
SEVERE: Error during merging resources
com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging
	at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:75)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:283)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: lStar
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:122)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
	... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: lStar
	at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:48)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)
	... 6 more

Feb 08, 2022 9:45:45 AM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during merging
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:mediapipe_face_detection.aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 1.208s, Critical Path: 1.04s
INFO: 129 processes: 129 internal.
FAILED: Build did NOT complete successfully

**Comment by sgowroji** [comment] 2022-02-08 06:13
Hi @qichuangguo,  Could you please share your code or graph changes on the above request to troubleshoot further. Thanks!

**Comment by qichuangguo** [comment] 2022-02-08 06:55
Didn't change any code, compile it, report an error.

**Comment by sgowroji** [comment] 2022-02-09 17:08
Seems Duplicate of https://github.com/google/mediapipe/issues/3050.  Did you put the BUILD file in the mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar dir or somewhere else?

**Comment by qichuangguo** [comment] 2022-02-10 00:51
Thank you. I reinstalled the environment and I'm ready

**Comment by sgowroji** [comment] 2022-02-10 02:59
Glad you resolved. Thank you for confirmation. We are closing this issue now.

**Closed by sgowroji** 2022-02-10 02:59 UTC
Labels: status:duplicate, type:build/install, solution:face detection, android::aar

**Comment by sayhi12345** [comment] 2022-09-02 02:49
> 

Hi @qichuangguo, what do you mean by reinstalling? you reinstall your sdk and ndk or just restart your bazel build?
Thank you!

**Comment by rolandeke** [comment] 2023-04-07 16:56
I know this issue has been closed but I am having error 

/home/chinedumeke/.cache/bazel/_bazel_chinedumeke/9b0c45ac7d66435dc85b349a16a12d35/external/maven/BUILD:252:11: Merging compiled Android resources for @maven//:androidx_core_core failed: (Exit 1): ResourceProcessorBusyBox failed: error executing command (from target @maven//:androidx_core_core) bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput ... (remaining 15 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Apr 07, 2023 4:52:40 PM com.google.devtools.build.android.AndroidCompiledResourceMergingAction main
SEVERE: Error during merging resources
com.google.devtools.build.android.AndroidResourceMerger$MergingException: Error during merging
        at com.google.devtools.build.android.AndroidResourceMerger$MergingException.wrapException(AndroidResourceMerger.java:74)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:227)
        at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
        at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:85)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:251)
        at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:181)
Caused by: java.io.IOException: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontVariationSettings
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:122)
        at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
        at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:219)
        ... 4 more
Caused by: com.google.devtools.build.android.AndroidFrameworkAttrIdProvider$AttrLookupException: Android attribute not found: fontVariationSettings
        at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:48)
        at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)
        at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)
        at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)
        ... 6 more

Apr 07, 2023 4:52:40 PM com.google.devtools.build.android.ResourceProcessorBusyBox processRequest
SEVERE: Error during merging
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/handtrackinggpu:handtrackinggpu failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/chinedumeke/mediapipe/mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/BUILD:18:16 Building mediapipe/examples/android/src/java/com/google/mediapipe/apps/basic/libbasic_lib.jar (1 source file) failed: (Exit 1): ResourceProcessorBusyBox failed: error executing command (from target @maven//:androidx_core_core) bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput ... (remaining 15 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
INFO: Elapsed time: 91.498s, Critical Path: 84.52s
INFO: 1030 processes: 206 internal, 812 linux-sandbox, 12 worker.
FAILED: Build did NOT complete successfully

**Comment by kaka-lin** [comment] 2023-05-19 07:39
Hi @qichuangguo,

I also have this error, what do you mean by reinstalling? 

Thank you

**Comment by qichuangguo** [comment] 2023-06-12 03:32
bazel reinstall @kaka-lin

**Comment by WitmanTzahi** [comment] 2023-06-18 06:33
> bazel reinstall @kaka-lin

Getting the following error:
Command 'reinstall' not found. Try 'bazel help'.
