### ISSUE TITLE
How to clean up memory after model is not used anymore?

### ISSUE THREAD

**Issue by ostap0207** [google/mediapipe#2819] opened 2021-11-25 20:43 UTC
Solution: Selfie Segmentation JS

I am trying to close/clean up memory after SelfieSegmentation is not needed anymore, however cannot find a way to do it.

Steps to reproduce:
Example page: https://ostap0207.github.io/mediapipe-selfie-segmentation-release-memory/index.html
To close execute `stop()` in the console which will do:

```javascript
    selfieSegmentation.close().then(() => {
      selfieSegmentation = null;
      videoElement = null;
      canvasElement = null;
      canvasCtx = null;
      camera = null;
      window.createMediapipeSolutionsPackedAssets = null; 
    });
```
Record memory snapshot in `Inspector > Memory > Heap snapshot`

Results:
There is still memory allocated (see `JSArrayBufferData@204689`) which seems to be references by `pointerLockChange` function that is added as event listener.
<img width="792" alt="Screenshot 2021-11-25 at 22 39 57" src="https://user-images.githubusercontent.com/2852092/143498048-559ced2d-1a02-43f5-9d30-9c2351247024.png">

Anything else I can do to free up the remaining memory?

**Comment by mhays-google** [comment] 2021-11-29 15:23
I know that some of the underlying implementations on which we rely create some globals, and this is an issue we need to look into.  Here, I believe that the issue is that there are elements added to the DOM that never get released (An HTMLCanvasElement is used for all of our GPU work, for instance).  I've added a bug internally to address this, but I don't have a timeline for when it will be resolved.

**Comment by mhays-google** [comment] 2021-12-14 23:37
Closing for now.  We are not currently looking into this (although I definitely see how this would be valuable).

**Closed by mhays-google** 2021-12-14 23:37 UTC
Labels: type:support, stat:awaiting response, platform:javascript, stalled, solution:selfie segmentation

**Comment by hughfenghen** [comment] 2022-06-20 11:35
@ostap0207  Hi, try exec `rmDocLockListener` in your `stop` function
```ts
// workaround: https://github.com/google/mediapipe/issues/2819
const _docAddEvtListener = document.addEventListener
let pointerLockArgs: Array<{ args: [any, any], typeName: string }> = []
document.addEventListener = (typeName: string, ...args: [any, any]) => {
  if (
    [
      'pointerlockchange',
      'mozpointerlockchange',
      'webkitpointerlockchange',
      'mspointerlockchange'
    ].indexOf(typeName) !== -1
  ) {
    pointerLockArgs.push({ typeName, args })
  }
  _docAddEvtListener.call(document, typeName, ...args)
}

function rmDocLockListener(): void {
  window.createMediapipeSolutionsPackedAssets = null
  pointerLockArgs.forEach(({ typeName, args }) => {
    document.removeEventListener(typeName, ...args)
  })
  pointerLockArgs = []
}
```

**Comment by amey-323** [comment] 2024-10-12 11:57
> @ostap0207 Hi, try exec `rmDocLockListener` in your `stop` function
> 
> ```js
> const _docAddEvtListener = document.addEventListener
> let pointerLockArgs = []
> document.addEventListener = (typeName, ...args) => {
>   if (
>     [
>       'pointerlockchange',
>       'mozpointerlockchange',
>       'webkitpointerlockchange',
>       'mspointerlockchange'
>     ].indexOf(typeName) !== -1
>   ) {
>     pointerLockArgs.push({ typeName, args })
>   }
>   _docAddEvtListener.call(document, typeName, ...args)
> }
> 
> function rmDocLockListener() {
>   window.createMediapipeSolutionsPackedAssets = null
>   pointerLockArgs.forEach(({ typeName, args }) => {
>     document.removeEventListener(typeName, ...args)
>   })
>   pointerLockArgs = []
> }
> ```

I tried this solution and it worked on localhost but while testing it on production it didn't worked successfully anything which I missed during implementing this solution @hughfenghen 
Attaching following screenshot for the same where when tested after deploying on production
![image](https://github.com/user-attachments/assets/a907b6ee-951d-485b-a240-57c107afe725)
