### ISSUE TITLE
Javascript api documentation and/or typescript declarations?

### ISSUE THREAD

**Issue by BSchrift** [google/mediapipe#1806] opened 2021-03-27 19:42 UTC
Hi, I'm working on a react and typescript based webapp and I would like to use the mediapipe javascript api. Has anyone written any working typescript declarations for the api? Also, is there any more detailed API reference than just the codepen examples and small snippets found on the homepage?

Thanks so much for your help.

**Comment by sgowroji** [comment] 2021-03-29 11:03
Hi Duplicate of this https://github.com/google/mediapipe/issues/1408

**Closed by sgowroji** 2021-03-29 11:03 UTC
Labels: platform:javascript, status:duplicate

**Comment by Choons** [comment] 2021-03-30 00:30
Only very basic features are exposed in the javascript release. Can't do most of the things mentioned in the glowing write-up
