### ISSUE TITLE
RuntimeError: Unable to initialize runfiles: ERROR: external/bazel_tools/tools/cpp/runfiles/runfiles.cc(120): cannot find runfiles (argv0="")

### ISSUE THREAD

**Issue by RTL8710** [google/mediapipe#4220] opened 2023-03-31 02:07 UTC
### OS Platform and Distribution

window 7

### Programming Language and version

Python

### MediaPipe version

0.9.2

### Android AAR (if android)

None

### Describe the problem

```shell
detector = vision.ObjectDetector.create_from_options(options)
```

### Complete Logs

```shell
Traceback (most recent call last):
  File "D:/AI/mediaPipeExample/object_detector.py", line 17, in <module>
    detector = vision.ObjectDetector.create_from_options(options)
  File "D:\AI\mediaPipeExample\venv\lib\site-packages\mediapipe\tasks\python\vision\object_detector.py", line 207, in create_from_options
    return cls(
  File "D:\AI\mediaPipeExample\venv\lib\site-packages\mediapipe\tasks\python\vision\core\base_vision_task_api.py", line 66, in __init__
    self._runner = _TaskRunner.create(graph_config, packet_callback)
RuntimeError: Unable to initialize runfiles: ERROR: external/bazel_tools/tools/cpp/runfiles/runfiles.cc(120): cannot find runfiles (argv0="")
```

**Comment by kuaashish** [comment] 2023-03-31 04:25
Hi @RTL8710,
Could you let us know the complete steps you have followed, standalone code to reproduce and look into the issue share the possible solution in the root cause.

**Comment by RTL8710** [comment] 2023-03-31 13:00
- ## [object_detector.ipynb](https://colab.research.google.com/github/googlesamples/mediapipe/blob/main/examples/object_detection/python/object_detector.ipynb#scrollTo=Yl_Oiye4mUuo&line=2&uniqifier=1)

- ## python version and mediapipe version:
![image](https://user-images.githubusercontent.com/22052451/229126351-e626a506-ed1f-4858-8c5d-b1b563c511d2.png)

- ## code
`# STEP 1: Import the necessary modules.
import numpy as np
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision


IMAGE_FILE = 'cat_and_dog.jpg'

import cv2
# from google.colab.patches import cv2_imshow

# STEP 2: Create an ObjectDetector object.
base_options = python.BaseOptions(model_asset_path='efficientdet_lite2_uint8.tflite')
options = vision.ObjectDetectorOptions(base_options=base_options,
                                       score_threshold=0.5)
detector = vision.ObjectDetector.create_from_options(options)
# detector =  vision.ObjectDetector.create_from_model_path("efficientdet_lite2_uint8.tflite")


# STEP 3: Load the input image.
image = mp.Image.create_from_file(IMAGE_FILE)

# STEP 4: Detect objects in the input image.
detection_result = detector.detect(image)
mp_drawing = mp.solutions.drawing_utils
# STEP 5: Process the detection result. In this case, visualize it.
image_copy = np.copy(image.numpy_view())
# annotated_image = visualize(, detection_result)
mp_drawing.draw_detection(image_copy, detection_result)
rgb_annotated_image = cv2.cvtColor(image_copy, cv2.COLOR_BGR2RGB)
cv2.imshow('face_mesh_annotated_image', rgb_annotated_image)
`

**Comment by kuaashish** [comment] 2023-03-31 15:19
@RTL8710,
Thank you for bringing up to our notice, this issue is known to us and we are working towards fix. As workaround, you can  load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47

**Comment by RTL8710** [comment] 2023-03-31 16:09
tks The problem has been resolved！

**Comment by RTL8710** [comment] 2023-03-31 16:16
May I ask you a new question: How to efficiently and succinctly convert the output of the model into the structure of the C language by porting the mediapipe model (object_dection) to the arm embedded system?
![image](https://user-images.githubusercontent.com/22052451/229174812-ab8054ea-f1db-4dbb-a5bb-2d3a1f2d8d4b.png)

**Comment by kuaashish** [comment] 2023-03-31 16:21
@RTL8710,
Good to hear that issue has been resolved. However, this issue seems to be related to a different error. To keep the context of the issue as relevant to the original issue as possible, may I suggest you close this issue and open another one?
This helps community and us to search the issues better in concise manner. thank you

**Comment by RTL8710** [comment] 2023-04-02 15:05
ok

**Comment by kuaashish** [comment] 2023-04-03 03:39
@RTL8710,
Thank you for the confirmation, Closing this as resolved. Please raise new issue with another query mentioned here.

**Closed by kuaashish** 2023-04-03 03:39 UTC
Labels: type:build/install, solution:object detection, type:tasks

**Comment by xiaolinpeter** [comment] 2023-04-11 12:03
> @RTL8710, Thank you for bringing up to our notice, this issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47

thanks your reply, but i try it as you, but a error as follow:
![image](https://user-images.githubusercontent.com/27184803/231156994-c0ff02fc-23d3-4aa2-a53a-b29d50aaa7c1.png)

**Comment by xiaolinpeter** [comment] 2023-04-11 12:04
> > @RTL8710, Thank you for bringing up to our notice, this issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47
> 
> thanks your reply, but i try it as you, but a error as follow: ![image](https://user-images.githubusercontent.com/27184803/231156994-c0ff02fc-23d3-4aa2-a53a-b29d50aaa7c1.png)

the code as follow:
`#!/usr/bin/env python
# -*- coding: utf-8 -*-
'''
@Project ：mediapipe 
@File ：mediapipe_task.py
@Author ：xiaolin_peter
@email：zheng.xiaolin@tslsmart.com
@Date ：2023/3/5 15:28 
'''
# STEP 1: Import the necessary modules.
import mediapipe as mp
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from baseOptions import BaseOptions
# STEP 2: Create an GestureRecognizer object.
base_options = python.BaseOptions(model_asset_buffer='gesture_recognizer.task')
options = vision.GestureRecognizerOptions(base_options=base_options)
recognizer = vision.GestureRecognizer.create_from_options(options)

images = []
results = []
IMAGE_FILENAMES = ["images/img.png"]
for image_file_name in IMAGE_FILENAMES:
  # STEP 3: Load the input image.
  image = mp.Image.create_from_file(image_file_name)
  # STEP 4: Recognize gestures in the input image.
  recognition_result = recognizer.recognize(image)
  # STEP 5: Process the result. In this case, visualize it.
  images.append(image)
  top_gesture = recognition_result.gestures[0][0]
  hand_landmarks = recognition_result.hand_landmarks
  results.append((top_gesture, hand_landmarks))
  print(hand_landmarks)
`

**Comment by xiaolinpeter** [comment] 2023-04-11 12:10
> > > @RTL8710, Thank you for bringing up to our notice, this issue is known to us and we are working towards fix. As workaround, you can load the file manually and use model_asset_buffer: https://github.com/google/mediapipe/blob/master/mediapipe/tasks/python/core/base_options.py#L47
> > 
> > 
> > thanks your reply, but i try it as you, but a error as follow: ![image](https://user-images.githubusercontent.com/27184803/231156994-c0ff02fc-23d3-4aa2-a53a-b29d50aaa7c1.png)
> 
> the code as follow: `#!/usr/bin/env python
> 
> # -_- coding: utf-8 -_-
> ''' @project ：mediapipe @file ：mediapipe_task.py @author ：xiaolin_peter @email：[zheng.xiaolin@tslsmart.com](mailto:zheng.xiaolin@tslsmart.com) @Date ：2023/3/5 15:28 '''
> 
> # STEP 1: Import the necessary modules.
> import mediapipe as mp from mediapipe.tasks import python from mediapipe.tasks.python import vision from baseOptions import BaseOptions
> 
> # STEP 2: Create an GestureRecognizer object.
> base_options = python.BaseOptions(model_asset_buffer='gesture_recognizer.task') options = vision.GestureRecognizerOptions(base_options=base_options) recognizer = vision.GestureRecognizer.create_from_options(options)
> 
> images = [] results = [] IMAGE_FILENAMES = ["images/img.png"] for image_file_name in IMAGE_FILENAMES:
> 
> # STEP 3: Load the input image.
> image = mp.Image.create_from_file(image_file_name)
> 
> # STEP 4: Recognize gestures in the input image.
> recognition_result = recognizer.recognize(image)
> 
> # STEP 5: Process the result. In this case, visualize it.
> images.append(image) top_gesture = recognition_result.gestures[0][0] hand_landmarks = recognition_result.hand_landmarks results.append((top_gesture, hand_landmarks)) print(hand_landmarks) `

**finally,  my python version is 3.8 and mediapipe version 0.9.2.1**
