### ISSUE TITLE
Apple silicon (M1) prebuilt mediapipe wheels released on PyPI

### ISSUE THREAD

**Issue by cansik** [google/mediapipe#3277] opened 2022-04-22 18:03 UTC
As already mentioned in https://github.com/google/mediapipe/pull/2591#issuecomment-1105351727, I have created an [automated script](https://github.com/cansik/mediapipe-silicon) to build mediapipe for Apple silicon (M1) Mac (Monterey `12`). The prebuilt binaries are hosted on [PyPI](https://pypi.org/project/mediapipe-silicon/) which makes installation as simple as possible:

```
pip install mediapipe-silicon
```

If you want to include mediapipe in a `requirements.txt`, I would suggest the following two lines to either install the default version or the Apple silicon version:

```
mediapipe>=0.8.9; platform_system != "Darwin" and platform.machine != 'arm64'
mediapipe-silicon>=0.8.9; platform_system == "Darwin" and platform.machine == 'arm64'
```

I look forward to feedback and suggestions from the community.
Hopefully the official mediapipe wheels will be updated soon to support Apple silicon.

**Comment by sureshdagooglecom** [comment] 2022-05-13 04:50
Hi @cansik ,
MediaPipe maintainers are aware of this issue and working on support , we will do it in the next release.

**Comment by sureshdagooglecom** [comment] 2022-05-17 10:00
Hi @cansik ,
Closing this issue ,if  any further issues please Reopen this issue.

**Closed** 2022-05-17 10:00 UTC
Labels: platform:ios, type:build/install, stat:awaiting response

**Comment by maricinnamon** [comment] 2022-07-12 09:31
Hi @cansik, can you, please, help to install it to Mac OS 11.2.3 (M1 Pro 2020)? 
Because using your script `pip install mediapipe-silicon` doesn't work for me. 
Maybe, you know, how to install it?
Thank you

**Comment by cansik** [comment] 2022-07-12 15:49
@maricinnamon Please open an issue in the following repository and provide some more information (python version, architecture, error message and so on):

https://github.com/cansik/mediapipe-silicon

**Comment by MSayedQ** [comment] 2023-02-06 08:11
Hi pip install mediapipe is not installing on windows and my python version is 3.11 how can I install mediapipe

**Comment by kuaashish** [comment] 2023-02-06 09:20
@MSayedQ,
Could you please raise a new issue with complete details/error logs and steps followed to reproduce the issue. Thanks!
