### ISSUE TITLE
Hair segmentation with mediapipe on tensorflow lite

### ISSUE THREAD

**Issue by Arezki93** [google/mediapipe#2312] opened 2021-07-19 15:33 UTC
Hi,

I am trying to use mediapipe's hair segmentation model in script but I am coming across the error of

RuntimeError:`` Encountered unresolved custom op: MaxPoolingWithArgmax2D.Node number 12 (MaxPoolingWithArgmax2D) failed to prepare.

can you please explain how did you created the without custom op version of the mediapipe model ?

**Comment by sgowroji** [comment] 2021-07-20 05:27
Hi @Arezki93, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by Arezki93** [comment] 2021-07-20 07:54
Hi @sgowroji, thank you for the answer, here are the steps I followed : 
1) I loaded the hair_segmentation.tflite file
2) I did a allocate_tensors() -> it generates an error (Encountered unresolved custom op: MaxPoolingWithArgmax2D.Node number 12 (MaxPoolingWithArgmax2D) failed to prepare)

`import tensorflow as tf`
`import numpy as np`
`interpreter = tf.lite.Interpreter('hair_segmentation.tflite')`
`interpreter.allocate_tensors()`
**---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-1452d1ea2c55> in <module>
      1 model_file = 'hair_segmentation.tflite'
      2 interpreter = tf.lite.Interpreter(model_path = model_file)
----> 3 interpreter.allocate_tensors()

~\anaconda3\lib\site-packages\tensorflow\lite\python\interpreter.py in allocate_tensors(self)
    406   def allocate_tensors(self):
    407     self._ensure_safe()
--> 408     return self._interpreter.AllocateTensors()
    409 
    410   def _safe_to_run(self):

RuntimeError: Encountered unresolved custom op: MaxPoolingWithArgmax2D.Node number 12 (MaxPoolingWithArgmax2D) failed to prepare.**

**Comment by TomerJakobovich** [comment] 2021-08-08 13:29
I also encountered this issue, @Arezki93 did you find a solution?

**Comment by Arezki93** [comment] 2021-08-10 08:06
unfortunately I did not find a solution !

Le dim. 8 août 2021 à 15:29, TomerJakobovich ***@***.***> a
écrit :

**Comment by sgowroji** [comment] 2021-08-12 03:35
Hi @Arezki93,  MediaPipe tflite where updated with ops here https://github.com/google/mediapipe/blob/ecb5b5f44ab23ea620ef97a479407c699e424aa7/mediapipe/util/tflite/cpu_op_resolver.cc#:~:text=void%20MediaPipe_RegisterTfLiteOpResolver(tflite,%7D But not sure about it in python.

**Comment by jiuqiant** [comment] 2021-08-12 16:08
MediaPipe repo has custom ops for the hair segmentation model. So, using the model with tflite python interpreter directly doesn't work. You need to copy the custom ops to a local TensorFlow repo and rebuild its python package.

Since it's not a MediaPipe Python issue, reassign this back to @sgowroji .

**Comment by sgowroji** [comment] 2021-08-18 09:26
Closing this issue w.r.t the above comments,  answers your query.

**Closed by sgowroji** 2021-08-18 09:26 UTC
Labels: type:support, platform:tflite, solution:hair segmentation
