### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/user/0/com.google.mediapipe.examples.facemesh/incrementallib/libmediapipe_jni.so" is 32-bit instead of 64-bit 

### ISSUE THREAD

**Issue by dharmeshdevstree** [google/mediapipe#3920] opened 2022-12-12 14:38 UTC
![imgpsh_fullsize_anim (1)](https://user-images.githubusercontent.com/86298602/207072875-9bbbe530-ae5e-4e9f-98f6-afcaac66d849.png)

Hello,
Any one have an idea on this
i have been using android-ndk-r21b-linux-x86_64 NDK in Ubuntu 20.02 64 bit.

**Comment by ayushgdev** [comment] 2022-12-13 05:58
Hi @dharmeshdevstree 
Can you please check if you have added the `android_ndk_repository` and `android_sdk_repository` to WORKSPACE file as suggested in the documentation [here](https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel).
You can manually add it as well. Sample is given below:
```
android_sdk_repository(name = "androidsdk", api_level=33, build_tools_version="30.0.3")
android_ndk_repository(name = "androidndk", api_level=21)
```

**Comment by dharmeshdevstree** [comment] 2022-12-13 06:02
> Hi @dharmeshdevstree Can you please check if you have added the `android_ndk_repository` and `android_sdk_repository` to WORKSPACE file as suggested in the documentation [here](https://google.github.io/mediapipe/getting_started/android.html#building-android-example-apps-with-bazel). You can manually add it as well. Sample is given below:
> 
> ```
> android_sdk_repository(name = "androidsdk", api_level=33, build_tools_version="30.0.3")
> android_ndk_repository(name = "androidndk", api_level=21)
> ```

![image](https://user-images.githubusercontent.com/86298602/207238824-f77cc927-c429-404d-9894-351b04c8e176.png)
Yes already added @ayushgdev

**Comment by ayushgdev** [comment] 2022-12-13 07:18
Okay. Can you please provide the **_exact_** steps from the beginning you followed for the setup so that we can recreate the issue at our end as well?

**Comment by dharmeshdevstree** [comment] 2022-12-13 08:31
Thanks for reply,
1. I clone this repo in my system then import project using bazel.
2. I setup WORKPLACE with add sdk and ndk directory path.(I downloaded android-ndk-r21b-linux-x86_64 ndk and setup this directory in WORKPLACE)
3. i tried to installed facemesh app using terminal command. Its successfully installed on my device. When i click on Start Camera at that moment getting above error
/data/user/0/com.google.mediapipe.examples.facemesh/incrementallib/libmediapipe_jni.so" is 32-bit instead of 64-bit.

FYI 
Android Studio Dolphin | 2021.3.1 Patch 1
My system configuration Ubuntu 20.02 64 bit.

**Comment by ayushgdev** [comment] 2022-12-16 06:17
Hi @dharmeshdevstree 
Thank you for providing the details. The file for r21 release is not available in the r[elease history](https://developer.android.com/ndk/downloads/revision_history) for download now. So we reproduced with the closest version available i.e. r21eLTS. Unfortunately, we were not able to reproduce the issue at our end. 
As a workaround, would you please try downloading NDK from within the Android Studio itself? Try the v21.1.6352462 first.

**Comment by dharmeshdevstree** [comment] 2022-12-19 07:13
Error:(7, 15) Building abc/libmain.jar (7 source files) and running annotation processors (AutoValueProcessor, AutoBuilderProcessor) failed: (Exit 1): java failed: error executing command external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 17 arguments skipped)


Error:(71, -1) cannot access MessageLiteOrBuilder
Error:(71, -1) cannot access Parser
Error:(77, -1) cannot access GeneratedMessageLite


Getting this error 
![image](https://user-images.githubusercontent.com/86298602/208368246-54037ec5-f9e0-468f-880f-c234c22d5848.png)


Hello,
I am getting this error related to AutoValueProcessor 
Anyone have an idea it's appriciable.
Thanks

**Comment by ayushgdev** [comment] 2022-12-19 10:21
Hi @dharmeshdevstree 
The Bazel version supported by MediaPipe is 5.2.0. Please consider using [Bazelisk](https://github.com/bazelbuild/bazelisk) which will automatically take care of the bazel version to use within the MediaPipe workspace. 
Also, would you please advice what changes did you do to resolve the original error of `"...libmediapipe_jni.so" is 32-bit instead of 64-bit.` ?

**Comment by dharmeshdevstree** [comment] 2022-12-19 10:28
Hello
Thanks for reply.
Let me try with Bazel version 5.2.0 and let you know.
Some mavel remove from build folder and version change and it's working.

Thanks

**Comment by dharmeshdevstree** [comment] 2022-12-19 11:50
Hi @ayushgdev 
I am not able to download Bazel version 5.2.0 
sudo apt-get install bazel when i used this command it's always installed 5.4.0 version
Any specific comman for that?

**Comment by ayushgdev** [comment] 2022-12-20 06:58
Hi @dharmeshdevstree Please use bazelisk tool. It is like NVM in node world. It manages the bazel version automatically based on the version specified in .bazelversion file. You can install bazelisk from [here](https://github.com/bazelbuild/bazelisk).

**Comment by dharmeshdevstree** [comment] 2022-12-20 08:04
Hello @ayushgdev 
i installed this version on my system and still getting same error.

Building abc/libmain.jar (7 source files) and running annotation processors (AutoValueProcessor, AutoBuilderProcessor) failed: (Exit 1): java failed: error executing command (from target //abc) external/remotejdk11_linux/bin/java -XX:-CompactStrings '--add-exports=jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED' '--add-exports=jdk.compiler/com.sun.tools.javac.main=ALL-UNNAMED' ... (remaining 16 arguments skipped)

![image](https://user-images.githubusercontent.com/86298602/208614402-880f8407-09ee-4988-9cfb-99691f5176f9.png)

Please let me know if anything need to change.
Thanks

**Comment by ayushgdev** [comment] 2022-12-20 08:48
@dharmeshdevstree Can you please try the changes provided in this [comment](https://github.com/google/mediapipe/issues/1679#issuecomment-788323387)? 
As a side note on the `bazel version` command, you need to execute that inside the mediapipe repo clone because the .bazelversion file is located there for bazelisk to read.

**Comment by dharmeshdevstree** [comment] 2022-12-20 09:58
Hi @ayushgdev 

i used https://github.com/google/mediapipe this repo and i generated AAR solution_core.aar
bazel build --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/java/com/google/mediapipe/solutioncore:solution_core
using this command in above repo i used to generate aar file.
This AAR file i used in my current sample project.

FYI
i tried solution-core-0.8.11-alpha-1.aar file from maven mediapipe. but hard luck and it's getting above error.

Please help on this
Thanks

**Comment by ayushgdev** [comment] 2022-12-20 10:18
Hi @dharmeshdevstree 
I can see there is another issue #3934  opened for this specific error. Please follow up on that issue. We will be closing this issue.

**Closed by ayushgdev** 2022-12-20 10:18 UTC
Labels: type:support, platform:android, solution:face mesh
