### ISSUE TITLE
how to publish the facial landmarks in ros?

### ISSUE THREAD

**Issue by flydragon2018** [google/mediapipe#4233] opened 2023-04-02 11:38 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

ubuntu 20.04

### MediaPipe version

0.8.1

### Solution

facemesh

### Programming Language and version

python 3.8

### Describe the actual behavior

```shell
Are the landmarks detected in same order as the labelled graph?

what is the center of head?

what kind of data type needed to publish the detected landmarks?

Thanks for your reply.
```

**Comment by flydragon2018** [comment] 2023-04-03 08:49
I worked it out to publish the detected landmarks.

The only thing remains confused is about the Z value.
The document only states that It is with respect to the center of head.

I got other saying that It is the average of head( or face)  average depth as reference ??

**Comment by kuaashish** [comment] 2023-04-03 09:30
@flydragon2018,
Could you please elaborate your query with more details. Thank you!

**Comment by flydragon2018** [comment] 2023-04-04 15:46
x y z face landmarks.  the x, y are normalized with respect to image width and height,  while the z value is not with respect to the center of head as origin 0.

**Comment by kuaashish** [comment] 2023-04-27 06:56
Closing this issue as Duplicate of #4193, Please follow up with another issue raised

**Closed by kuaashish** 2023-04-27 06:56 UTC
Labels: type:support, solution:face mesh, platform:python
