### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement mediapipe ERROR: No matching distribution found for mediapipe

### ISSUE THREAD

**Issue by faijan22** [google/mediapipe#1906] opened 2021-04-19 09:51 UTC
my current version for python is 3.8.2 , i tired pip install mediapipe didnt worked , also tried using git , easy , --user , running as administrator but nothing worked. can you please tell me how to install it ?

**Comment by sgowroji** [comment] 2021-04-19 09:57
Hi @faijan22, Could you please share your error and what are the steps performed to reproduce it. Thanks!

**Comment by faijan22** [comment] 2021-04-19 10:00
yes sir, 

C:\Users\HP>pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe
ERROR: No matching distribution found for mediapipe

and some other stackoverflow answers, sir.

**Comment by sgowroji** [comment] 2021-04-19 10:10
Please have a look at this https://github.com/google/mediapipe/issues/1674#issuecomment-788295898. Seems duplicate of your issue.

**Comment by faijan22** [comment] 2021-04-19 12:49
(env_mediapipe) PS C:\Users\HP\Desktop\python openecv> pip install mediapipe
Collecting mediapipe
  ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
WARNING: You are using pip version 19.2.3, however version 21.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

**Comment by faijan22** [comment] 2021-04-19 12:49
sir I created venv -  inside that i tried to install above error i faced .
can you please guide me from start to end ...

**Comment by faijan22** [comment] 2021-04-19 13:13
it worked i uninstalled my current python version 3.8.2 and installed 3.7 and then  created venv and tried to install and it worked

**Comment by sgowroji** [comment] 2021-04-19 15:09
We are glad to know your issue resolved. So closing this ticket. Thanks

**Closed by sgowroji** 2021-04-19 15:09 UTC
Labels: MediaPipe, platform:python, stat:awaiting response, type:support

**Comment by g-o-o-g-l-e** [comment] 2024-02-21 07:50
I got PS C:\Users\happypeople\PycharmProjects\1stPrj> pip install mediapipe
ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)
ERROR: No matching distribution found for mediapipe
