### ISSUE TITLE
mediapipeとarcoreをbazelでビルドする方法

### ISSUE THREAD

**Issue by hibiking-0422** [google/mediapipe#1669] opened 2021-02-27 07:42 UTC
# 質問内容
**mediapipeのobjectronとarcoreを使うため、arcoreをbazelでビルドしたいのですが方法がわかりません。**
arcoreをbazelでビルドする方法を知っている方、もしくわ他にmediapipeとarcoreを共存させる方法を知っている方はいらっしゃるでしょうか？

# 参考リンク
[mediapipe公式サイト](https://mediapipe.dev/#!)
[mediapipe objectronの概要](https://google.github.io/mediapipe/solutions/objectron)

**Comment by rmothukuru** [comment] 2021-03-01 08:13
@hibiking-0422,
We couldn't understand what the issue is. Can you please use English Language to describe your issue? Thanks!

**Comment by mzwtjp** [comment] 2021-03-03 02:09
He says as follows.

I am not sure how to build arcore using bazel, in order to use mediapipe's objectron together with arcore.
Anybody knows how to build arcore using bazel?  And/or how to let mediapipe and arcore co-exit?

**Comment by sgowroji** [comment] 2021-04-15 07:58
Hi @hibiking-0422, Have a look at this issue https://github.com/google/mediapipe/issues/583#issuecomment-609919618

**Comment by sgowroji** [comment] 2021-04-21 06:38
Hi @hibiking-0422, Did you get a chance to go through the above comments. Thanks!

**Comment by sgowroji** [comment] 2021-04-26 06:07
Assuming you are resolved with the above comment. We are closing this ticket. Thanks!

**Closed by sgowroji** 2021-04-26 06:07 UTC
Labels: platform:bazel, solution:objectron, stat:awaiting response, type:build/install, type:feature
