### ISSUE TITLE
How to make shoes obj.uuu file

### ISSUE THREAD

**Issue by z7212819** [google/mediapipe#1433] opened 2020-12-25 07:14 UTC
Excuse me, the object detection has been changed to footwear try on, but I don't know how to change my own shoe model to obj.uuu Format, is there any way?

**Comment by wanghaichuan941221** [comment] 2020-12-28 02:13
@z7212819  Did you manage to change the footwear? If so, can you tell me how.

**Comment by hadon** [comment] 2021-02-05 23:40
Does this issue refer to 3D object tracking, "Objectron"?

**Comment by tyrmullen** [comment] 2021-02-14 00:37
Yes, the .uuu format was created to condense all the necessary geometry for OpenGL 3D rendering into a simple binary blob.  For more details, please see https://github.com/google/mediapipe/issues/1074, which I believe is a duplicate of this.  Closing for now as duplicate.

**Closed by tyrmullen** 2021-02-14 00:37 UTC
Labels: model, tracking
