### ISSUE TITLE
[Android] How can I remove a shape?

### ISSUE THREAD

**Issue by seoungbin0125** [google/mediapipe#3958] opened 2022-12-28 09:44 UTC
<em>Please make sure that this is a build/installation issue and also refer to the [troubleshooting](https://google.github.io/mediapipe/getting_started/troubleshooting.html) documentation before raising any issues.</em>

**System information** (Please provide as much relevant information as possible)

- [MediaPipe version] lastest release version
- Android SDK and NDK versions (if android):
- Android AAR

**Describe the problem**:

I want to remove the displayed shapes in the picture below.
![image](https://user-images.githubusercontent.com/67889670/209791942-373baab5-7c4e-47c7-8a99-50fe5afa7f28.png)

**Comment by ayushgdev** [comment] 2022-12-29 06:00
Marking this as a duplicate of #3956 and closing the issue. @seoungbin0125  Please follow up on this requirement on #3956 .

**Closed** 2022-12-29 06:01 UTC
Labels: status:duplicate, type:build/install, platform:android, solution:hands

**Comment by asthagarg2428** [comment] 2023-01-06 11:37
@seoungbin0125 How are you drawing these lines on camerx preview?
