### ISSUE TITLE
error when bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world

### ISSUE THREAD

**Issue by bianxg** [google/mediapipe#1200] opened 2020-10-14 08:28 UTC
Linux version 4.4.0-184-generic (buildd@lgw01-amd64-060) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) ) #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020

bazel --version
bazel 3.0.0- (@non-git)

git log 
commit cccf6244d3fc4afc53082a397e764a8560eec96e
Author: MediaPipe Team <mediapipe-team@google.com>
Date:   Mon Sep 28 00:50:43 2020 -0400

bazel run --define MEDIAPIPE_DISABLE_GPU=1     mediapipe/examples/desktop/hello_world:hello_world
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f358144776d3dfc5a928ef32a0e4fbe93c99b55772d70cca77a6478e34d96aa7"
DEBUG: Call stack for the definition of repository 'rules_foreign_cc' which is a http_archive (rule definition at /home/test/.cache/bazel/_bazel_test/c7e025c0f98ebd567eb2397aa5ae0c51/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /home/test/project/mediapipe/WORKSPACE:39:1
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
INFO: SHA256 (https://github.com/bazelbuild/rules_cc/archive/master.zip) = e1b6d845f9473ececdfb8dbd8c4c18e0339f4e6a45c4aa52e6a265e6f5040933
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e1b6d845f9473ececdfb8dbd8c4c18e0339f4e6a45c4aa52e6a265e6f5040933"
DEBUG: Call stack for the definition of repository 'rules_cc' which is a http_archive (rule definition at /home/test/.cache/bazel/_bazel_test/c7e025c0f98ebd567eb2397aa5ae0c51/external/bazel_tools/tools/build_defs/repo/http.bzl:296:16):
 - <builtin>
 - /home/test/project/mediapipe/WORKSPACE:33:1
ERROR: /home/test/.cache/bazel/_bazel_test/c7e025c0f98ebd567eb2397aa5ae0c51/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl:28:21: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/test/.cache/bazel/_bazel_test/c7e025c0f98ebd567eb2397aa5ae0c51/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /home/test/.cache/bazel/_bazel_test/c7e025c0f98ebd567eb2397aa5ae0c51/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 557.604s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (2 packages loaded, 0 targets configured)

**Comment by nnrtgt** [comment] 2020-10-15 04:19
I am also facing same Issue:
 bazel run --define MEDIAPIPE_DISABLE_GPU=1 \
>     mediapipe/examples/desktop/hello_world:hello_world
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "f358144776d3dfc5a928ef32a0e4fbe93c99b55772d70cca77a6478e34d96aa7"
DEBUG: Repository rules_foreign_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_z063159/0026028b5e9993b7608bc8050bc675a7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from http://mirror.tensorflow.org/github.com/bazelbuild/rules_closure/archive/cf1e44edb908e9616030cc83d085989b8e6cd6df.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException GET returned 404 Not Found
DEBUG: Rule 'rules_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "e1b6d845f9473ececdfb8dbd8c4c18e0339f4e6a45c4aa52e6a265e6f5040933"
DEBUG: Repository rules_cc instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule http_archive defined at:
  /private/var/tmp/_bazel_z063159/0026028b5e9993b7608bc8050bc675a7/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: /private/var/tmp/_bazel_z063159/0026028b5e9993b7608bc8050bc675a7/external/rules_cc/cc/private/rules_impl/cc_flags_supplier.bzl:28:25: rule() got unexpected keyword argument 'incompatible_use_toolchain_transition'
ERROR: While resolving toolchains for target //mediapipe/examples/desktop/hello_world:hello_world: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /private/var/tmp/_bazel_z063159/0026028b5e9993b7608bc8050bc675a7/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
ERROR: Analysis of target '//mediapipe/examples/desktop/hello_world:hello_world' failed; build aborted: com.google.devtools.build.lib.packages.BuildFileContainsErrorsException: error loading package '@bazel_tools//tools/cpp': in /private/var/tmp/_bazel_z063159/0026028b5e9993b7608bc8050bc675a7/external/rules_cc/cc/defs.bzl: Extension file 'cc/private/rules_impl/cc_flags_supplier.bzl' has errors
INFO: Elapsed time: 0.097s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)

**Comment by jiuqiant** [comment] 2020-10-15 15:35
Due to a recent change on the Bazel side, rules_foreign_cc is removed. The solution is to switch to use Bazel 3.4+. I verified the fix in the Docker container. See details at https://github.com/google/mediapipe/issues/1175#issuecomment-704524129.

**Comment by jiuqiant** [comment] 2020-10-15 15:38
Due to a recent change on the Bazel side, "rules_foreign_cc" is not available anymore. The solution is to switch to use Bazel 3.4+. I verified the fix in the Docker container. See details at https://github.com/google/mediapipe/issues/1175#issuecomment-704524129. MediaPipe will have a new version out this week to ask users to at least have Bazel 3.4+.

**Comment by nnrtgt** [comment] 2020-10-15 17:07
Thank you, hope this works fine on Mac

**Closed** 2020-10-16 00:54 UTC

**Comment by mstfabbstbr** [comment] 2021-08-14 09:47
same problem with bazel 3.7.2
