### ISSUE TITLE
error when re-run the hand-tracking project

### ISSUE THREAD

**Issue by ChuyiZhong** [google/mediapipe#427] opened 2020-02-03 09:33 UTC
I used to run the hand-tracking project successfully a month ago.
I tried to re-run it today but an error showed up:
dyld: Library not loaded: /usr/local/opt/ilmbase/lib/libImath-2_3.24.dylib
  Referenced from: /usr/local/opt/opencv@3/lib/libopencv_imgcodecs.3.4.dylib
  Reason: image not found
Abort trap: 6
I am using MacOS CPU.
All help are appreciated.

**Comment by mcclanahoochie** [comment] 2020-02-05 05:08
duplicate of https://github.com/google/mediapipe/issues/431

**Closed by mcclanahoochie** 2020-02-05 05:08 UTC
