### ISSUE TITLE
(Javascript) Hand Track on Android Chrome throws RuntimeError.

### ISSUE THREAD

**Issue by ajmalrasi** [google/mediapipe#1459] opened 2021-01-02 20:07 UTC
I'm trying to run Hand Track on Chrome 87.0.42, running on Samsung S8 with Exynos 8895 soc. it works fine on PC but stuck at the loading screen on mobile.

Here is the console log.

> RuntimeError: abort(undefined) at Error
    at jsStackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:67549)
    at stackTrace (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:67725)
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:41039)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:179943)
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:41070)
    at _abort (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:179943)
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10471]:0x49a300
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10466]:0x49a278
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10461]:0x499da0
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10458]:0x499a2a
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[10474]:0x49a359
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[515]:0xebe1
    at https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.wasm:wasm-function[502]:0xd956
    at SolutionWasm$send [as send] (eval at new_ (https://cdn.jsdelivr.net/npm/@mediapipe/hands/hands_solution_wasm_bin.js:9:160446), <anonymous>:9:1)

**Comment by MIDIBlocks** [comment] 2021-01-04 04:49
Hi I'm also experiencing this with the latest release on Android/Chrome and two others have reported this to me as well. It seems to be limited to just the Hands model (Facemesh, Holistic, and Pose works). Can also confirm that it works fine on desktop in all browsers

**Comment by Adolar13** [comment] 2021-01-06 16:44
Can confirm chrome not working on android but working in firefox.

**Comment by simon-lanf** [comment] 2021-03-16 03:57
@ajmalrasi @MIDIBlocks @Adolar13 could you go to chrome://version/ on chrome android and tell me if you have the 32bit version or 64bit ? Chrome was just released as 64bit for the first time with 89 for android 10 with 8gb of ram: https://www.ghacks.net/2021/03/13/google-is-pushing-64-bit-chrome-on-android/

I can reproduce the error on 32bit chrome android but on 64but chrome android it works 100%. Let me know if you can reproduce on 64bit or not.

**Comment by sgowroji** [comment] 2021-05-27 08:04
Hi @ajmalrasi, Could you please share the issue status?

**Comment by sgowroji** [comment] 2021-06-08 06:50
Hi @ajmalrasi, Could you please respond to my above [comment](https://github.com/google/mediapipe/issues/1459#issuecomment-849427107). Thanks!

**Comment by ajmalrasi** [comment] 2021-06-08 09:23
@sgowroji Just tested on Samsung S8, i can confirm that the issue is resolved.

**Closed** 2021-06-09 07:09 UTC
Labels: platform:javascript, solution:hands

**Comment by Amrit9939** [comment] 2021-09-16 15:54
i get this issue in chrome. how can i resolve it. thanku
