### ISSUE TITLE
Hand wasm javascript api is not laoding on mobile devices(getting dimensions and wasm error)

### ISSUE THREAD

**Issue by vasanthhr** [google/mediapipe#1430] opened 2020-12-24 09:19 UTC
Hand's 21 keypoints wasm javascript api is not loading on mobile devices, we getting console log errors as dimensions out of range  and wasm abort run-time error.

We tried to load this url on mobile chrome and safari browser(but it didn't work on mobile browsers): https://code.mediapipe.dev/codepen/hands 

Please find below screenshot ( debugged on mobile device).

![image](https://user-images.githubusercontent.com/20619142/103076928-cd821080-459c-11eb-89e8-a88df225b5d3.png)

**Comment by Ankit-Gupta-1511** [comment] 2020-12-24 10:56
I am also facing the same issue

**Comment by djthegr8** [comment] 2020-12-26 11:36
> dimensions out of range
Could this be due to too less RAM available to GL?

**Comment by Ankit-Gupta-1511** [comment] 2020-12-26 11:38
> > dimensions out of range
> 
> Could this be due to too less RAM available to GL?

No, I tested on an 8gb ram device. So, I think this is something else.

**Comment by djthegr8** [comment] 2020-12-26 11:39
GPU memory?

**Comment by hadon** [comment] 2021-02-05 23:43
I'll also mention contributor @tyrmullen, who may have more insight on this limitation.

**Comment by tyrmullen** [comment] 2021-02-06 02:40
This is due to that particular ML graph not being able to run yet on Android Chrome.  Our initial release was heavily targeting Desktop Chrome, so while it's great to hear that it already runs on Safari (which makes me curious if it runs on iOS too), it's not too surprising that other platforms ran into some problems.  This is something we'll have to look into.

From the error message, it appears the specific issue here is a WebGL numeric argument being out of bounds (likely exceeding the limits) for the given device.  I suspect the other errors/warnings are just a result of this.

**Comment by afogel** [comment] 2021-02-10 21:34
is this related to #1600 ? @tyrmullen

**Comment by tyrmullen** [comment] 2021-02-10 23:30
@afogel No, that looks like a different issue, specifically a problem in the graph construction (or one of the dependency subgraphs), which should hopefully be much easier to fix than this.

**Comment by simon-lanf** [comment] 2021-03-16 03:55
@Ankit-Gupta-1511 @vasanthhr could you go to chrome://version/ on chrome android and tell me if you havr the 32bit version or 64bit ? Chrome was just released as 64bit for the first time with 89 for android 10 with 8gb of ram: https://www.ghacks.net/2021/03/13/google-is-pushing-64-bit-chrome-on-android/

I can reproduce the error on 32bit chrome android but on 64but chrome android it works 100%.

**Comment by sgowroji** [comment] 2021-08-23 07:01
Please go through this for the supported [platforms](https://google.github.io/mediapipe/getting_started/javascript.html#supported-plaforms)

**Closed by sgowroji** 2021-08-23 07:01 UTC
Labels: platform:web, stat:awaiting response, platform:javascript

**Comment by mhays-google** [comment] 2021-08-23 16:12
Due to limitations in our inference engine implementation, we unfortunately
only support 64 bit at this time.
