### ISSUE TITLE
Cannot access HAND_CONNECTIONS to draw connectors line in hand landmark detection

### ISSUE THREAD

**Issue by cosmo3769** [google/mediapipe#4174] opened 2023-03-14 01:49 UTC
### OS Platform and Distribution

* macOS Ventura Version 13.2.1

### Task name 

* Hand Landmark Detection

### Tech Stack

* React.js

### Describe the actual behavior

I am integrating mediapipe task solution (Hand Landmark Detection) in a react web application. I am using @mediapipe/tasks-vision for the task. Everything is working fine except this one: 

```
if (results.landmarks) {
   for (const landmarks of results.landmarks) {
       drawConnectors(canvasCtx, landmarks, HAND_CONNECTIONS, {
       color: "#00FF00",
       lineWidth: 5
       });
       drawLandmarks(canvasCtx, landmarks, { color: "#FF0000", lineWidth: 2 });
   }
}
```

In the code given above, I am getting this error: 

```
Unhandled Promise Rejection: ReferenceError: Can't find variable: HAND_CONNECTIONS
```

Due to this error, only the landmarks(here red dots) are showing but the hand landmarks are not connected with each other(here it should be green lines). 

In the package (@mediapipe/tasks-vision), I don't find a way to import HAND_CONNECTIONS.

### Describe the expected behaviour

While searching through the solution, I find that we can import HAND_CONNECTIONS from the previous package (@mediapipe/hands). As a result, the hand landmarks are connected with each other forming lines.

### Steps to reproduce 

Here is the GitHub repo: https://github.com/cosmo3769/handlandmark-detection-mediapipe-react

To reproduce,

* install node
* run npm install
* run npm start

**Comment by ayushgdev** [comment] 2023-03-14 10:36
Hello @cosmo3769 
Thanks for raising this issue. We are able to reproduce it at our end. Our demos also use the legacy solutions' hands package to draw the connections. We shall discuss it internally on this and try to integrate it in the tasks API soon, but cannot comment on the timeline.
For now, we have classified it as a bug.

**Comment by cosmo3769** [comment] 2023-03-14 12:13
Okay, sure.

**Comment by ayushgdev** [comment] 2023-03-28 04:26
@schmidt-sebastian Can you please take a look at this issue?

**Comment by kuaashish** [comment] 2023-09-28 09:18
@cosmo3769,

We are revisiting to the older issues, This feature has been added [here](https://github.com/google/mediapipe/tree/v0.10.5/mediapipe/tasks/web/vision/hand_landmarker). Would you kindly confirm and inform us if the issue is no longer pertinent from your perspective? Upon your confirmation, we can proceed to mark it as resolved and proceed with its closure. Thank you

**Comment by cosmo3769** [comment] 2023-10-06 10:48
Hi @kuaashish, I checked it. It is working perfectly fine. Thank you for the nice work. Here is my GitHub repo where I checked the implementation: [Handlandmark detection using mediapipe and react](https://github.com/cosmo3769/handlandmark-detection-mediapipe-react).

**Comment by kuaashish** [comment] 2023-10-06 10:56
@cosmo3769,

Thank you for your confirmation, Could you please let us know if now this is no longer issue from your end, Can we move ahead and mark the issue status resolved and close it.

**Comment by cosmo3769** [comment] 2023-10-06 10:57
Yes, surely. We can close it. @kuaashish

**Closed** 2023-10-06 10:58 UTC
Labels: legacy:hands, platform:javascript, type:bug, type:tasks
