### ISSUE TITLE
Access variable outside processor.addPacketCallback

### ISSUE THREAD

**Issue by nitin26gupta** [google/mediapipe#1151] opened 2020-09-27 04:51 UTC
I declared, global variable 'left_iris_depth' 
public static float left_iris_depth;
Then assigned value to this variable in processor.addPacketCallback

processor.addPacketCallback(
                LEFT_IRIS_DEPTH_MM,
                (packet) -> {
                    left_iris_depth = PacketGetter.getFloat32(packet);
                    Log.v(TAG,"left depth in cm is: " + left_iris_depth/10);
                });

but when i try to access this variable outside it gives value as 0 only and not the value assigned inside processor.addPacketCallback

So how could I access the variable values outside processor.addPacketCallback?

**Comment by hadon** [comment] 2021-01-22 18:29
I think the overall design here is correct.  The static variable should contain a value assigned during a recent callback.  A few things to watch out for: 

(1) thread synchronization: unless the callback thread and the thread reading the global variable are synchronized in some way, changes to the global variable may not appear consistent between the two threads.  Marking the global variable as "volatile" would ensure more consistency between threads.  

(2) extra callbacks: if the callback is called multiple times, maybe even in parallel, it may overwrite the variable and hide some values that you expect to see.  

(3) shadowing: maybe there is a local variable somehow shadowing the global variable.  

(4) class loaders: maybe there are multiple copies of the global variable caused by multiple class loaders.

**Comment by hadon** [comment] 2021-03-20 00:31
Closing this issue for now. Feel free to re-open it if more responses are needed.

**Closed by hadon** 2021-03-20 00:31 UTC
Labels: platform:android
