### ISSUE TITLE
Converting UIImage Into CVPixelBuffer and Feeding Into MediaPipe Face Mesh Returns No Result

### ISSUE THREAD

**Issue by waleedbaroudi** [google/mediapipe#4229] opened 2023-03-31 14:14 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

No

### OS Platform and Distribution

iOS 13.0

### Bazel version

5.2.0

### Solution

FaceMesh

### Programming Language and version

C++, Swift

### Describe the actual behavior

The functions
`startGraph()`
`processVideoFrame(frame)`
pass with no errors, the delegate is set, but the delegate functions are not triggered.

### Describe the expected behaviour

Expected the function 
```c++
- (void)mediapipeGraph:(MPPGraph*)graph
       didOutputPacket:(const ::mediapipe::Packet&)packet
            fromStream:(const std::string&)streamName {
 ...
}
```
to be reached but it was not.

### Standalone code/steps you may have used to try to get what you need

1. Get the image as a UIImage: `UIImage(named:"image_name")`
2. Convert the UIImage into a CVPixelBuffer using the following extension:

```swift
extension UIImage {
   
    func toPixelBuffer() -> CVPixelBuffer? {
        let attrs = [kCVPixelBufferCGImageCompatibilityKey: kCFBooleanTrue, kCVPixelBufferCGBitmapContextCompatibilityKey: kCFBooleanTrue] as CFDictionary
        var pixelBuffer : CVPixelBuffer?
        let status = CVPixelBufferCreate(kCFAllocatorDefault, Int(size.width), Int(size.height), kCVPixelFormatType_32ARGB, attrs, &pixelBuffer)
        guard (status == kCVReturnSuccess) else {
          return nil
        }

        CVPixelBufferLockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))
        let pixelData = CVPixelBufferGetBaseAddress(pixelBuffer!)

        let rgbColorSpace = CGColorSpaceCreateDeviceRGB()
        let context = CGContext(data: pixelData, width: Int(size.width), height: Int(size.height), bitsPerComponent: 8, bytesPerRow: CVPixelBufferGetBytesPerRow(pixelBuffer!), space: rgbColorSpace, bitmapInfo: CGImageAlphaInfo.noneSkipFirst.rawValue)

        context?.translateBy(x: 0, y: size.height)
        context?.scaleBy(x: 1.0, y: -1.0)

        UIGraphicsPushContext(context!)
        draw(in: CGRect(x: 0, y: 0, width: size.width, height: size.height))
        UIGraphicsPopContext()
        CVPixelBufferUnlockBaseAddress(pixelBuffer!, CVPixelBufferLockFlags(rawValue: 0))

        return pixelBuffer
    }
}
```
3. Setup FaceMesh:

```swift
faceMesh = FaceMesh()
faceMesh.startGraph()
faceMesh.delegate = self
```

4. Feed the pixel buffer (from step 2) into Mediapipe FaceMesh:

```swift
if let frame = image.toPixelBuffer() {
    lastFrameBuffer = frame
    faceMesh.processVideoFrame(frame)
}
```

5. The frame passes into this function:
```c++
- (void)processVideoFrame:(CVPixelBufferRef)imageBuffer {
    NSLog(@"[FACEMESH] Processing Video Frame %@", kGraphName);
    const auto ts =
    mediapipe::Timestamp(self.timestamp++ * mediapipe::Timestamp::kTimestampUnitsPerSecond);
    NSError* err = nil;
    BOOL sent = [self.mediapipeGraph sendPixelBuffer:imageBuffer
                                          intoStream:kInputStream
                                          packetType:MPPPacketTypePixelBuffer
                                           timestamp:ts
                                      allowOverwrite:NO
                                               error:&err];
    NSLog(@"[FACEMESH] Sent? %d", sent);
    if (err == nil) {
        NSLog(@"[FACEMESH] NO ERROR");
    } else {
        NSLog(@"[FACEMESH] ERROR: %@",[err localizedDescription]);
    }
}
```

6. Observe logs:
```
[FACEMESH] inited graph pure_face_mesh_mobile_gpu
[FACEMESH] Started graph pure_face_mesh_mobile_gpu
[FACEMESH] Processing Video Frame pure_face_mesh_mobile_gpu
[FACEMESH] Sent? 1
[FACEMESH] NO ERROR
```

**Comment by kuaashish** [comment] 2023-04-05 07:01
Hello @waleedbaroudi,
Would you please let us know the complete steps you have followed, standalone code to reproduce the issue and look into this in detailed manner? Thank you

**Comment by waleedbaroudi** [comment] 2023-04-05 13:02
Hi @kuaashish, the steps and code are exactly as mentioned in the issue, and in that given order. Which part would you like me to clarify?

**Comment by nguyencse** [comment] 2023-05-28 16:07
@waleedbaroudi  Because `processVideoFrame`  use `kCVPixelFormatType_32BGRA`. So you need to create CVPixelBuffer with format`kCVPixelFormatType_32ARGB` to fit input of this func

**Comment by schmidt-sebastian** [comment] 2024-03-15 18:42
Closing due to in-activity. Please re-open if necessary.

**Closed by schmidt-sebastian** 2024-03-15 18:42 UTC
Labels: type:support, platform:ios, legacy:face mesh, platform:c++, stat:awaiting googler
