### ISSUE TITLE
Weird output of ImageTransformationCalculator for certain output_width and output_height

### ISSUE THREAD

**Issue by yxchng** [google/mediapipe#712] opened 2020-05-12 03:19 UTC
- Graph for resizing image to 540x540

```
input_stream: "input_video"
output_stream: "output_video"
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:transformed_input_video_cpu"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 540
      output_height: 540
      scale_mode: STRETCH
    }
  }
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "transformed_input_video_cpu"
  output_stream: "output_video"
}

```

- Output

![IMG_2248](https://user-images.githubusercontent.com/10518587/81634760-2c49ae00-9442-11ea-9182-11b714ded851.JPG)

- Graph for resizing image to 541x541

```
input_stream: "input_video"
output_stream: "output_video"
node {
  calculator: "FlowLimiterCalculator"
  input_stream: "input_video"
  input_stream: "FINISHED:output_video"
  input_stream_info: {
    tag_index: "FINISHED"
    back_edge: true
  }
  output_stream: "throttled_input_video"
}
node: {
  calculator: "GpuBufferToImageFrameCalculator"
  input_stream: "throttled_input_video"
  output_stream: "input_video_cpu"
}
node: {
  calculator: "ImageTransformationCalculator"
  input_stream: "IMAGE:input_video_cpu"
  output_stream: "IMAGE:transformed_input_video_cpu"
  output_stream: "LETTERBOX_PADDING:letterbox_padding"
  node_options: {
    [type.googleapis.com/mediapipe.ImageTransformationCalculatorOptions] {
      output_width: 541
      output_height: 541
      scale_mode: STRETCH
    }
  }
}
node: {
  calculator: "ImageFrameToGpuBufferCalculator"
  input_stream: "transformed_input_video_cpu"
  output_stream: "output_video"
}

```

- Output

![IMG_2247](https://user-images.githubusercontent.com/10518587/81634746-248a0980-9442-11ea-921a-09efaefd8299.JPG)

I do not change anything from MediaPipe. The code is freshly pulled from Github. I printed out the input size and it is 1080x1080 (should different for different phone). When resizing to 540x540, the output looks normal. But when resizing to 541x541, the output is ridiculous!

**Comment by yxchng** [comment] 2020-05-12 05:56
I have done more experiments and this phenomenon only occurs when resizing is done on CPU. It is fine when resizing is done on GPU.

**Comment by Cubbee** [comment] 2020-06-01 16:29
Hi, I've encountered similar issue on device with Android 9.0. I've spent quite a lot of time debugging, because my graph worked fine on Android 8, but broke after update.

The issue is also with ImageTransformationCalculator, I'm using the same settings as you, but run it on GPU. Haven't found out yet which input sizes trigger the problem, will update later.

Just wanted to let maintainters know that the issue exists.

**Comment by tyrmullen** [comment] 2020-08-07 21:46
I think this is an image padding (/alignment) issue, causing a stride problem in the data.  For now, I would assume sizes where the width is a multiple of 4 should be fine (and occasionally, in rare circumstances, the width being a multiple of 16 may be helpful).

**Comment by RMiTiG** [comment] 2021-07-07 09:15
Same problem in my iphone while android is fine.In my case,the output_width/output_height aspect ratio must be 1:1, or broke.I have used the GPU

**Comment by sgowroji** [comment] 2021-07-26 05:25
Assuming the above issue resolved using this [comment](https://github.com/google/mediapipe/issues/712#issuecomment-670725425). We are closing this issue now.

**Closed by sgowroji** 2021-07-26 05:25 UTC
Labels: calculators, type:support
