### ISSUE TITLE
@mediapipe/tasks-vision 0.10.0 Pose landmarks is not returning visibility nor presence

### ISSUE THREAD

**Issue by hansen1416** [google/mediapipe#4479] opened 2023-05-29 05:26 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Windows10/Ubuntu20.04

### Browser and version if the issue happens on browser

Google chrome

### Programming Language and version

javascript

### Solution

Pose

### Describe the actual behavior

```shell
In the result callback, the items of landmarks and worldLandmarks only contain values of x, y, z coordinates. 
But according to https://developers.google.com/mediapipe/solutions/vision/pose_landmarker/web_js, there shoube be two more keys `visibility` and `presence`.
```

### Describe the expected behaviour

```shell
In the result callback, the items of landmarks and worldLandmarks should contain `visibility` and `presence`.
```

### Standalone code/steps you may have used to try to get what you need

```shell
Install "@mediapipe/tasks-vision": "^0.10.0" via npm. Download the models needed.


const createPoseLandmarker = async () => {
		const vision = await FilesetResolver.forVisionTasks(
			"/tasks-vision/wasm"
		);
		return await PoseLandmarker.createFromOptions(vision, {
			baseOptions: {
				modelAssetPath: `/tasks-vision/pose_landmarker_lite.task`,
				delegate: "GPU",
			},
			runningMode: "VIDEO",
			numPoses: 1,
			minPoseDetectionConfidence: 0.5,
			minPosePresenceConfidence: 0.5,
			minTrackingConfidence: 0.5,
			outputSegmentationMasks: false,
		});
	};

...

createPoseLandmarker().then((pose) => {
    poseDetector = pose;
});
...

poseDetector.detectForVideo(
    video,
    performance.now(),
    (res) => {
        console.log(res);
    }
);
```
```


### Other info / Complete Logs

_No response_

**Comment by kuaashish** [comment] 2023-05-29 11:09
Closing this as Duplicate of #4409. Please follow with already raised issue.

**Closed by kuaashish** 2023-05-29 11:09 UTC
Labels: platform:javascript, solution:pose, type:bug
