### ISSUE TITLE
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

### ISSUE THREAD

**Issue by gionlime** [google/mediapipe#3980] opened 2023-01-10 01:44 UTC
项目非常棒 有flutter版本吗？？The project is great. Is there a flutter version?

**Comment by kuaashish** [comment] 2023-01-10 05:14
Hi @gionlime,
Thanks for raising this feature request! we have already running this request #3922 and team sees this a great feature request for the larger community. Team will has already taken notes on this but can not provide any particular timeline.

**Comment by schmidt-sebastian** [comment] 2023-01-10 16:20
Closing as this is a duplicate of https://github.com/google/mediapipe/issues/3922

**Closed by schmidt-sebastian** 2023-01-10 16:20 UTC
Labels: type:feature, MediaPipe, stat:awaiting googler
