### ISSUE TITLE
Need clarification about the min_pose_presence_confidence in pose landmark detection

### ISSUE THREAD

**Issue by KrisHan999** [google/mediapipe#4856] opened 2023-10-05 20:49 UTC
### Have I written custom code (as opposed to using a stock example script provided in MediaPipe)

None

### OS Platform and Distribution

Ubuntu 18.04

### Task name (e.g. Image classification, Gesture recognition etc.)

Human Pose Landmark

### Programming Language and version (e.g. C++, Python, Java)

Python

### Describe the actual behavior

The min_pose_presence_confidence seems not work in the demo

### Describe the expected behaviour

Show different results with different setting

### Standalone code/steps you may have used to try to get what you need

```shell
When I pass the parameter to the PoseLandmarkOption, there is a `min_pose_presence_confidence` parameter, and I\'m not sure of the usage of this parameter. Then I tried the online demo https://mediapipe-studio.webapps.google.com/demo/pose_landmarker, and adjusted the `min_pose_presence_confidence`. The results are the same. 

I want to know:
1. Is this `min_pose_presence_confidence` applied on each landmark or the mean of all landmarks
2. What happens if the actual confidence is below `min_pose_presence_confidence`? What happens to the detection result for the frame? Will I still get the detected landmark results or not?
3. What exactly is the `min_pose_presence_confidence` used for?

Thanks
```

**Comment by kuaashish** [comment] 2023-10-10 09:12
Duplicate of #4859.

**Closed by kuaashish** 2023-10-10 09:12 UTC
Labels: status:duplicate, type:support, platform:python, task:pose landmarker, os:linux-non-arm
