### ISSUE TITLE
Mediapipe and Flask server

### ISSUE THREAD

**Issue by nikitatishin5** [google/mediapipe#1553] opened 2021-01-28 12:25 UTC
Everybody hi! I am trying to use Flask server and mediapipe together. Faced such a problem. When a picture from the front comes to the server, Hands modul starts and stops at self._graph.wait_until_idle (), which is located on the mediapipe / python / solution_base.py path. After calling this function, nothing else happens. Please help me figure it out. When i use it without Flask it works well.

**Comment by raghavgurbaxani** [comment] 2021-01-29 23:20
@nikitatishin5 @mhays-google @hadon 
I am also facing the same issue. Please suggest how to get around it.

**Comment by jiuqiant** [comment] 2021-01-30 00:54
What's the error message you see? Do you have the code to reproduce this issue?

**Comment by jiuqiant** [comment] 2021-01-30 00:56
We never tried to use MediaPipe with Flask. My first round of question are
- What's the error message you see? 
- Do you have the code to help us reproduce this issue?

**Comment by nikitatishin5** [comment] 2021-01-30 21:50
There is no any error. Its just stops. I just took code from CodePen for JS and from ready solution for Python Hand and made them work together. I rewrite function OnResult from JS code and made it to send Image to server via Flask-SocketIO. I could work for 3-4 times but then just stops.

**Comment by nikitatishin5** [comment] 2021-01-30 21:58
JS

`function sendPhoto(data){
if (ready_to_do)
{
    document.body.classList.add('loaded');
    fpsControl.tick();

  // Draw the overlays.
    canvasCtx.save();
    canvasCtx.clearRect(0, 0, canvasElement.width, canvasElement.height);
    canvasCtx.drawImage(
        data, 0, 0, canvasElement.width, canvasElement.height);
    var data_url = canvasElement.toDataURL();
    // console.log(data_url);
    console.log(data);
    console.log(startStop)
    if(startStop){
        socket.emit('my event', {data: data_url});
        ready_to_do = false
  }
    canvasCtx.restore();

    }
}
/**
 * Instantiate a camera. We'll feed each frame we receive into the solution.
 */
 const camera = new Camera(videoElement, {
  // onFrame: sendPhoto()
    onFrame: async () => {
    await sendPhoto(videoElement);
  },
    width: 1280,
    height: 720
});`


Python
`@socketio.on('my event')
def handle_my_custom_event(data):
    global i
    global fps_res
    global letters_stream
    cvimg = data_uri_to_cv2_img(data)
    print('raw_marks')
    raw_marks = get_marks(cvimg)
    print('raw_marks')
    if raw_marks:
        marks = split_marks(raw_marks)
        # print(marks)
        cur_letter = get_letter(marks)
        if fps_res > 0:
            letters_stream.append(cur_letter)
            fps_res -= 1
            # print('space')
        else:
            let_num_max = max(set(letters_stream),
                              key=letters_stream.count)
            fps_res = fps_max
            letters_stream = []
            letter = letters[let_num_max]
            print(letter)
            emit('response', letter)`

**Comment by jiuqiant** [comment] 2021-02-01 02:38
> There is no any error. Its just stops. I just took code from CodePen for JS and from ready solution for Python Hand and made them work together. I rewrite function OnResult from JS code and made it to send Image to server via Flask-SocketIO. I could work for 3-4 times but then just stops.

I am a little bit confused. Which API you use, MediaPipe Python or JavaScript?

From the code pasted here, it looks like you use the JavaScript API. But, you original question is about MediaPipe Python. Can you clarify? Thanks.

**Comment by nikitatishin5** [comment] 2021-02-01 07:31
As I said, I use JS just for taking Image and send it via socket. Python makes all calculations.

**Comment by jiuqiant** [comment] 2021-02-01 18:11
Hi, I made a simple flask example on macos and it looks ok to me.

My app.py:
```
from flask import Flask
import mediapipe as mp
import cv2

mp_pose = mp.solutions.pose
app = Flask(__name__)

@app.route('/')
def hello_world():
    pose = mp_pose.Pose(static_image_mode=True, min_detection_confidence=0.5, upper_body_only=True)
    image = cv2.imread('/path/to/pose.jpg')
    image_hight, image_width, _ = image.shape
    pose_results = pose.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    return str(f'nose landmark: ('
        f'{pose_results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].x * image_width},'
        f'{pose_results.pose_landmarks.landmark[mp_pose.PoseLandmark.NOSE].y * image_hight})')
```

My command:
```
$ python -m flask run
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

The output:
![Screen Shot 2021-02-01 at 10 09 36 AM](https://user-images.githubusercontent.com/3359144/106499694-bd036680-6475-11eb-8e3c-f98f8374c79d.png)

**Comment by nikitatishin5** [comment] 2021-02-01 19:50
Yes, its good! It works for me as well. But can you make it via sockets or just some how overload your server? Because i dont know how to reproduce my problem. I guess that is just because of weak laptop.

**Comment by nikitatishin5** [comment] 2021-02-01 20:09
Now i just wrote little app and its end with error "Packet timestamp mismatch on a calculator receiving from stream "image". Current minimum expected timestamp is 133333 but received 133332. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.":




import cv2
import mediapipe as mp
mp_drawing = mp.solutions.drawing_utils
mp_hands = mp.solutions.hands
import threading


hands = mp_hands.Hands(
    static_image_mode=True,
    max_num_hands=2,
    min_detection_confidence=0.5)
def foo(i):
    print(f"Поток {i} начался")
    file_list = ['/Users/nikitatishin/Desktop/Screen Shot 2020-12-10 at 6.06.50 PM.png']
    for idx, file in enumerate(file_list):
        image = cv2.flip(cv2.imread(file), 1)
        results = hands.process(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
        if not results.multi_hand_landmarks:
            continue
        image_hight, image_width, _ = image.shape
        annotated_image = image.copy()
        for hand_landmarks in results.multi_hand_landmarks:
        
          
    


thread_list = []

for i in range(0,15):
    a = threading.Thread(target=foo,args=(i,))
    a.start()
    thread_list.append(a)

for i in thread_list:
    i.join()

**Comment by raghavgurbaxani** [comment] 2021-02-02 05:14
I get the following error - 

`Error: socket hang up`

**Comment by nikitatishin5** [comment] 2021-02-02 06:35
May be it was my error in the beginning, but it was hided somehow. Im not sure

**Comment by sukkritsharmaofficial** [comment] 2021-04-28 08:56
hi @nikitatishin5 , i'm facing the same issue while using multi-threading and mp together, did you fix the issue by any chance? If yes, can you please tell me how to fix it ?

**Comment by nikitatishin5** [comment] 2021-04-28 09:06
I made little less load for server. So i count avg requests per minute and dynamically changing count of Hands class exemplars. And trying to do not use one class example for more then 15 parallel counting. And also i began use gunicorn, and made picture format to jpg and with less quality 28 апр. 2021 г. 11:56 пользователь Sukkrit Sharma ***@***.***> написал:
hi @nikitatishin5 , i'm facing the same issue while using multi-threading and mp together, did you fix the issue by any chance? If yes, can you please tell me how to fix it ?

**Comment by sukkritsharmaofficial** [comment] 2021-04-28 14:32
@nikitatishin5 okay, thank you so much, i'll try to limit the number of image throughputs too!

**Comment by sgowroji** [comment] 2021-04-29 07:03
We are glad you shared your resolution. Hence closing this ticket.

**Closed by sgowroji** 2021-04-29 07:03 UTC
Labels: platform:python, platform:web

**Comment by nikitatishin5** [comment] 2021-04-29 07:52
Its not that way, which i would prefer. Instead of 60 fps i got 25-30. Its terrible.29 апр. 2021 г. 10:03 пользователь GowrojiSunil ***@***.***> написал:
We are glad you shared your resolution. Hence closing this ticket.

**Comment by evandromoura** [comment] 2022-11-01 02:37
@nikitatishin5 
try to create a new instance before calling the method 
ex:
faceDetector = FaceDetection() 
faces, boxes = faceDetector(frame)

**Comment by ddelange** [comment] 2023-05-23 10:14
Hi 👋

I can confirm that some part of the internal (C++?) code is not thread-safe.

In Python (FastAPI in our case, analogous to Flask), we have a shared `mediapipe.solutions.pose.Pose()` instance, and we're calling `pose.process(...)` from multiple threads simultaneously. This will hit the `Current minimum expected timestamp is 133333 but received 133332.` error posted above (`ValueError: CalculatorGraph::Run() failed in Run`).

To fix this, you can either force the application to run on a single thread (we don't want that), or you can wrap the call to `pose.process(...)` in a [threading.Lock](https://docs.python.org/3/library/threading.html#lock-objects):

```diff
+ import threading
+ lock = threading.Lock()  # a lock on global scope, or self.lock = threading.Lock() in your class's __init__

  def process_file(filename):
      ...
-     pose_results = pose.process(...)
+     with lock:  # force running sequentially when multiple threads call this function simultaneously
+         pose_results = pose.process(...)
```

**Comment by whuang288alex** [comment] 2023-06-05 22:17
Hi @ddelange, I want to use mediapipe hand landmark detection in my flask application.  The following code run just fine without importing mediapipe. However, if I do import mediapipe as mp then it just get stuck like this.

<img width="384" alt="image" src="https://github.com/google/mediapipe/assets/91099638/9bbeef3d-dd5d-4e52-80f0-bbae1feabe85">

Can you please help me out? Many thanks!

import cv2
from flask import Flask, Response

app = Flask(__name__)
video = cv2.VideoCapture(0)

def gen(video):
    while True:
        success, image = video.read()
        ret, jpeg = cv2.imencode('.jpg', image)
        frame = jpeg.tobytes()
        yield (b'--frame\r\n'b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')

@app.route('/')
def index():
    global video
    return Response(gen(video), mimetype='multipart/x-mixed-replace; boundary=frame')

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=2207, threaded=False)

**Comment by sourabmaity** [comment] 2023-08-11 02:58
Hi 👋

I am getting an error :
ValueError: CalculatorGraph::Run() failed in Run: 
; Packet timestamp mismatch on a calculator receiving from stream "image". Current minimum expected timestamp is 433330 but received 433329. Are you using a custom InputStreamHandler? Note that some InputStreamHandlers allow timestamps that are not strictly monotonically increasing. See for example the ImmediateInputStreamHandler class comment.

How to solve this ? if any one help

**Comment by ddelange** [comment] 2023-08-11 07:15
hi @sourabmaity :wave: did you try my comment from May 23?

**Comment by sourabmaity** [comment] 2023-08-11 07:39
Thank you for quick response i used threading.Semaphore() that works

**Comment by ddelange** [comment] 2023-08-11 08:43
nice. just fyi a `Sempaphore(1)` is about 12x slower than a `Lock()`:

```pycon
In [1]: import threading

In [2]: semaphore = threading.Semaphore()
   ...: lock = threading.Lock()

In [3]: def sem():
   ...:     with semaphore:
   ...:         pass
   ...:

In [4]: def loc():
   ...:     with lock:
   ...:         pass
   ...:

In [5]: %timeit sem()
5.07 µs ± 95.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [6]: %timeit loc()
430 ns ± 11 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)
```
