### ISSUE TITLE
Fail to use python api on macos

### ISSUE THREAD

**Issue by nancy618618** [google/mediapipe#2003] opened 2021-05-08 09:23 UTC
Hi,
recently I use the python api on macos to do pose keypoint detection, the code used is list in this link, https://google.github.io/mediapipe/solutions/pose.html, but met the problem below:
RuntimeError: CalculatorGraph::Run() failed in Run: 
Calculator::Open() for node "poselandmarkbyroicpu__inferencecalculator__poselandmarkbyroicpu__InferenceCalculator" failed: ; interpreter_ilure (mediapipe/calculators/tensor/inference_calculator_cpu.cc:142) 
Could you help me how to solve this problem, thanks. The below images are code used and error occured.
Looking forward to your response. 
<img width="1129" alt="截屏2021-05-08 下午5 16 52" src="https://user-images.githubusercontent.com/62641994/117533780-3d130c80-b021-11eb-9c2c-7ba9c445fc0a.png">

<img width="679" alt="截屏2021-05-08 下午5 17 56" src="https://user-images.githubusercontent.com/62641994/117533807-5c119e80-b021-11eb-9a67-8f1c86d6e80a.png">

**Comment by jiuqiant** [comment] 2021-05-09 03:27
Hi, let's try the following two to diagnose the problem:

1) If you change the model_complexity to 0 or 1, does this error still exist?
2) Try deleting site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite and then rerun pose api with model_complexity=2. Does the previous issue still exist?

**Comment by nancy618618** [comment] 2021-05-10 02:50
Thanks for your reply, change the model_complexity to 0 fix the problem.

**Comment by rmothukuru** [comment] 2021-05-10 10:42
@nancy618618,
Can you please let us know if the issue is resolved so that we can close it? Thanks!

**Comment by sgowroji** [comment] 2021-05-19 07:01
Assuming your issue fixed, we are closing this issue now.

**Closed by sgowroji** 2021-05-19 07:01 UTC
Labels: calculators, solution:pose, stat:awaiting response, type:support

**Comment by beausoft** [comment] 2022-06-05 07:24
> Hi, let's try the following two to diagnose the problem:
> 
> 1. If you change the model_complexity to 0 or 1, does this error still exist?
> 2. Try deleting site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite and then rerun pose api with model_complexity=2. Does the previous issue still exist?

I fix the issue by deleting "site-packages/mediapipe/modules/pose_landmark/pose_landmark_heavy.tflite". The reason is that pose_landmark_heavy.tflite is not complete.
![捕获](https://user-images.githubusercontent.com/9295882/172040070-dbe06cc3-cbb0-4323-8229-dd4258a3896e.PNG)
