### ISSUE TITLE
Multihand tracking Linux desktop example freezes when polling for landmarks

### ISSUE THREAD

**Issue by prantoran** [google/mediapipe#1532] opened 2021-01-21 08:42 UTC
The pc has gpu support with Nvidia 460 drivers. I am running the desktop example for Linux. When I poll for landmarks in the following way, the app freezes:
```
  ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller,
                   graph.AddOutputStreamPoller(kOutputStream));
  ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller multi_hand_landmarks_poller,
                  graph.AddOutputStreamPoller("hand_landmarks"));
...
...
mediapipe::Packet multi_hand_landmarks_packet;
    // check if landmarks exist from graph
    if (!multi_hand_landmarks_poller.Next(&multi_hand_landmarks_packet)) {
      std::cout << "landmarks cannot be polled\n";
      break;
    }
...
```

**Comment by prantoran** [comment] 2021-01-21 08:49
Update: app freezes once no hand is detected in image and stays frozen forever.

**Comment by prantoran** [comment] 2021-01-21 09:15
I tried modifying the `bool OutputStreamPollerImpl::Next(Packet* packet)` function in `mediapipe/framework/graph_output_stream.cc` by breaking from while loop if `empty_queue` occurred for more than 3 times but it did not work.

**Comment by prantoran** [comment] 2021-01-21 09:41
If I comment out the mutex locks in ` bool OutputStreamPollerImpl::Next(Packet* packet)` then it works.

**Comment by hadon** [comment] 2021-01-29 19:35
The symptom of failing once no hand is detected sounds quite familiar, maybe @grishchenko-ivan can provide some insight. It's interesting that the freeze can be avoided by disabling the mutex synchronization.  Let me know if you have any theory about the root cause of the freeze.

**Comment by ivan-grishchenko** [comment] 2021-01-30 01:01
It can be something with loop that uses MP packets with pseudo-timestamps to predict multiple hands (here: https://github.com/google/mediapipe/blob/master/mediapipe/modules/hand_landmark/hand_landmark_tracking_gpu.pbtxt#L112). @fanzhanggoogle and @eknight7 Could you please take a look?

**Comment by morfant** [comment] 2021-02-18 11:57
> If I comment out the mutex locks in ` bool OutputStreamPollerImpl::Next(Packet* packet)` then it works.

Just for the infomation,
On a mac (big sur)

[mutex.cc : 2409] RAW: thread should hold at least a read lock on Mutex 0x7f8adec23bc0

Occured.

**Comment by eknight7** [comment] 2021-03-25 22:02
Hi @morfant, @prantoran can you please confirm if you are observing this issue in the latest MediaPipe release? Thank you.

**Comment by caoqiang250** [comment] 2021-04-25 09:42
> Hi @morfant, @prantoran can you please confirm if you are observing this issue in the latest MediaPipe release? Thank you.


I have tried, and this problem still exists. When the program cannot detect the hand, this line of code will block the program forever, causing the program to feign death.

`auto& multiHandLandmarks = landmark_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();`

**Comment by caoqiang250** [comment] 2021-04-25 11:17
I have resoved this question, now it works well! this is my solution:
1.edit your gragh /mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt,add a node "PacketPresenceCalculator" and a output stream "landmark_presence". it is my graph:
'
# MediaPipe graph that performs hands tracking on desktop with TensorFlow
# Lite on CPU.
# Used in the example in
# mediapipe/examples/desktop/hand_tracking:hand_tracking_cpu.
# contact me 952631256@qq.com

# CPU image. (ImageFrame)
input_stream: "input_video"

# CPU image. (ImageFrame)
output_stream: "output_video"

# Collection of detected/predicted hands, each represented as a list of
# landmarks. (std::vector<NormalizedLandmarkList>)
output_stream: "landmarks"

# add this output stream ,we can use it to jurge if there Poller.Next() can  work
output_stream: "landmark_presence"

# Generates side packet cotaining max number of hands to detect/track.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:num_hands"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 2 }
    }
  }
}

# Detects/tracks hand landmarks.
node {
  calculator: "HandLandmarkTrackingCpu"
  input_stream: "IMAGE:input_video"
  input_side_packet: "NUM_HANDS:num_hands"
  output_stream: "LANDMARKS:landmarks"
  output_stream: "HANDEDNESS:handedness"
  output_stream: "PALM_DETECTIONS:multi_palm_detections"
  output_stream: "HAND_ROIS_FROM_LANDMARKS:multi_hand_rects"
  output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:multi_palm_rects"
}

# Subgraph that renders annotations and overlays them on top of the input
# images (see hand_renderer_cpu.pbtxt).
node {
  calculator: "HandRendererSubgraph"
  input_stream: "IMAGE:input_video"
  input_stream: "DETECTIONS:multi_palm_detections"
  input_stream: "LANDMARKS:landmarks"
  input_stream: "HANDEDNESS:handedness"
  input_stream: "NORM_RECTS:0:multi_palm_rects"
  input_stream: "NORM_RECTS:1:multi_hand_rects"
  output_stream: "IMAGE:output_video"
}

# add PacketPresenceCalculator  加入这个计算器，可以判断是否有可用的landmarks 可用
node {
  calculator: "PacketPresenceCalculator"
  input_stream: "PACKET:landmarks"
  output_stream: "PRESENCE:landmark_presence"
}
'
2.config your /mediapipe/graphs/hand_tracking/BUILD file,for cc_library,add a dependence "//mediapipe/calculators/core:packet_presence_calculator",it is my BUILD file:
'
~~~~~~some code~~~~~~ 
cc_library(
    name = "desktop_tflite_calculators",
    deps = [
        ":desktop_offline_calculators",
        "//mediapipe/calculators/core:constant_side_packet_calculator",
        "//mediapipe/calculators/core:merge_calculator",
        **"//mediapipe/calculators/core:packet_presence_calculator",**
        "//mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu",
        "//mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu",
    ],
)

~~~~~~some code~~~~~~ 

'
3.edit your src file mediapipe/examples/desktop/demo_run_graph.cc

'
~~~~~~some code~~~~~~ 
ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller,
                   graph.AddOutputStreamPoller(kOutputStream));
  ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller_landmark,
                   graph.AddOutputStreamPoller(kLandmarksStream));
  ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller presence_poller,
                   graph.AddOutputStreamPoller("landmark_presence"));'
~~~~~~some code~~~~~~
mediapipe::Packet packet;
    mediapipe::Packet landmark_packet;
    mediapipe::Packet presence_packet;
    if (!poller.Next(&packet)) break;
    // check whether the packet exists
    if (!presence_poller.Next(&presence_packet)) break;
    auto is_landmark_present = presence_packet.Get<bool>();
     if (is_landmark_present) {
      if (!poller_landmark.Next(&landmark_packet)) break;
      auto& multiHandLandmarks = landmark_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
     //there is your code,you can use multiHandLandmarks 
     }

auto& output_frame = packet.Get<mediapipe::ImageFrame>();
~~~~~~some code~~~~~~

**Comment by morfant** [comment] 2021-04-29 14:11
> I have resoved this question, now it works well! this is my solution:
> 1.edit your graph /mediapipe/graphs/hand_tracking/hand_tracking_desktop_live.pbtxt,add a node "PacketPresenceCalculator" and a output stream "landmark_presence". it is my graph:
> 
> ```
> input_stream: "input_video"
> output_stream: "output_video"
> output_stream: "landmarks"
> output_stream: "landmark_presence"
> 
> node {
>   calculator: "ConstantSidePacketCalculator"
>   output_side_packet: "PACKET:num_hands"
>   node_options: {
>     [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
>       packet { int_value: 2 }
>     }
>   }
> }
> 
> node {
>   calculator: "HandLandmarkTrackingCpu"
>   input_stream: "IMAGE:input_video"
>   input_side_packet: "NUM_HANDS:num_hands"
>   output_stream: "LANDMARKS:landmarks"
>   output_stream: "HANDEDNESS:handedness"
>   output_stream: "PALM_DETECTIONS:multi_palm_detections"
>   output_stream: "HAND_ROIS_FROM_LANDMARKS:multi_hand_rects"
>   output_stream: "HAND_ROIS_FROM_PALM_DETECTIONS:multi_palm_rects"
> }
> 
> node {
>   calculator: "HandRendererSubgraph"
>   input_stream: "IMAGE:input_video"
>   input_stream: "DETECTIONS:multi_palm_detections"
>   input_stream: "LANDMARKS:landmarks"
>   input_stream: "HANDEDNESS:handedness"
>   input_stream: "NORM_RECTS:0:multi_palm_rects"
>   input_stream: "NORM_RECTS:1:multi_hand_rects"
>   output_stream: "IMAGE:output_video"
> }
> 
> node {
>   calculator: "PacketPresenceCalculator"
>   input_stream: "PACKET:landmarks"
>   output_stream: "PRESENCE:landmark_presence"
> }
> ```
> 
> 2.config your /mediapipe/graphs/hand_tracking/BUILD file,for cc_library,add a dependence "//mediapipe/calculators/core:packet_presence_calculator",it is my BUILD file:
> 
> ```
> ~~~~~~some code~~~~~~ 
> cc_library(
>     name = "desktop_tflite_calculators",
>     deps = [
>         ":desktop_offline_calculators",
>         "//mediapipe/calculators/core:constant_side_packet_calculator",
>         "//mediapipe/calculators/core:merge_calculator",
>         "//mediapipe/calculators/core:packet_presence_calculator",
>         "//mediapipe/graphs/hand_tracking/subgraphs:hand_renderer_cpu",
>         "//mediapipe/modules/hand_landmark:hand_landmark_tracking_cpu",
>     ],
> )
> 
> 
> ~~~~~~some code~~~~~~ 
> ```
> 
> 3.edit your src file mediapipe/examples/desktop/demo_run_graph.cc
> 
> ```
> ~~~~~~some code~~~~~~ 
> ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller,
>                    graph.AddOutputStreamPoller(kOutputStream));
>   ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller poller_landmark,
>                    graph.AddOutputStreamPoller(kLandmarksStream));
>   ASSIGN_OR_RETURN(mediapipe::OutputStreamPoller presence_poller,
>                    graph.AddOutputStreamPoller("landmark_presence"));'
> ~~~~~~some code~~~~~~
> mediapipe::Packet packet;
>     mediapipe::Packet landmark_packet;
>     mediapipe::Packet presence_packet;
>     if (!poller.Next(&packet)) break;
>     // check whether the packet exists
>     if (!presence_poller.Next(&presence_packet)) break;
>     auto is_landmark_present = presence_packet.Get<bool>();
>      if (is_landmark_present) {
>       if (!poller_landmark.Next(&landmark_packet)) break;
>       auto& multiHandLandmarks = landmark_packet.Get<std::vector<::mediapipe::NormalizedLandmarkList>>();
>      //there is your code,you can use multiHandLandmarks 
>      }
> 
> auto& output_frame = packet.Get<mediapipe::ImageFrame>();
> ~~~~~~some code~~~~~~
> ```

It works! Thank you!!!

**Comment by sgowroji** [comment] 2021-04-30 05:45
Glad to know it worked, We are closing this issue now. Thanks!

**Closed by sgowroji** 2021-04-30 05:45 UTC
Labels: platform:desktop, solution:hands, stat:awaiting response

**Comment by txf-** [comment] 2021-04-30 16:27
This works for the landmark presence. But I would have also liked access handedness, which blocks in the same way. So I tried using the PacketPresenceCalculator for handedness packets, unfortunately it doesn't seem to work.  Am I misunderstanding anything about its usage?
