### ISSUE TITLE
android pose err

### ISSUE THREAD

**Issue by qichuangguo** [google/mediapipe#3016] opened 2022-01-26 06:41 UTC
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file android/R$attr
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrFields(AndroidFrameworkAttrIdJar.java:56)
	at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:44)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
1643179169.454413655: src/main/tools/linux-sandbox-pid1.cc:423: wait returned pid=2, status=0x100
1643179169.454424365: src/main/tools/linux-sandbox-pid1.cc:441: child exited normally with code 1
1643179169.454728456: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:pose_tracking_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.599s, Critical Path: 2.42s
INFO: 131 processes: 129 internal, 1 linux-sandbox, 1 worker.

**Comment by sgowroji** [comment] 2022-01-26 08:46
Hi @qichuangguo, Could you please provide steps to reproduce the above error. Thanks!

**Comment by qichuangguo** [comment] 2022-01-26 09:08
bazel build -c opt --fat_apk_cpu=arm64-v8a,armeabi-v7a //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:pose_tracking_aar        




BUILD：
load("//mediapipe/java/com/google/mediapipe:mediapipe_aar.bzl", "mediapipe_aar")
mediapipe_aar(
    name = "pose_tracking_aar",
    calculators = ["//mediapipe/graphs/pose_tracking:pose_tracking_gpu_deps"],
)

**Comment by qichuangguo** [comment] 2022-01-26 09:09
err:


ERROR: /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/external/maven/BUILD:708:11: Merging compiled Android resources for @maven//:androidx_vectordrawable_vectordrawable failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe && \
  exec env - \
    PATH=/home/qcg/.cache/bazelisk/downloads/bazelbuild/bazel-4.2.1-linux-x86_64/bin:/mnt/data/Android/Sdk/tools:/mnt/data/Android/Sdk/platform-tools:/mnt/data/Android/Sdk:/mnt/data/Android/Sdk/ndk/22.1.7171670:/mnt/data/DeveloperTool/cocos2d-x-4.0/templates:/mnt/data/DeveloperTool:/mnt/data/DeveloperTool/cocos2d-x-4.0/tools/cocos2d-console/bin:/home/qcg/bin:/home/qcg/anaconda3/bin:/home/qcg/anaconda3/condabin:/home/qcg/.local/bin:/home/qcg/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/mnt/data/DeveloperTool/jdk1.8.0_131/bin:/mnt/data/Android/Sdk/tools:/mnt/data/Android/Sdk/platform-tools \
    TMPDIR=/tmp \
  /home/qcg/.cache/bazel/_bazel_qcg/install/ee8d7e4b6774884ed2cd0aece6fc9fda/linux-sandbox -t 15 -w /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe -w /tmp -w /dev/shm -D -- bazel-out/k8-opt-exec-50AE0418/bin/external/bazel_tools/src/tools/android/java/com/google/devtools/build/android/ResourceProcessorBusyBox --tool MERGE_COMPILED -- --classJarOutput bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_vectordrawable_vectordrawable_resources.jar --targetLabel @maven//:androidx_vectordrawable_vectordrawable --manifestOutput bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_vectordrawable_vectordrawable_processed_manifest/AndroidManifest.xml --androidJar external/androidsdk/platforms/android-31/android.jar --primaryManifest bazel-out/android-arm64-v8a-opt/bin/external/maven/_aar/androidx_vectordrawable_vectordrawable/AndroidManifest.xml --primaryData ';;@maven//:androidx_vectordrawable_vectordrawable;bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_vectordrawable_vectordrawable_symbols/symbols.zip' --directData ';;@maven//:androidx_core_core;bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_core_core_symbols/symbols.zip' --data ';;@maven//:androidx_arch_core_core_runtime;bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_arch_core_core_runtime_symbols/symbols.zip&;;@maven//:androidx_lifecycle_lifecycle_runtime;bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_lifecycle_lifecycle_runtime_symbols/symbols.zip&;;@maven//:androidx_versionedparcelable_versionedparcelable;bazel-out/android-arm64-v8a-opt/bin/external/maven/androidx_versionedparcelable_versionedparcelable_symbols/symbols.zip')
1643188133.270329600: src/main/tools/linux-sandbox.cc:152: calling pipe(2)...
1643188133.270365906: src/main/tools/linux-sandbox.cc:171: calling clone(2)...
1643188133.270587470: src/main/tools/linux-sandbox.cc:180: linux-sandbox-pid1 has PID 73670
1643188133.281125429: src/main/tools/linux-sandbox-pid1.cc:447: Pid1Main started
1643188133.281312351: src/main/tools/linux-sandbox-pid1.cc:189: working dir: /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe
1643188133.281329997: src/main/tools/linux-sandbox-pid1.cc:221: writable: /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe
1643188133.281336020: src/main/tools/linux-sandbox-pid1.cc:221: writable: /tmp
1643188133.281341992: src/main/tools/linux-sandbox-pid1.cc:221: writable: /dev/shm
1643188133.281389311: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /
1643188133.281395669: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev
1643188133.281399534: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/pts
1643188133.281403489: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /dev/shm
1643188133.281406769: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/hugepages
1643188133.281410550: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /dev/mqueue
1643188133.281414249: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run
1643188133.281417722: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/lock
1643188133.281421673: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/user/1000
1643188133.281425508: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/user/1000/gvfs
1643188133.281429236: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/user/1000/doc
1643188133.281433006: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /run/snapd/ns
1643188133.281436891: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys
1643188133.281458463: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/security
1643188133.281463497: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup
1643188133.281467384: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/unified
1643188133.281471361: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/systemd
1643188133.281475260: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/freezer
1643188133.281478844: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/pids
1643188133.281482653: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/memory
1643188133.281486432: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/cpu,cpuacct
1643188133.281490565: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/net_cls,net_prio
1643188133.281494364: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/blkio
1643188133.281498724: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/devices
1643188133.281502368: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/cpuset
1643188133.281523490: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/hugetlb
1643188133.281527791: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/perf_event
1643188133.281531392: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/cgroup/rdma
1643188133.281535142: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/pstore
1643188133.281538834: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/firmware/efi/efivars
1643188133.281543512: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/bpf
1643188133.281547780: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/debug
1643188133.281551494: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/tracing
1643188133.281555279: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/fs/fuse/connections
1643188133.281559423: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /sys/kernel/config
1643188133.281570327: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc
1643188133.281574380: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc/sys/fs/binfmt_misc
1643188133.281580369: src/main/tools/linux-sandbox-pid1.cc:313: remount(nullptr, /proc/sys/fs/binfmt_misc, nullptr, 2101281, nullptr) failure (Operation not permitted) ignored
1643188133.281590323: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /proc/sys/fs/binfmt_misc
1643188133.281594865: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/bare/5
1643188133.281610784: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core18/2253
1643188133.281614508: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/postman/148
1643188133.281617828: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core20/1270
1643188133.281621181: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core18/2284
1643188133.281624610: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gnome-3-28-1804/145
1643188133.281628121: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core/11993
1643188133.281631624: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core20/1242
1643188133.281634916: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/scrcpy/364
1643188133.281638405: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gtk-common-themes/1515
1643188133.281641758: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gnome-3-38-2004/87
1643188133.281645592: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gtk-common-themes/1519
1643188133.281649077: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/netron/229
1643188133.281652376: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/vlc/2288
1643188133.281655913: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/snap-store/558
1643188133.281659548: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/snapd/14549
1643188133.281662777: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/snap-store/547
1643188133.281681947: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gnome-3-28-1804/161
1643188133.281686941: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/scrcpy/351
1643188133.281690029: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/postman/149
1643188133.281693439: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gnome-3-34-1804/72
1643188133.281697047: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/snapd/14295
1643188133.281700274: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/vlc/2344
1643188133.281703799: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/netron/230
1643188133.281707267: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/gnome-3-34-1804/77
1643188133.281711246: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /mnt/data
1643188133.281716182: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /boot/efi
1643188133.281719697: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /snap/core/12603
1643188133.281723382: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /tmp/.mount_Qv2rayPFAUbM
1643188133.281727891: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe
1643188133.281737569: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /home/qcg/.cache/bazel/_bazel_qcg/94b563eeccd2c836fa5af676613159f4/sandbox/linux-sandbox/3692/execroot/mediapipe
1643188133.281741486: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /tmp
1643188133.281744690: src/main/tools/linux-sandbox-pid1.cc:292: remount ro: /tmp/.mount_Qv2rayPFAUbM
1643188133.281747944: src/main/tools/linux-sandbox-pid1.cc:292: remount rw: /dev/shm
1643188133.281792796: src/main/tools/linux-sandbox-pid1.cc:376: calling fork...
1643188133.281931752: src/main/tools/linux-sandbox-pid1.cc:406: child started with PID 2
1643188133.281962359: src/main/tools/linux-sandbox.cc:197: done manipulating pipes
Exception in thread "main" java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file android/R$attr
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrFields(AndroidFrameworkAttrIdJar.java:56)
	at com.google.devtools.build.android.AndroidFrameworkAttrIdJar.getAttrId(AndroidFrameworkAttrIdJar.java:44)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.getStyleableInitializers(PlaceholderIdFieldInitializerBuilder.java:329)
	at com.google.devtools.build.android.PlaceholderIdFieldInitializerBuilder.build(PlaceholderIdFieldInitializerBuilder.java:238)
	at com.google.devtools.build.android.AndroidResourceClassWriter.flush(AndroidResourceClassWriter.java:114)
	at com.google.devtools.build.android.UnwrittenMergedAndroidData.writeResourceClass(UnwrittenMergedAndroidData.java:91)
	at com.google.devtools.build.android.AndroidResourceMerger.mergeCompiledData(AndroidResourceMerger.java:275)
	at com.google.devtools.build.android.AndroidCompiledResourceMergingAction.main(AndroidCompiledResourceMergingAction.java:231)
	at com.google.devtools.build.android.ResourceProcessorBusyBox$Tool$3.call(ResourceProcessorBusyBox.java:81)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.processRequest(ResourceProcessorBusyBox.java:234)
	at com.google.devtools.build.android.ResourceProcessorBusyBox.main(ResourceProcessorBusyBox.java:177)
1643188134.247321674: src/main/tools/linux-sandbox-pid1.cc:423: wait returned pid=2, status=0x100
1643188134.247333718: src/main/tools/linux-sandbox-pid1.cc:441: child exited normally with code 1
1643188134.247555781: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
Target //mediapipe/examples/android/src/java/com/google/mediapipe/apps/buid_aar:pose_tracking_aar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 117.007s, Critical Path: 5.12s
INFO: 145 processes: 129 internal, 13 linux-sandbox, 3 worker.
FAILED: Build did NOT complete successfully

**Comment by sgowroji** [comment] 2022-01-28 13:58
Hi @qichuangguo, Can you provide system configuration in which the above issue is seen. Thanks!

**Comment by qichuangguo** [comment] 2022-01-29 00:13
Ubuntu 20.10   64 bit  GNOME  3.38.3  memory 16G

**Comment by sgowroji** [comment] 2022-02-09 17:09
Duplicate of https://github.com/google/mediapipe/issues/3057

**Comment by sgowroji** [comment] 2022-02-17 04:49
Closing as the duplicate is closed.

**Closed by sgowroji** 2022-02-17 04:49 UTC
Labels: status:duplicate, type:support, platform:android, solution:pose, android::aar
