### ISSUE TITLE
Workspace error

### ISSUE THREAD

**Issue by dgrnd4** [google/mediapipe#994] opened 2020-08-11 13:53 UTC
**ERROR: C:/users/diego/mediapipe/WORKSPACE:180:16: invalid escape sequence: \U
ERROR: error loading package 'external': Failed to parse WORKSPACE file
INFO: Elapsed time: 0.104s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
FAILED: Build did NOT complete successfully (0 packages loaded)**

Hi, when i use the command  "bazel run mediapipe/examples/desktop/hello_world:hello_world" the error above appear.

Can you help me? maybe i'm missing something in the installation.
There are some of you who have been solved the same problem?

**Comment by jiuqiant** [comment] 2020-08-11 16:15
Duplicate of https://github.com/google/mediapipe/issues/993.

**Closed by jiuqiant** 2020-08-11 16:15 UTC

**Comment by Victoria-1** [comment] 2021-09-28 10:54
> **ERROR: C:/users/diego/mediapipe/WORKSPACE:180:16: invalid escape sequence: \U ERROR: error loading package 'external': Failed to parse WORKSPACE file INFO: Elapsed time: 0.104s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded) FAILED: Build did NOT complete successfully (0 packages loaded)**
> 
> Hi, when i use the command "bazel run mediapipe/examples/desktop/hello_world:hello_world" the error above appear.
> 
> Can you help me? maybe i'm missing something in the installation. There are some of you who have been solved the same problem?

I got the same question! Have you solved it?  Any recommendations?

**Comment by dgrnd4** [comment] 2021-09-28 11:24
if i am not wrong i solved it switching operative system from windows to linux

**Comment by Victoria-1** [comment] 2021-09-29 07:57
> if i am not wrong i solved it switching operative system from windows to linux

Thanks!  It seems some variables i set did not work without restarting the computer. After i restarted the computer, built successfully.
