### ISSUE TITLE
Dart package

### ISSUE THREAD

**Issue by rohrz4nge** [google/mediapipe#1046] opened 2020-08-25 21:28 UTC
Is a Dart package for easy cross-plattform use with Flutter planned or will we have to wait for the MLKit integration for this?

**Comment by mgyong** [comment] 2020-08-26 16:36
Duplicate of #17 
No plans for flutter package from MediaPipe team. However, there is community example in [awesome-mediapipe repo](https://mediapipe.org)

**Closed** 2020-08-26 16:36 UTC
