### ISSUE TITLE
Memory leak in facemesh demo 

### ISSUE THREAD

**Issue by ankitadloid** [google/mediapipe#2245] opened 2021-07-02 07:25 UTC
link : https://codepen.io/mediapipe/pen/KKgVaPJ

Google Chrome | 91.0.4472.114 (Official Build) (x86_64)
-- | --
Revision | 4bb19460e8d88c3446b360b0df8fd991fee49c0b-refs/branch-heads/4472@{#1496}
OS | macOS Version 12.0 (Build 21A5248p)
JavaScript | V8 9.1.269.36

Checked in chrome's task manager 
subframe https://cdpn.io/ memory footprint keeps on increasing.
<img width="1240" alt="Screenshot 2021-07-02 at 12 54 43 PM" src="https://user-images.githubusercontent.com/83121879/124236989-af413280-db34-11eb-8379-6be1d71bfd5b.png">

**Comment by sgowroji** [comment] 2021-07-02 07:44
Hi @ankitadloid, Could you please provide the steps to reproduce the above error. Thanks!

**Comment by ankitadloid** [comment] 2021-07-02 07:58
@sgowroji After visiting webpage https://codepen.io/mediapipe/pen/KKgVaPJ , check memory footprint using chrome's task manger.
Also, I verified memory leak by testing the code separately (without codepen) on my local environment , took heap snapshots after every ~10 sec 
<img width="609" alt="Screenshot 2021-07-02 at 1 24 59 PM" src="https://user-images.githubusercontent.com/83121879/124241013-fc270800-db38-11eb-98fc-872388863e32.png">

**Comment by tyrmullen** [comment] 2021-07-07 17:38
I believe this is the same issue as #1937 , which should now be fixed with the latest update.  I tried the link you provided just now (on Chrome Desktop), and was unable to reproduce the leak, taking snapshots every 10 seconds or so (it stayed at ~8.0MB for me).

**Closed by tyrmullen** 2021-07-07 17:38 UTC
Labels: platform:javascript, stat:awaiting googler, type:support
