### ISSUE TITLE
Memory leak with handtracking iOS

### ISSUE THREAD

**Issue by noppefoxwolf** [google/mediapipe#387] opened 2020-01-12 07:03 UTC
I found a memory leak on example project for iOS.

- Model: iPhone 11 Pro
- iOS: 13.3
- Xcode: 11.3
- mediapipe: v0.6.8
- bazel: 1.1.0
- tulsi: 0.20190814.88
- Scheme: HandTrackingGPUApp
- 3D / 2D both

![image](https://user-images.githubusercontent.com/2066707/72215257-505cb780-3554-11ea-924b-3f2c61545135.png)

```
Message from debugger: Terminated due to memory issue
```

**Comment by noppefoxwolf** [comment] 2020-01-13 06:00
Is this relevant?
https://github.com/google/mediapipe/issues/93

**Comment by fenollp** [comment] 2020-02-25 16:45
I can reproduce the issue. We experience leaks with our graphs on iOS as well.
It seems no CPU-only apps are leaking nor is the edge detection example app.

mediapipe v0.6.8.1
Xcode 11.3.1
iOS 13.3.1 (17D50)
Model: iPhone 6s
* ObjectDetectionCpuApp: no leaks
* ObjectDetectionGpuApp: crashes with
> validateComputeFunctionArguments:771: failed assertion `Compute Function(ComputeFunction): argument size[0] from buffer(7) with offset(0) and length(12) has space for 12 bytes, but argument has a length(16).'
* EdgeDetectionGpuApp: no leaks
* MultiHandTrackingGpuApp: leaks by allocating about 30MB/s
* HandTrackingGpuApp: leaks
* HandDetectionGpuApp: leaks
* FaceDetectionGpuApp: leaks
* FaceDetectionCpuApp: no leaks

**Comment by Jihadik** [comment] 2020-02-28 18:34
We are affected as well. `ObjectDetectionGpuApp` is crashing.  
Could we get some more attention to the issue, @mgyong?  
@fenollp, do you have an idea when the problem was introduced?

**Comment by danhd123** [comment] 2020-03-19 00:04
We're seeing the same thing on MultiHandTrackingGpuApp, Xcode 11.3.1, iOS 13.3.1, iPhone 11 Pro. The leak happens in both Debug and Release, but NOT when open in Instruments (regardless of which Instruments are active), which makes this well nigh impossible to actually debug.

**Comment by NikolayChirkov** [comment] 2020-03-19 00:07
The leak is fixed in upcoming release

**Comment by danhd123** [comment] 2020-03-19 00:20
Great to hear! Is the fix on the staging branch, or another fork, or is it not available yet? Any chance of posting the fix if it's not available on GitHub yet? It's be really great to get this ASAP.

**Comment by NikolayChirkov** [comment] 2020-03-19 00:31
While release is coming please use the quick fix: replace a single line https://github.com/google/mediapipe/blob/3b6d3c40589968c8333b4a936fbad7a8bea6d7f6/mediapipe/framework/scheduler_queue.cc#L28

with this code:

#ifdef __APPLE__
#define AUTORELEASEPOOL @autoreleasepool
#else
#define AUTORELEASEPOOL
#endif  // __APPLE__

**Comment by danhd123** [comment] 2020-03-19 01:03
Thank you!

For anyone confused by the automatic markdown parsing, that's supposed to be: 
```objc
#ifdef __APPLE__
#define AUTORELEASEPOOL @autoreleasepool
#else
#define AUTORELEASEPOOL
#endif // __APPLE__
```

**Comment by jiuqiant** [comment] 2020-03-24 23:47
This fix is in https://github.com/google/mediapipe/commit/1722d4b8a25ad7c919576f9b1bab4ffa7a9299bc.

**Closed by jiuqiant** 2020-03-24 23:47 UTC
Labels: ios
