### ISSUE TITLE
Latest version does not build on Windows

### ISSUE THREAD

**Issue by gerald-lee** [google/mediapipe#908] opened 2020-07-14 13:48 UTC
When I run below command
`bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python37//python.exe" mediapipe/examples/desktop/hello_world`

it generates the error:

```
ERROR: D:/git/mediapipe/mediapipe/framework/BUILD:824:1: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
.\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
.\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\memory(2078): note: see declaration of 'std::make_unique'
Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 71.407s, Critical Path: 68.40s
INFO: 152 processes: 152 local.
FAILED: Build did NOT complete successfully
```

I am using C++ BuildTools version 14.26.28801

If I rollback to mediapipe May version, it builds successfully.

**Comment by cwlee200** [comment] 2020-07-14 13:57
Also, at step 9 of [windows installation guideline](https://google.github.io/mediapipe/getting_started/install.html#installing-on-windows), I believe double slash should be used for the PYTHON_BIN_PATH. Otherwise, it will reproduce the issue 724.

i.e.
`Note: For building MediaPipe on Windows, please add --action_env PYTHON_BIN_PATH="C://path//to//python.exe" to the build command`
`C:\Users\Username\mediapipe_repo>bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://python_36//python.exe" mediapipe/examples/desktop/hello_world`

**Comment by rohabimbesat** [comment] 2020-07-14 16:23
i have the exact same issue

**Comment by jiuqiant** [comment] 2020-07-15 05:26
Try the following fixes. Note that those fixes may only work on native Windows with MSVC. Still looking for a more general solution that works across platforms (Linux, macOS, Windows, Android, and iOS).

```
diff --git a/mediapipe/framework/legacy_calculator_support.h b/mediapipe/framework/legacy_calculator_support.h          
index 4cd15ce..34139da 100644                                                                                           
--- a/mediapipe/framework/legacy_calculator_support.h                                                                   
+++ b/mediapipe/framework/legacy_calculator_support.h                                                                   
@@ -73,12 +73,12 @@ class LegacyCalculatorSupport {                                                                      
// definitions must be in the .cc file. However, a declaration still needs to be                                        
// included in the header, or some compilers will assume they have no                                                   
// definition.                                                                                                         
-template <>                                                                                                            
-thread_local CalculatorContext*                                                                                        
-    LegacyCalculatorSupport::Scoped<CalculatorContext>::current_;                                                      -template <>                                                                                                            
-thread_local CalculatorContract*                                                                                       
-    LegacyCalculatorSupport::Scoped<CalculatorContract>::current_;                                                     +// template <>                                                                                                         
+// thread_local CalculatorContext*                                                                                     
+//     LegacyCalculatorSupport::Scoped<CalculatorContext>::current_;                                                   +// template <>                                                                                                         
+// thread_local CalculatorContract*                                                                                    
+//     LegacyCalculatorSupport::Scoped<CalculatorContract>::current_;                                                   
}  // namespace mediapipe                                                                                                                                                                                                                      
diff --git a/mediapipe/framework/packet.h b/mediapipe/framework/packet.h                                                index f6b1774..3f296f9 100644                                                                                           
--- a/mediapipe/framework/packet.h                                                                                      
+++ b/mediapipe/framework/packet.h                                                                                      
@@ -445,7 +445,7 @@ struct MessageRegistrationImpl {                                                                     template <typename T>                                                                                                   NoDestructor<mediapipe::RegistrationToken>                                                                                  MessageRegistrationImpl<T>::registration(MessageHolderRegistry::Register(                                       
-        T{}.GetTypeName(), [] { return absl::make_unique<Holder<T>>(new T); }));                                    
+        T{}.GetTypeName(), absl::make_unique<Holder<T>>));                                                                                                                                                                                      
// For non-Message payloads, this does nothing.                                                                         
template <typename T, typename Enable = void>                           
```

**Comment by tonywang531** [comment] 2020-07-16 09:26
My C++ is I am using C++ BuildTools version 14.26.28808 and I have the same issue

**Comment by jiuqiant** [comment] 2020-07-16 17:22
The issue occurs at https://github.com/google/mediapipe/blob/e9fbe868e55fa23aaabc31f9f847c22287062850/mediapipe/framework/packet.h#L448.

GCC and clang are ok with the syntax `[] { return absl::make_unique<Holder<T>>(new T); })` on Linux and macos.  However, MSVC is not. It's unclear what't the right fix for MSVC.

**Comment by jiuqiant** [comment] 2020-07-16 17:28
Disclaimer: MediaPipe Windows support is experimental since we have limited resources and mainly focus on Linux and mobile platforms. 

The issue occurs at https://github.com/google/mediapipe/blob/e9fbe868e55fa23aaabc31f9f847c22287062850/mediapipe/framework/packet.h#L448.

GCC and clang are ok with the syntax `[] { return absl::make_unique<Holder<T>>(new T); })` on Linux and macos.  However, MSVC is not. It's unclear to me what't the right fix for MSVC on Windows. Any suggestions are welcome.

**Comment by jiuqiant** [comment] 2020-07-16 17:40
The issue occurs at https://github.com/google/mediapipe/blob/e9fbe868e55fa23aaabc31f9f847c22287062850/mediapipe/framework/packet.h#L448

GCC and clang are ok with the syntax `[] { return absl::make_unique<Holder<T>>(new T); })` on Linux and macos.  However, MSVC is not. It's unclear to me what't the right fix for MSVC on Windows. Any suggestions are welcome.

Please note that MediaPipe Windows support is experimental since we have limited resources and mainly focus on Linux and mobile platforms.

**Comment by rahulvenkat** [comment] 2020-07-17 20:45
> When I run below command
> `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python37//python.exe" mediapipe/examples/desktop/hello_world`
> 
> it generates the error:
> 
> ```
> ERROR: D:/git/mediapipe/mediapipe/framework/BUILD:824:1: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
> .\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
> .\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\memory(2078): note: see declaration of 'std::make_unique'
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> Use --verbose_failures to see the command lines of failed build steps.
> INFO: Elapsed time: 71.407s, Critical Path: 68.40s
> INFO: 152 processes: 152 local.
> FAILED: Build did NOT complete successfully
> ```
> 
> I am using C++ BuildTools version 14.26.28801
> 
> If I rollback to May version, it builds successfully.

How do you rollback to May version? Do you have a link?

**Comment by rahulvenkat** [comment] 2020-07-17 22:11
I rolledback to BUildTools version 14.25.28610 and I still see the issue:

> ERROR: C:/mediapipe_repo/mediapipe/mediapipe/framework/BUILD:824:11: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
> .\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
> .\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
> C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.25.28610\include\memory(2074): note: see declaration of 'std::make_unique'
> Target //mediapipe/examples/desktop/hello_world:hello_world failed to build

**Comment by tonywang531** [comment] 2020-07-18 01:29
> > When I run below command
> > `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python37//python.exe" mediapipe/examples/desktop/hello_world`
> > it generates the error:
> > ```
> > ERROR: D:/git/mediapipe/mediapipe/framework/BUILD:824:1: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
> > .\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
> > .\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
> > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\memory(2078): note: see declaration of 'std::make_unique'
> > Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> > Use --verbose_failures to see the command lines of failed build steps.
> > INFO: Elapsed time: 71.407s, Critical Path: 68.40s
> > INFO: 152 processes: 152 local.
> > FAILED: Build did NOT complete successfully
> > ```
> > 
> > 
> > I am using C++ BuildTools version 14.26.28801
> > If I rollback to May version, it builds successfully.
> 
> How do you rollback to May version? Do you have a link?

https://github.com/google/mediapipe/releases/tag/v0.7.5
You can download the older version as zip here

**Comment by jiuqiant** [comment] 2020-07-20 05:11
> > > When I run below command
> > > `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python37//python.exe" mediapipe/examples/desktop/hello_world`
> > > it generates the error:
> > > ```
> > > ERROR: D:/git/mediapipe/mediapipe/framework/BUILD:824:1: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
> > > .\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
> > > .\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
> > > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\memory(2078): note: see declaration of 'std::make_unique'
> > > Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> > > Use --verbose_failures to see the command lines of failed build steps.
> > > INFO: Elapsed time: 71.407s, Critical Path: 68.40s
> > > INFO: 152 processes: 152 local.
> > > FAILED: Build did NOT complete successfully
> > > ```
> > > 
> > > 
> > > I am using C++ BuildTools version 14.26.28801
> > > If I rollback to May version, it builds successfully.
> > 
> > 
> > How do you rollback to May version? Do you have a link?
> 
> https://github.com/google/mediapipe/releases/tag/v0.7.5
> You can download the older version as zip here

Or just do `mediapipe> git checkout v0.7.5`.

**Comment by Jayant-Jeet** [comment] 2020-07-25 03:19
> > > > When I run below command
> > > > `bazel build -c opt --define MEDIAPIPE_DISABLE_GPU=1 --action_env PYTHON_BIN_PATH="C://Python//Python37//python.exe" mediapipe/examples/desktop/hello_world`
> > > > it generates the error:
> > > > ```
> > > > ERROR: D:/git/mediapipe/mediapipe/framework/BUILD:824:1: C++ compilation of rule '//mediapipe/framework:packet' failed (Exit 2)
> > > > .\mediapipe/framework/packet.h(448): error C2672: 'absl::lts_2020_02_25::make_unique': no matching overloaded function found
> > > > .\mediapipe/framework/packet.h(448): error C2783: 'void std::make_unique(_Types &&...)': could not deduce template argument for '__formal'
> > > > C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.26.28801\include\memory(2078): note: see declaration of 'std::make_unique'
> > > > Target //mediapipe/examples/desktop/hello_world:hello_world failed to build
> > > > Use --verbose_failures to see the command lines of failed build steps.
> > > > INFO: Elapsed time: 71.407s, Critical Path: 68.40s
> > > > INFO: 152 processes: 152 local.
> > > > FAILED: Build did NOT complete successfully
> > > > ```
> > > > 
> > > > 
> > > > I am using C++ BuildTools version 14.26.28801
> > > > If I rollback to May version, it builds successfully.
> > > 
> > > 
> > > How do you rollback to May version? Do you have a link?
> > 
> > 
> > https://github.com/google/mediapipe/releases/tag/v0.7.5
> > You can download the older version as zip here
> 
> Or just do `mediapipe> git checkout v0.7.5`.

Same issue. Rolling back to v0.7.5 works

**Comment by JERMYH** [comment] 2020-09-12 14:06
I have  exactly the same issue. I wonder know if there is a new way to fix it now instead rollback the version

**Comment by Max3LakaJUMP** [comment] 2020-10-03 08:18
It seems like:
https://stackoverflow.com/questions/49117293/templated-variables-bug-with-lambdas-in-visual-studio

This without lambda compiles:
template <typename T>
std::unique_ptr<Holder<T>> GetPointer()
{
    return absl::make_unique<Holder<T>>(new T);
}
template <typename T>
NoDestructor<mediapipe::RegistrationToken>
    MessageRegistrationImpl<T>::registration(MessageHolderRegistry::Register(
        T{}.GetTypeName(), GetPointer<T>));

**Comment by Max3LakaJUMP** [comment] 2020-10-03 08:21
It seems like:
https://stackoverflow.com/questions/49117293/templated-variables-bug-with-lambdas-in-visual-studio

This without lambda compiles:
```
template <typename T>
std::unique_ptr<Holder<T>> GetPointer()
{
    return absl::make_unique<Holder<T>>(new T);
}
template <typename T>
NoDestructor<mediapipe::RegistrationToken>
    MessageRegistrationImpl<T>::registration(MessageHolderRegistry::Register(
        T{}.GetTypeName(), GetPointer<T>));
```

**Comment by jiuqiant** [comment] 2020-10-10 02:56
See the fix at https://github.com/google/mediapipe/issues/975#issuecomment-706467559.

**Comment by jiuqiant** [comment] 2020-10-20 01:26
Fixed in https://github.com/google/mediapipe/commit/c828392681bc343a90e188c5ad5f295bada1eefb.

**Closed by jiuqiant** 2020-10-20 01:26 UTC
