### ISSUE TITLE
Segmentation fault (core dumped) on Ubuntu python only

### ISSUE THREAD

**Issue by sufiaji** [google/mediapipe#1734] opened 2021-03-12 04:44 UTC
Hi Team,

Thanks for this awesome framework. However I encountered error when running the Python Face Mesh solution on Ubuntu 20.04. Instead of re-open the issue #1720 , I create a new issue here and let me mention the detail problem.

Platform: Ubuntu 20.04
Python: 3.8.5
Solution: Face Mesh

Note that this error doesn't happen on MacOS and Windows 10.

below is the code I try to run:

![image](https://user-images.githubusercontent.com/7789546/110892946-96afd100-8327-11eb-8ee1-3d008a0b3f21.png)

and the error raised as below:

![image](https://user-images.githubusercontent.com/7789546/110893203-19d12700-8328-11eb-8cc8-15fa8e33e0dc.png)

the mediapipe code that hits error:

![image](https://user-images.githubusercontent.com/7789546/110894055-bfd16100-8329-11eb-8598-fa88b5f50bb8.png)

Kindly advise since we need to run our program on Ubuntu.
Thank you

**Comment by gkarpiak** [comment] 2021-03-16 17:04
Hi @sufiaji , thank you for your interest in MediaPipe.

Could you please try to run Face Mesh sample on the same machine using pure C++? That should help to narrow down the problem. (If it runs correctly, then the problem is in python wrapper.)

**Comment by sufiaji** [comment] 2021-03-18 07:57
Hello @gkarpiak ,

Thanks for the reply. Could you please advise the step to run example of face mesh C++ on Ubuntu? I am able to run the Hello World example on my Ubuntu, but struggling to find face mesh C++ example...

Thank you!

**Comment by sgowroji** [comment] 2021-03-18 12:32
Closing this issue as we see you resolved!

**Comment by sufiaji** [comment] 2021-03-18 14:23
Hi @sgowroji 

This issue is not resolved yet, @gkarpiak asked to test using C++ to narrow down the problem, and I have tested with C++ sample and Ok. So now we know that the problem need to be resolved by the mediapipe team is on the python wrapper.

Thank you.

**Comment by jiuqiant** [comment] 2021-03-19 17:26
Do you run into this issue on a particular video or it crashes on every video or even webcam input? We need to a deterministic way to reproduce this issue first.

**Comment by sufiaji** [comment] 2021-03-21 14:27
Hi @jiuqiant 
Thanks for the mentioned steps to investigate. After several tests, this dump happen on every video. I create a simple python script to do the stress test, by iterating the subroutine screenshot above (up to 1000 iterations). So every iteration, the program will process all frames in a video file (from 1st frame into last frame), then next iteration it will repeat the same process. The dump hits on different iteration even on the same video. Sometimes the dump hits on iteration 19, 41, 98, or even 500. 
I will continue to test from webcam.
Thank you.

**Comment by jiuqiant** [comment] 2021-03-21 18:58
I tested MP FaceMesh API on a clean GCP ubuntu 20.04 instance (https://cloud.google.com/compute/docs/images/os-details#ubuntu_lts) with two test videos (a 7 seconds long and a 36 seconds long) and both of them look fine to me. I suggest that you can reproduce it on a clean ubuntu20.04 instance and report the detailed steps back.

My test video:
I trimmed  https://www.youtube.com/watch?v=n_Cn8eFo7u8 for testing. The short test video I use is from 31s to 39s and the long video is from 3s to 39s.

My test code:

<img width="825" alt="Screen Shot 2021-03-21 at 11 38 08 AM" src="https://user-images.githubusercontent.com/3359144/111916824-103b7380-8a3a-11eb-8632-bc11f86d3443.png">

My terminal outputs:

<img width="965" alt="Screen Shot 2021-03-21 at 11 53 52 AM" src="https://user-images.githubusercontent.com/3359144/111917234-22b6ac80-8a3c-11eb-9115-8bd833db4552.png">

<img width="897" alt="Screen Shot 2021-03-21 at 11 31 31 AM" src="https://user-images.githubusercontent.com/3359144/111916844-26493400-8a3a-11eb-9650-1b6c4dc60c2f.png">

**Comment by sufiaji** [comment] 2021-03-22 04:35
Hi @jiuqiant 

Thanks for your video, I will test and report back. 
Could you please also test mine? 
https://youtu.be/kX6Jb-ziYVU
A 2 seconds video with 1080p resolution. It crash on iteration less than 100 on my Ubuntu.

Thank you

**Comment by sgowroji** [comment] 2021-03-29 11:15
Hi @sufiaji , Can you share the status of this issue. Thanks!

**Comment by sufiaji** [comment] 2021-03-29 11:26
Dear @jiuqiant @sgowroji 

Apologize for being too long to response.
I tried the trimmed video as suggested by @jiuqiant , the 36s video... and it was dump on iteration 33 as below

![image](https://user-images.githubusercontent.com/7789546/112829733-bbdc6780-90bb-11eb-9e80-c672b70d1622.png)

This is the code:

![image](https://user-images.githubusercontent.com/7789546/112829826-e0384400-90bb-11eb-8338-122f1fc31df7.png)

![image](https://user-images.githubusercontent.com/7789546/112829951-107fe280-90bc-11eb-9142-583e91c35576.png)

We also tried on Docker as well and it was giving the same dump, although not on the same iteration.

Please advise.
Thank you

**Comment by sgowroji** [comment] 2021-04-09 07:17
Hi @sufiaji, Could you please confirm your issue status. And where you need guidance. Thanks!

**Comment by sufiaji** [comment] 2021-04-09 15:09
Hi @sgowroji 
Thanks for replying.

This issue is still open, since I still encounter the error when trying the video suggested by @jiuqiant , even I run in Docker container. As mentioned above, the python error **Segmentation fault** raised on mediapipe/python/solutions/face_mesh.py and mediapipe/python/solution_base.py. 
I need the guidance on how to eliminate those errors.
Thank you!

**Comment by sgowroji** [comment] 2021-04-09 15:17
Hi @sufiaji, could you please mention the complete error details, so that @jiuqiant can have a look over. Thanks!

**Comment by sufiaji** [comment] 2021-04-09 16:06
Hi @sgowroji ,

Please find below the detailed error in plain text:

Fatal Python error: Segmentation fault

Thread 0x00007fbe0a2dc700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 232 in _on_run
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fbe0aadd700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/pydevd.py", line 186 in _on_run
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fbe0b2de700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 302 in wait
  File "/usr/lib/python3.8/threading.py", line 558 in wait
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_timeout.py", line 43 in _on_run
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fbe0badf700 (most recent call first):
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 210 in _read_line
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 228 in _on_run
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fbe0c2e0700 (most recent call first):
  File "/usr/lib/python3.8/threading.py", line 306 in wait
  File "/usr/lib/python3.8/queue.py", line 179 in get
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_comm.py", line 339 in _on_run
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_daemon_thread.py", line 46 in run
  File "/usr/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 890 in _bootstrap

Current thread 0x00007fbe0da88740 (most recent call first):
  File "/home/pradhonoaji/Documents/facespoof/facespoofenv/lib/python3.8/site-packages/mediapipe/python/solution_base.py", line 290 in process
  File "/home/pradhonoaji/Documents/facespoof/facespoofenv/lib/python3.8/site-packages/mediapipe/python/solutions/face_mesh.py", line 238 in process
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 97 in _run_module_code
  File "/usr/lib/python3.8/runpy.py", line 265 in run_path
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285 in run_file
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444 in main
  File "/home/pradhonoaji/.vscode/extensions/ms-python.python-2021.3.658691958/pythonFiles/lib/python/debugpy/__main__.py", line 45 in <module>
  File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main

**Comment by sufiaji** [comment] 2021-05-25 12:30
Hi @sgowroji , Hope you're doing good.
Any update on this matter?
Thanks!

**Comment by jiuqiant** [comment] 2021-05-25 21:09
Can you try `pip install --index-url https://test.pypi.org/simple/ mediapipe==0.8.4.2.1`?

**Comment by sgowroji** [comment] 2021-05-28 06:13
Hi @sufiaji, Please try the above comment. Thanks!

**Comment by sgowroji** [comment] 2021-06-14 05:56
Hi @sufiaji, Thank you for responding. Could you please confirm the above with the latest release. Thanks!

**Closed** 2021-06-28 06:52 UTC
Labels: platform:python, solution:face mesh, stalled, stat:awaiting response, type:support
