### ISSUE TITLE
Difference between BlazePose demo and MediaPipe Pose Landmarker demo

### ISSUE THREAD

**Issue by philiprkk** [google/mediapipe#4849] opened 2023-10-03 07:20 UTC
Why is the web demo for BlazePose on https://storage.googleapis.com/tfjs-models/demos/pose-detection/index.html?model=blazepose so much smoother than the demo on MediaPipe studio https://mediapipe-studio.webapps.google.com/demo/pose_landmarker ? Is it remnants from this issue? https://github.com/google/mediapipe/issues/4809

**Comment by kuaashish** [comment] 2023-10-03 10:05
@philiprkk,

Unfortunately, we (the engineering team behind MediaPipe) cannot provide an answer to question like this. Product announcements and their associated performance are communicated through our blogs or other official channels.

**Comment by philiprkk** [comment] 2023-10-03 10:43
Is the engineering team not responsible for the MediaPipe Studio demos?

**Comment by schmidt-sebastian** [comment] 2023-10-03 20:35
We are working on smoothing the landmarks for Pose Landmarker. This will be merged soon.

Closing as this is a duplicate of https://github.com/google/mediapipe/issues/4715

**Closed by schmidt-sebastian** 2023-10-03 20:35 UTC
Labels: type:support, platform:javascript, stat:awaiting googler, task:pose landmarker
