### ISSUE TITLE
Detect key points for legs image

### ISSUE THREAD

**Issue by omaraga12** [google/mediapipe#4070] opened 2023-02-07 16:28 UTC
Hello, I was testing the project, it is so good, but the problema is that when I want to detect the keyt points of half body it does not detect, specially when it is legs, like this image:
![image](https://user-images.githubusercontent.com/64969223/217303857-c8921341-94f7-4055-8ff0-03e4c28e2e6e.png)
Is there a way that it can detect the poses in this kind o images?
Thank you so much

**Comment by ayushgdev** [comment] 2023-02-08 05:25
Hello @omaraga12 
Unfortunately, this will be a case where custom model training can help.
In our soltuion for realtime detection and tracking of the person in frame, we focus on detecting the bounding box of a relatively rigid body part like the human face or torso. Thus, if torso (or a part of it )is not visible, it is having hard time detection the human. Further, quoting from the [paper](https://arxiv.org/pdf/2006.10204.pdf)
"We restrict our dataset to those cases where either the whole person is visible, or where hips and shoulders keypoints can be confidently annotated."
Please refer the research paper in this [model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview) more details how the pose detection works. This might give a clue to develop custom solution.

**Comment by omaraga12** [comment] 2023-02-12 23:07
Thank you so much for your reply

**Comment by ayushgdev** [comment] 2023-02-13 06:17
@omaraga12 Can we conclude the issue is resolved and close it?

**Closed** 2023-02-13 06:24 UTC
Labels: type:support, stat:awaiting response, solution:pose

**Comment by azHq** [comment] 2023-12-18 09:59
when mediapipe will deploy their leg key points detection model?
