### ISSUE TITLE
Facemesh codepen not working on Desktop Safari 15

### ISSUE THREAD

**Issue by shubhamdawande** [google/mediapipe#2639] opened 2021-10-07 21:31 UTC
Hi all,

I am using mediapipe facemesh solution in my project. Currently it does not work on Desktop Safari 15 with WebGL 2 support. I am getting empty landmark output. This is however working fine on iOS Safari.

I noticed that the official codepen does not work as well and shows a black screen. Here's the link: [https://codepen.io/mediapipe/pen/KKgVaPJ](https://codepen.io/mediapipe/pen/KKgVaPJ). 

There's no failure stack trace in console.

> [Warning] I1008 02:24:52.405000 1 gl_context_webgl.cc:151] Successfully created a WebGL context with major version 3 and handle 3 (face_mesh_solution_wasm_bin.js, line 9)
[Warning] I1008 02:24:52.406000 1 gl_context.cc:351] GL version: 3.0 (OpenGL ES 3.0 (WebGL 2.0)) (face_mesh_solution_wasm_bin.js, line 9)
[Warning] W1008 02:24:52.407000 1 gl_context.cc:821] OpenGL error checking is disabled (face_mesh_solution_wasm_bin.js, line 9)

I understand that this solution mainly supports chrome. However it would be great if Safari fix can be looked into considering it now has WebGL 2 support.

**Comment by shubhamdawande** [comment] 2021-10-18 10:59
@mhays-google Any update on this?

**Comment by sgowroji** [comment] 2021-12-06 06:02
Hi @shubhamdawande, Demo running on Safari/Mac, is not well supported at this time, But still you can continue with it. Closing this issue at present as intended.

**Closed by sgowroji** 2021-12-06 06:02 UTC
Labels: platform:web, solution:face mesh, type:bug, stat:awaiting googler
