### ISSUE TITLE
Error importing mediapipe

### ISSUE THREAD

**Issue by ammarjafri** [google/mediapipe#1997] opened 2021-05-07 10:05 UTC
Hi, I am using https://google.github.io/mediapipe/getting_started/install.html#installing-on-debian-and-ubuntu guide to install, mediapipe on jetson nano. After downloading the file, when I import it there was no problem,
but when I use mediapipe.solutions.draw_utils so it gives error Attribute error: module 'mediapipe' has no attribute 'solutions', I did some research and found that __init__.py is empty in mediapipe folder, then I found the file in my PC, and edit __init__.py file and that when I try to import mediapipe it gives me this error:
File "usr/local/lib/python3.6/dist-packages/mediapipe/python__init__.py", line 17, in <module?
     from mediapipe.python._framework_bindings import resource_util
ModuleNotFoundError: No module named 'mediapipe.python._framework_bindings'
Although in python folder there is a file named _framework_bindings.cc

Please help me out to solve this problem, and pip install mediapipe does not work it gives error: could not find a version that satisfies the requirement mediapipe (from versions: )
No matching distribution found for mediapipe.

**Comment by sgowroji** [comment] 2021-05-07 10:52
Hi @ammarjafri, Could you please provide the complete steps to reproduce your error. Thanks!

**Comment by ammarjafri** [comment] 2021-05-07 11:03
> Hi @ammarjafri, Could you please provide the complete steps to reproduce your error. Thanks!

Just, Import mediapipe
in python3

**Comment by aoxipo** [comment] 2021-05-08 08:43
hello please tried `pip install  mediapipe` in terminal

**Comment by ammarjafri** [comment] 2021-05-08 15:29
> hello， please try `pip install mediapipe` in terminal

As I mention above pip install mediapipe gives this error:
could not find a version that satisfies the requirement mediapipe (from versions: )
No matching distribution found for mediapipe.

**Comment by sgowroji** [comment] 2021-05-20 09:34
Hi @ammarjafri, Please follow this https://github.com/google/mediapipe/issues/1959#issuecomment-830212097, https://github.com/google/mediapipe/issues/1674#issuecomment-788295898. Assuming the above is duplicate of this references.

**Comment by sgowroji** [comment] 2021-05-25 10:26
Hi @ammarjafri, Could you please check the above comment and respond to it. Thanks!

**Comment by sgowroji** [comment] 2021-06-01 06:25
Assuming your query answered in the above [comments](https://github.com/google/mediapipe/issues/1997#issuecomment-844914966). We are closing this issue now.

**Closed by sgowroji** 2021-06-01 06:25 UTC
Labels: platform:python, stat:awaiting response, type:support

**Comment by hhajae** [comment] 2021-06-01 08:34
@sgowroji 
help me. I am using "https://github.com/jiuqiant/mediapipe_python_aarch64" and "https://github.com/superuser789/MediaPipe-on-RaspberryPi#readme" guide to install mediapipe in Rasberrypi4 with Raspbian

When I ran "python3 setup.py gen_protos && python3 setup.py bdist_wheel",
/home/pi/mediapipe-0.8.4/mediapipe/python/BUILD:19:17: Linking mediapipe/python/_framework_bindings.so failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc @bazel-out/arm-opt/bin/mediapipe/python/_framework_bindings.so-2.params

Use --sandbox_debug to see verbose messages from the sandbox
/usr/bin/ld.gold: error: cannot find -ljpeg
/usr/bin/ld.gold: error: cannot find -ltiff
collect2: error: ld returned 1 exit status
Target //mediapipe/python:_framework_bindings.so failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 220.849s, Critical Path: 214.27s
INFO: 32 processes: 10 internal, 22 linux-sandbox.
FAILED: Build did NOT complete successfully
error: command 'bazel' failed with exit status 1

thank you.

**Comment by sgowroji** [comment] 2021-06-01 09:48
Hi @hhajae, Can you please raise it as a new issue with complete steps to reproduce the error. Thanks!

**Comment by hhajae** [comment] 2021-06-01 10:02
@sgowroji
I made new issue!
https://github.com/google/mediapipe/issues/2107#issue-908122389
Thank you.
